### ISSUE TITLE
L01E03

### ISSUE THREAD

**Issue by abhiojha8** [udacity/robotics-beta-test-issues#102]
Alongwith the links for Anaconda and Jupyter notebook, we can give a brief overview of how to setup the environment.

**Comment by abhiojha8** [comment]
abhio9vt L01E03

**Comment by ryan-keenan** [comment]
For now the instructions are just in the [link](https://github.com/ryan-keenan/RoboND-Python-Starterkit/blob/master/doc/configure_via_anaconda.md), but if it seems like further discussion here would be helpful as well we can always add it.
