### ISSUE TITLE
L02E03

### ISSUE THREAD

**Issue by bpinaya** [udacity/robotics-beta-test-issues#118]
When setting up the jupyter notebook, the default page is password protected, either instructions should be given to disable the psw or this should be taken care of, it just forces the student to go through some links to find out what is needed to disable the psw.

**Comment by ryan-keenan** [comment]
Hmmm... I'm not familiar with this, could you elaborate on where and when this is happening?

**Comment by bpinaya** [comment]
![image](https://cloud.githubusercontent.com/assets/2473733/25316948/c480b34a-283d-11e7-9fa8-da5429ad57ba.png)
When setting up the conda env. After following the steps.
My work env is: 
Linux asusrog 4.4.0-71-generic #92~14.04.1-Ubuntu SMP Fri Mar 24 15:22:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Browser: Chrome Version 57.0.2987.133 (64-bit)

**Comment by ryan-keenan** [comment]
I haven't run into this myself and I haven't heard from others on this so I'm going to close this for now but definitely will revisit if the issue comes up again!
