### ISSUE TITLE
philLudewig P01E08

### ISSUE THREAD

**Issue by stupsi99** [udacity/robotics-beta-test-issues#120]
It would help a lot to keep an overview of what variable stands for what, if they were labeled with a coordinate system. E.g. "W" for world, or "R" for rover.

Even though the project is still quite small, it would help the students to keep an overview of the coordinate transformations.

**Comment by ryan-keenan** [comment]
This is a great point.  I've tried to clear up variable names so this is clear but for now I haven't gone with any particular convention.  Will definitely revisit this if confusion persists.
