### ISSUE TITLE
rajmis P01E03

### ISSUE THREAD

**Issue by rajmis** [udacity/robotics-beta-test-issues#126]
Instructions are quite well articulated. However, I would like to add a small thing to the list, might help a newbie to avoid a simple error.
"If you're doing a fresh install for Anaconda, please restart your bash (terminal) after successful installation. Otherwise, it might give an error that conda command is not found!"

**Comment by ryan-keenan** [comment]
The Anaconda setup docs do make this suggestion, but for good measure  I've added a note to the instructions in the `configure_via_anaconda.md` file
