### ISSUE TITLE
rajmis P01E03

### ISSUE THREAD

**Issue by rajmis** [udacity/robotics-beta-test-issues#127]
Again, this is just a suggestion that might improve the debugging process for setting up the environment-
"While creating the anaconda environment using environment.yml, if it crashes in between due to internet issues or timed out HTTP request then use the following command - conda env remove -n robond-term1 and restart it again."
For some reason, the environment name for my setup is robond-term1 and not RoboND.

**Comment by ryan-keenan** [comment]
Great suggestion!  I've added this to the instructions in `configure_via_anaconda.md`
