### ISSUE TITLE
benpinaya Simulator

### ISSUE THREAD

**Issue by bpinaya** [udacity/robotics-beta-test-issues#151]
I am running the simulator and going around the environment but I can't find those yellow rocks, I don't know where the flag Show/Hide samples is enabled or disabled by default. It would be useful to have a way to know where this is on/off. So far I can't find the yellow rocks.

**Comment by bpinaya** [comment]
After more careful navigation I could find the rocks, but still a flag indicating if the yellow rocks are shown would be very helpful.

**Comment by ryan-keenan** [comment]
Thanks for the feedback here, I think I'll just change it so the rocks are always on.
