### ISSUE TITLE
sagunms P1E6 Video walkthrough on Perspective transformation

### ISSUE THREAD

**Issue by sagunms** [udacity/robotics-beta-test-issues#156]
A video demonstration similar to [CarND video](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/2b62a1c3-e151-4a0e-b6b6-e424fa46ceab/lessons/40ec78ee-fb7c-4b53-94a8-028c5c60b858/concepts/5aba544c-13b9-440f-b35c-f67aef7e2946) would be really good because there are a lot of concepts going on in a single page. 

- Explaining the intuition behind Perspective Transformation
- Walkthrough about how the source coordinates for the transform are obtained via Matplotlib interface
- Python notebook walkthrough on cv2 wrapPerspective function and output image produced

I think this would be really good and why this would be a good basis for a map representation.

**Comment by Shreeyak** [comment]
I second this. Was about to post an issue regarding the same. Some more context needs to be given about perspectives and transformation. A small video or a gif and few lines should be included at least.

**Comment by ryan-keenan** [comment]
Thanks for the feedback on this!  I am working on putting something together here :).

**Comment by ryan-keenan** [comment]
video now in the classroom!
