### ISSUE TITLE
sagun Typos in the course text

### ISSUE THREAD

**Issue by sagunms** [udacity/robotics-beta-test-issues#158]
Although the text material is good, I have noticed multiple sections requires proof reading. Perhaps we should have dedicated issue just for proof reading?

Here are a few:

### Meet Your Instructors:
change " control real **robot!**" - " control real **robots!**"

### Projects You will build
"pick up an object from one location and **put it another**"
"pick up an object from one location and **put it in another**"

### 3. Setting up your Environment
**continuum analytics** should be Title Case. 

Change:
"The instructions for getting setup are in **a GitHub repositories**"
to something like:
should be "The instructions for getting set up **are available in [this GitHub] repository**"

### 4. Recording Camera Data

Change the following text:
called “ IMG” to store
to:
called `IMG` to store - probably use Markdown to highlight instead of using double quotes.

matplotlib should be Title Case. 

### 8. Map to World Coordinates
Change:
**You** goal in this exercise to write code that will allow you to use the rover's position, ...
to:
**Your** goal in this exercise to write code that will allow you to use the rover's position, ...

### 9. Which Way to Go?
Change:
**Once** simple way to decide is to choose the direction with the most navigable terrain!
To:
**One** simple way to decide is to choose the direction with the most navigable terrain!

**Comment by ryan-keenan** [comment]
Thanks for catching all these typos!  All fixed now :)
