### ISSUE TITLE
P1E5: Image name changes

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#161]
When you download the sample image using the link provided, the filename is 'sample.jpg'. In the exercise, this image is called 'sample1.jpg'. It is not a big deal, but I think the name should be the same. In addition, there is no link to download the other five images if you want to test the program on your local machine.

**Comment by ryan-keenan** [comment]
Thanks for the feedback!  I've gone through and changed it to `sample.jpg` throughout
