### ISSUE TITLE
P1E6: Missing %matplotlib inline

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#162]
The color thresholding exercise (P1E5) includes the following line in the code snippet:
 
# Uncomment the next line for use in a Jupyter notebook
#%matplotlib inline

This is not included in the first code snippet here, and if you copy this code directly into a Jupyter notebook, the image won't show.

**Comment by ryan-keenan** [comment]
Thanks for catching this!  I've added this now to the next couple quiz pages
