### ISSUE TITLE
Running Simulator on Ubuntu

### ISSUE THREAD

**Issue by maunesh** [udacity/robotics-beta-test-issues#17]

**Comment by maunesh** [comment]
Do we need to download anything else to run the Roversim?
I am running Ubuntu 14.04, and after I launch the simulator, it closes itself.
I have tried different Graphcs and Display options, but no luck.

**Comment by ryan-keenan** [comment]
Hmm... shouldn't be a problem but I'll look into it.  Thanks for reporting!

**Comment by letyrodridc** [comment]
I've Ubuntu 16.04, and it's working.

**Comment by maunesh** [comment]
I found few hints on StackOverflow, but the simulator works fine on Mac, so I don't plan to debug further.
