### ISSUE TITLE
vivek1108: Is project 1 for exploring alone?

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#173]
Is project 1 for exploring alone? or for picking the object too? I dont see a flag that tells we are near the object, nor an action command to send to the robot to pick the object.

**Comment by vxy10** [comment]
nevermind, found it.

**Comment by vxy10** [comment]
Am still not sure how to send commands for picking_up and near_sample, i tried sending fixed_turn but that didnt cause the turn. Also, in send_control() function, the variables for picking_up and near_sample are not written, only steer, throttle and brake are written.

**Comment by ryan-keenan** [comment]
This is all very true!  So far it's only setup for mapping and navigation but you should be able to add another input to the `send_control()` function to do pickup if you like.  If you are near a sample and you send the flag to pickup it should do it (though I haven't tried yet).  I'm planning to update soon with instructions on how to use this functionality
