### ISSUE TITLE
Broken Link on simulator

### ISSUE THREAD

**Issue by thiagodefreitas** [udacity/robotics-beta-test-issues#175]
Probably still intentional, but just to emphasize that the link for the environment build is still broken on the *Exploring the Simulator* section

**Comment by ryan-keenan** [comment]
Actually these should work, which build were you trying to download?

**Comment by thiagodefreitas** [comment]
Just tried again, and the link is working for me, now.

**Comment by thiagodefreitas** [comment]
just to be clearer, there is a linked page now: https://github.com/udacity/RoboND-Rover-Unity-Simulator, although this leads to a 404 error page, but I presume this is intentional for now.

**Comment by ryan-keenan** [comment]
Ah thanks for catching that, the repo was still private but I just made it public.
