### ISSUE TITLE
P01 Color Thresholding

### ISSUE THREAD

**Issue by thiagodefreitas** [udacity/robotics-beta-test-issues#176]
The solution part contains only the color_thresh function.
Although the rgb_thresh is hardcoded for (160,160,160). 

If you copy the solution, the problem is not solved.

So, in my opinion, either the full source should be added or at least, the:
red_threshold = 160
green_threshold = 160
blue_threshold = 160

**Comment by ryan-keenan** [comment]
That's a good point!  I've changed it now so the solution function has `rgb_thresh=(0, 0, 0)` like the example but the values for the thresholds are listed below.
