### ISSUE TITLE
sagun P01 Use relative path in robot_log.csv

### ISSUE THREAD

**Issue by sagunms** [udacity/robotics-beta-test-issues#178]
Latest commit 45c1d69 uses robot_log.csv containing absolute path. Running ipython notebook on test data breaks.

Easy fix to convert absolute to relative:
```
cd test_dataset
sed -i -e 's/\/Users\/ryan\/Desktop\/RoboND\/Roversim\/student_beta_rover/\.\./g' robot_log.csv
```

**Comment by ryan-keenan** [comment]
Aaagghhh!  Thanks for catching this.  Just recorded new test data today and forgot about the relative path thing.  It's fixed now and pushed to the repo
