### ISSUE TITLE
sagun P01 Fix ipynb reference to new ground truth image extension

### ISSUE THREAD

**Issue by sagunms** [udacity/robotics-beta-test-issues#179]
Latest commit 45c1d69 ipynb is still referring to the old map_bw.jpg. Now that the filename is map_bw.png, change the following line:
```
ground_truth = mpimg.imread('../calibration_images/map_bw.jpg')
```
to:
```
ground_truth = mpimg.imread('../calibration_images/map_bw.png')
```

**Comment by ryan-keenan** [comment]
This has been fixed in the latest update.  Thanks for reporting!
