### ISSUE TITLE
sagun P01 Name 'to_radial_coords' is not defined ipynb

### ISSUE THREAD

**Issue by sagunms** [udacity/robotics-beta-test-issues#180]
In Coordinate Transformation part of IPython notebook, 'to_radial_coords' function has been changed to 'to_polar_coords'. Since the code is still looking for the old function name, we get:
`NameError: name 'to_radial_coords' is not defined`.

Also, the plot and the mean arrow doesn't look right.

**Comment by ryan-keenan** [comment]
Thanks for reporting this.  I've been updating the notebook a lot in the past 24 hours to accommodate changes in the lesson.  This (and a number of other things) should be fixed / better now!
