### ISSUE TITLE
sagun P01E07 Blue-coloured plots in the first summary image different from explanation?

### ISSUE THREAD

**Issue by sagunms** [udacity/robotics-beta-test-issues#181]
The first summary image of Wrap, Threshold, and Map lecture says: "Note the change in coordinates from the lower left to lower right images.". The blue-coloured plot that represent rover-coordinates in the first summary seems inconsistent with the blue plots in the explanation (and the quiz result) so I am not sure if it is correct.

**Comment by ryan-keenan** [comment]
thanks for pointing this out!  I just changed the way we're doing this coordinate transform yesterday but hadn't cleaned up all the old images.  Fixed now.
