### ISSUE TITLE
The Perception Step

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#190]
since most of the students taking this course will be having some background python and image processing, they might get confused with the step 
red_channel[:,:,[1, 2]] = 0

for displaying red channel , with the fundamental way of extracting red channel from an RGB image by using
red_channel = img[:,:,0]

a single line explanation stating the specific use of 
red_channel[:,:,[1, 2]] = 0
instead of the traditional method will be helpful for experienced students

like

red_channel[:,:,[1, 2]] = 0 # this line outputs an image with only red channel value dominating the RGB image without changing the Depth of the image (Depth is still 3 , in old method, it will get reduced to 1)

**Comment by ryan-keenan** [comment]
Thanks for pointing this out, I've added a comment about this in the code.
