### ISSUE TITLE
Perspective transform

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#191]
without an introduction to open cv , it might be hard for students to digest perspective transformations concept . adding these links might give them an idea of what perspective transformation is going to do to the image and why bird's eye view is needed for the purpose of navigation

http://docs.opencv.org/trunk/da/d6e/tutorial_py_geometric_transformations.html

http://www.pyimagesearch.com/2014/08/25/4-point-opencv-getperspective-transform-example/

**Comment by ryan-keenan** [comment]
Thanks for this recommendation!  I added the first link to the lesson.  I'll leave out the link to PyImageSearch for now since he's selling his own courses on CV but a quick search will lead folks to that page if they are looking for more information.
