### ISSUE TITLE
sjuneja P01 Windows Simulator

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#192]
Tried it quite a few times, but holding the "Alt" key after launching the simulator doesn't bring up the options to set resolution and graphics quality for the simulator.

**Comment by sahiljuneja** [comment]
cc - @ryan-keenan

**Comment by sahiljuneja** [comment]
Okay, figured this out.

You have to press and hold "Alt" right after you double-click on the exe to launch the simulator.

I was pressing and holding "Alt" after the simulator had just started, which doesn't work.

**Comment by ryan-keenan** [comment]
I added a note in the classroom about this ;)
