### ISSUE TITLE
sjuneja L02E4 Recording Data

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#193]
Since this is a career focused ND, it would help if you went into slightly more details on Telemetry so that they understand it better to be able to talk about it.

Explaining roll, pitch, yaw angles w.r.t a mobile robot would be good for beginners. Giving a link to the angles with respect to the plane might not translate too well for new students. How exactly does pitch happen for a mobile robot? That's one question I would expect someone to try to understand. 

I know this is not a college or graduate level course, but you have to assume students with no background. And something like "Rover's orientation with respect to the world" might not be intuitive enough for everyone as per me.

[If the above is explained properly in future lessons, then a note here, in the lesson, stating that would be good to reassure students]

**Comment by ryan-keenan** [comment]
Thanks for bringing this up.  I found a better post to link to that I think covers the concepts of roll, pitch and yaw in more detail and has a nice image of a mobile robot with the correct indications for roll, pitch and yaw.  For now I'm going to leave it at that, but will add more if this is a sticking point for students.
