### ISSUE TITLE
sjuneja L02E05 The Perception Step

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#194]
It would be great if there could be a very small paragraph on numpy along with a couple of resources for students to learn more about numpy. 

For SDCND Term 1, initially, quite a few students faced problems with numpy if I remember correctly. So a couple of resources might help. 

Maybe this http://cs231n.github.io/python-numpy-tutorial/#numpy or https://github.com/rougier/numpy-tutorial

**Comment by ryan-keenan** [comment]
Great recommendation!  Julia sent me a nice link to a numpy crash course on image processing so I linked to that.  I think it should be sufficient to get people familiarized.
