### ISSUE TITLE
RoboND-Python-Starterkit

### ISSUE THREAD

**Issue by celibertojr** [udacity/robotics-beta-test-issues#197]
to be able to do  'conda env create -f environment.yml' with success in Windows (8.1) need to start a Command Prompt as an Administrator or the installation will fail.

**Comment by jchernus** [comment]
You should be running that command from Anaconda, not cmd. Does it fail when you run it in Anaconda? Maybe you need to launch Anaconda with admin privileges - but mine worked fine without.

**Comment by rohts-patil** [comment]
I could do it by the normal way.

**Comment by ryan-keenan** [comment]
I'll close this for now, please reopen if the issue persists.
