### ISSUE TITLE
Map to World Coordinates

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#198]
Rotation matrix formula seems to be good but , the fundamental theory of cartesian coordinate system and the reason for applying Rotation and translation is missing. 

the addition of these details might facilitate students who are not having Robotic background . 

i would like to provide my suggestion on how i like to put this forward

" After generating robot centric coordinate system representing the drivable area , we need toconvert this to  world map. for this purpose we are going to use the robots position (X,Y) on the map and the yaw value to convert the points in robot space to map space . 
Step 1 : Rotate or turn  the drivable pixels with respect the the robots yaw

step 2 : Translate or move the data to the current robot's (X,Y) position 

these steps will rotate and move the drivable pixel data to the current position of the robot
this is the use of rotation and Translation 

 "
feel free to modify this

**Comment by ryan-keenan** [comment]
Thank you for this suggestion!  I've added something similar to this in the classroom now to clarify this section.
