### ISSUE TITLE
P01 - 2 Exporing the simulation - You can give more details for beginners in paragraph 6.

### ISSUE THREAD

**Issue by GabrielDGP** [udacity/robotics-beta-test-issues#199]
P01 - 2 Exporing the simulation - You can give more details for beginners in paragraph 6.

In the second paragraph of Download and Launch the Simulator, for people who use windows.
In the instruction to enter the resolution settings, more details can be given to access this configuration window. For example, make it more explicit that you have to immediatly secure the alt after double clicking the Roversim.exe file and that if you hold the alt and click on the file you will not have access to this window, just as if you take a while to hold the alt You will not have access to this configuration window.

**Comment by ryan-keenan** [comment]
Thanks for raising this issue!  Sahil also pointed this out and I've now added a little extra text in the classroom
