### ISSUE TITLE
P01 -  4. Recording Data

### ISSUE THREAD

**Issue by GabrielDGP** [udacity/robotics-beta-test-issues#200]
To inform that pressing R, you choose the place that  the data will be saved.
It Shows that it appears written that is recording in the simulator, then you move the robot.
If you want to finish recording and have the telemetry data and images you press again R, which will effectively save this data.

Explaining this can be useful, because several times I came back in the folder I chose to see the recorded data without pressing the R again and I had nothing saved.

**Comment by ryan-keenan** [comment]
Thanks for this feedback!  I've added a note in parentheses to hit `r` a second time and I've also recorded a video on this topic that will be in the classroom soon.
