### ISSUE TITLE
L02E05 - Add External Numpy Resources

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#201]
If a student has never seen or worked with numpy, this lesson will be a steep learning curve. I think that would be okay later in the term, when you have them hooked already and feeling confident, but this early on some people will feel very uneasy and unsupported.

I would suggest providing students with a resource (such as this: http://scikit-image.org/docs/dev/user_guide/numpy_images.html) to help them familiarize themselves with numpy. I suggested this particular resource because it is specifically about images, and talks about masking very early on.

**Comment by ryan-keenan** [comment]
Great suggestion!  I've added this link where numpy is introduced now.
