### ISSUE TITLE
L02E07 Warp, Threshold and Map

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#202]
the problem which confused me is when i saw the image 

plt.imshow(colorsel)

where the drivable area is appearing bottom to top , But after i extract the non Zero points and plot them 

ypos, xpos = colorsel.nonzero()
plt.plot(xpos, ypos, '.')
plt.xlim(0, 320)
plt.ylim(0, 160)
plt.show() 

the same image appears Top to bottom (inverted ) , 

later , i understand that there is a change  in the (0,0) position 

that is , in the first image (colorsel) the (0,0) is at the top left and in the next image (0,0) is at the bottom left 

A single line explaining this shift can facilitate the learning process

**Comment by ryan-keenan** [comment]
Great suggestion!  I've added a line explaining this.
