### ISSUE TITLE
Autonomous mode

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#203]
lot of explanation is given which is confusing and requires repeated reading . if you can cut short this section , it will be easy for the readers 

only focus on the important things like process_image function and few others .

**Comment by ryan-keenan** [comment]
This is definitely a good point!  I've cut out some of the repetitive sections of this page but it is still fairly long and dense.  My goal here was just to provide some "documentation" of the code used in the project.  Hopefully it is a bit cleaner now!
