### ISSUE TITLE
L02E07 - Add image to dense paragraph

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#208]
The text below could really use an image to help describe it. Students who aren't familiar with yaw will be confused. The image at the top is helpful, but scrolling up and down to read text, look at image, continue reading text... is unproductive.

Also, leftt => left. 

"The orientation of the rover in world space is its yaw angle, and is measured counterclockwise from the positive x-direction. Here we'll define pixel positions in rover-centric coordinates to have the origin at the bottom center of the warped image, with x increasing vertically from bottom to top, and y increasing right to leftt. In this way, when the rover is at the origin in the world coordinate system and oriented at a yaw angle of 0, it's coordinates will match the world coordinates."

**Comment by ryan-keenan** [comment]
This is great feedback.  I shuffled things around so this statement appears at the end below the final image and the text is a bit more concise.
