### ISSUE TITLE
Shreeyak P01E02

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#209]
The "alt " command to bring up the settings doesn't work for me. I'm using Ubuntu. Also, there are screenshots for MacOS and Windows but none for Ubuntu. Tried hitting alt on startup for 5min.

**Comment by ryan-keenan** [comment]
Thanks for reporting this! On windows you need to double click then hit Alt immediately... does that work for you? I'm considering dropping this "feature" and just having that screen pop up every time you launch

**Comment by Shreeyak** [comment]
That did not work for me, no. I read the thread on this at slack, tried
everything. Couldn't get it working. Best would be to add an menu option in
the start screen or always have this option pop up.

**Comment by ryan-keenan** [comment]
The new version of the sim brings this window up automatically, no need to hold alt down

**Comment by ryan-keenan** [comment]
The new version of the sim brings this window up automatically, no need to press alt
