### ISSUE TITLE
Shreeyak P01E04: sensor noise explanation

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#210]
It is mentioned how real sensors have noise that has to be dealt with. From talking to people, many have no idea what noise means or what it looks like. I think it'll be a good idea to add an image showing noise in real sensors and how simulators don't have that noise. 

I believe that this is a very important concept to keep in mind and that some time should be spent on it.

**Comment by ryan-keenan** [comment]
I agree this is an important issue but I don't want to take too much of a tangent on it here in the lesson.  I've added a link to the Wikipedia article on signal processing noise and a few more words of clarification.
