### ISSUE TITLE
p01 pix_to_world yuvaram

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#222]
in the jupyter notebook provided for the project , there is a small misspelling 

worldsize 

def pix_to_world(xpix, ypix, x_rover, y_rover, yaw_rover, worldsize, scale):

but inside the function 

world_size  is used 

x_pix_world = np.clip(np.int_((((xpix * np.cos(yaw)) - (ypix * np.sin(yaw)))/scale) + x_rover), 
                            0, world_size - 1)

**Comment by ryan-keenan** [comment]
Thanks for catching this!  just fixed it
