### ISSUE TITLE
sychaichangkun p01 pix_to_world

### ISSUE THREAD

**Issue by sychaichangkun** [udacity/robotics-beta-test-issues#223]
In the perception.py Project 01, the function pix_to_world() works well. But in the Rover_Project_Test_Notebook.ipynb, I need to set yaw = np.pi/2 - yaw = yaw_rover * np.pi / 180  in func pix_to_world().  I haven't find out there the bug come from.

**Comment by sychaichangkun** [comment]
Ignore this issue please. The problem get solved after updating the beta_rover.

**Comment by ryan-keenan** [comment]
cool thanks!
