### ISSUE TITLE
P01 lesson 8 need more clarification

### ISSUE THREAD

**Issue by Mohammed-Tag-ElAsfia** [udacity/robotics-beta-test-issues#229]
I suggest to add pictures with coordinates x,y on rover to show this what is meant by x_vec and y_vec and how they differ from x_rover and y_rover because i feel it makes confusion

do if you put picture are explain what each notation in that lesson refer to, that will make things lucid

**Comment by ryan-keenan** [comment]
Hey, could you please refresh that page?  I think you might be looking at an older version (x_vec and y_vec are not in there anymore)

**Comment by ryan-keenan** [comment]
I'm going to close this for now
