### ISSUE TITLE
L03 intro to ros

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#232]
my suggestion will be to have "Sourcing the ROS Environment" before "ROS File Navigation Commands"

My reason :
 if we try to run roscd and rosls commands , we are getting errors that roscd command is not found . this is becouse we haven't set our ros environment in bash . so it will be good if we can chage the order

**Comment by bkinman** [comment]
Thanks for the feedback! This makes sense. I've decided to go ahead and remove "ROS File Navigations Commands" for now. I don't feel that it adds much to the material in it's current form.
