### ISSUE TITLE
L05E07 - ROS cheat sheet link broken

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#234]
The cheat sheet link is broken. This is the link for the last 'official' cheat sheet I've found: https://github.com/ros/cheatsheet/releases/download/0.0.1/ROScheatsheet_catkin.pdf

It seems to be a little bit old (Indigo release, two years ago).

**Comment by bkinman** [comment]
Awesome, thanks! I've updated the link.

It is indeed a bit old. But I'm pretty sure that most, if not all, of the commands there still work.
