### ISSUE TITLE
Shreeyak P01: Announce tools used in project

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#236]
Hey, I spent a significant amount of time exploring the tools used in this project (miniconda, jupyter, numpy). Very interesting and useful tools!
There are several courses linked to that cover these topics. I think these topics and courses  should be released to people to get familiar with before the course starts. It's a LOT of info to go through in the first week. It will be a lot easier if the tools used are a little familiar beforehand.
Many people have been asking on slack for topics to peruse before course starts.

**Comment by ryan-keenan** [comment]
This is great point!  I will bring this up and see if we can incorporate all of these things into the FAQ and pre-classroom experience.
