### ISSUE TITLE
cornzyblack L03E01

### ISSUE THREAD

**Issue by cornzyblack** [udacity/robotics-beta-test-issues#237]
I like the fact that the history was brief, after all this is not an ROS history class. I also like the fact that a link was provided in the episode for the learner to read more about the history of ROS. However, it would be nice if you chipped in what the ROS acronym actually stands for probably at the beginning of line 1

"Development of ROS (Robot Operating System)... "

**Comment by bkinman** [comment]
Indeed, that would have helped.

We did add a new video "welcome to ROS essentials", where to clear up the acronym. This precedes "Brief History of ROS".
