### ISSUE TITLE
P1 Search and Sample Return -L5 and L6

### ISSUE THREAD

**Issue by GabrielDGP** [udacity/robotics-beta-test-issues#239]
In the last line of the codes it is written
plt.show() # not required inside Jupyter notebook

I tried not to put this line in the code on jupyter, and it did not show the results.
I think this line is also needed to show the results on jupyter.

**Comment by Shreeyak** [comment]
For me, Jupyter still shows output if I don't put that line.

**Comment by ryan-keenan** [comment]
Hmm.... for me as well this line is not required.  I will keep an eye on this but closing for now.
