### ISSUE TITLE
L03E07

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#240]
Top comment, "Now that we’ve launched turtlesim_node, and played around with sending commands via the turtle_teleop_key node, let’s dig deeper, to see what actually happening underneath the surface..."

should read 

"Now that we’ve launched turtlesim_node, and played around with sending commands via the turtle_teleop_key node, let’s dig deeper, to see what is actually happening underneath the surface..."

Note the inserted 'is' in the last sentence.

**Comment by bkinman** [comment]
Good catch! I've fixed it!
