### ISSUE TITLE
L03E07 - Add definitions

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#241]
I think it would be helpful to provide students with a clear definition of a Topic, when you first mention one. And similarly, to a Message (though this one is a bit more self explanatory and thus won't need as much writing). 

Without this, students who have never seen ROS may be confused. They can read on and infer the meaning, but I think it's best that we make the lesson easy/user-friendly for them :)

**Comment by jchernus** [comment]
This can be marked Done.

**Comment by bkinman** [comment]
Awesome, will do ;) thanks for coming back to this.
