### ISSUE TITLE
Gabrcg P01

### ISSUE THREAD

**Issue by gabrcg** [udacity/robotics-beta-test-issues#245]
The sim is frying my Macbook. Maybe something can be changed in the Unity

**Comment by Shreeyak** [comment]
LoL! I'm sorry, but this comment is written beautifully!

**Comment by ryan-keenan** [comment]
I'll look into it!  You might try with lower graphics quality and resolution and see if it helps.

**Comment by ryan-keenan** [comment]
Seems the solution for now is just to run at lower resolution / graphics quality
