### ISSUE TITLE
issue with windows simulator

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#247]
i finished my coding and tested it in ubuntu . the simulator seems to work perfectly .(See the video)

https://www.youtube.com/watch?v=83KfL4-2NCM&t=1s

now , in windows simulator the same code is not working 

https://www.youtube.com/watch?v=6uuBA9gkUv8

please look into this problem

**Comment by ryan-keenan** [comment]
I can't see the video now, but my only guess here based on what other people have said is that it might have to do with the resolution and graphics quality you are using.   If it is different between the two machines, the results may be different as well.
