### ISSUE TITLE
P1 lesson 8 Quiz

### ISSUE THREAD

**Issue by Mohammed-Tag-ElAsfia** [udacity/robotics-beta-test-issues#248]
x_vec = (dist / 10) * np.sin(angles + yaw_rover)  
 y_vec = (dist / 10) * np.cos(angles + yaw_rover)

I think it should x component you should and multiply "dist" by "cos" not sin, and also y component needs to be corrected

**Comment by ryan-keenan** [comment]
This section has been modified quite a bit so these lines of code no longer exist.
