### ISSUE TITLE
installation of ros

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#258]
this problem happens only if you are not using the VM image provided by udacity . i have ubuntu 14 installed in my system 

ros kinetic is not designed for ubuntu 14 . so please specify that use of ubuntu 16 is must for  continue working on the projects in the course  if that student prefer not to use VM

**Comment by bkinman** [comment]
OSRF's instructions for installing ROS on the wiki mention that you must only use 16.04 for Kinetic.

We won't be explicitly supporting students installing ROS in linux natively... At least not for now, so I'm going to go ahead and close this.
