### ISSUE TITLE
sjuneja P01 Windows Simulator

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#259]
The simulator doesn't seem to be optimized for different viewing resolutions.

This is what I get for one of them (320x240)
![download](https://cloud.githubusercontent.com/assets/12501638/26033896/b03b892e-38d1-11e7-9617-53dc6721f3ae.png)

**Comment by ryan-keenan** [comment]
thanks for pointing this out! will be fixed soon!

**Comment by ryan-keenan** [comment]
this is fixed now :)
