### ISSUE TITLE
sjuneja P01 Windows Simulator Not Capturing

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#260]
It seems for long duration of moving around the simulator while recording is on, the simulator doesn't end up "capturing" the data at the end of the run.

It works fine for small runs.

**Comment by ryan-keenan** [comment]
not sure what the problem is here but I'll look into it!

**Comment by ryan-keenan** [comment]
I made a note of this in the notebook, but also that it is not necessary to capture a large amount of data.
