### ISSUE TITLE
sjuneja P01 Windows Simulator "Is Near Objective"

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#261]
When the data is being captured, the "Is Near Objective" doesn't change to "Yes" when the robot is close enough to the rock.

Don't you think that's helpful? Or you plan to have that as a useful parameter for a different project?

**Comment by ryan-keenan** [comment]
Interesting, I hadn't noticed that.  For now we're not outputting the "near_sample" flag to the csv file so it shouldn't matter.   However, I've added a page at the end of the lesson now called [Requirements & Challenges](https://classroom.udacity.com/nanodegrees/nd209-beta/parts/f491093d-8e67-4eab-8102-87bae095ca79/modules/0573f9ff-2e23-48cd-87d0-af24d758348a/lessons/ef841d31-8c53-49b3-8da3-a9d1523adef0/concepts/ed33ab6f-2b67-4991-b372-ab915538b734)  That describes how to use the "near_sample" flag in autonomous mode to do rock pickup.  Seems there may be still some problem with the "picking_up" flag in that it stays stuck on after pickup.  That will be sorted out soon.
