### ISSUE TITLE
sjuneja P01 Data Collection

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#262]
In the L02E14 it might help students if you clarified what exactly should the data collection contain. 

In terms of driving around the entire area and collect N number of samples? And stating that samples are generated randomly everytime it's restarted. 

Just a small line could help make it clear what kind and amount of data to collect. Because currently, the simulator is not allowing to capture large amounts of data in one go, so that's a hindrance.

**Comment by ryan-keenan** [comment]
good suggestion, I've added a note to the notebook saying the sim may crash if you record a large (longer than a few mins) dataset, but that you don't need a ton of data.  Hopefully that provides the necessary guidance!
