### ISSUE TITLE
Shreeyak P01E07: Why swap axes

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#265]
It is not clear to me why we swap the x and y axes to convert the image to rover-centric co-ords. Can you please elaborate here?

**Comment by Shreeyak** [comment]
Aah, You've mentioned ` oriented at a yaw angle of 0` . This part of the lesson could be edited to make it slightly better to go through (from `You are now looking down on the rover's world from above...` onwards)

**Comment by ryan-keenan** [comment]
I've moved things around a bit here so that the discussion of the "why" comes after the process of switching coordinate frames.  Hopefully this is more clear now
