### ISSUE TITLE
Shreeyak P01E07: Typo

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#266]
>Here we'll define pixel positions in rover-centric coordinates to have the origin at the bottom center of the warped image, with x increasing vertically from bottom to top, and y increasing right to leftt.

It should be `y increasing left to right`, yes? 
This whole paragraph is quite confusing, as stated in earlier issue #265 .

**Comment by ryan-keenan** [comment]
I agree. I've reworked this section now, hopefully more clear!
