### ISSUE TITLE
Shreeyak P01E07: plt.show() in Jupyter

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#267]
In the examples provided, this is mentioned: `plt.show() # not necessary inside Jupyter notebook`

I find that when I *do not* include this statement, I get in the output something like `Out[70]: (0,160)`. Don't quite understand why that is there or what it means. 

When I include `plt.show()` this statement does not appear.

Screenshot below

**Comment by Shreeyak** [comment]
![jupyter plt_show](https://cloud.githubusercontent.com/assets/12800185/26034572/56e05cdc-38dc-11e7-98c6-6f0bf3ffc1bf.png)

**Comment by Shreeyak** [comment]
Also get other messages, like this:
![jupyter plt_show 2](https://cloud.githubusercontent.com/assets/12800185/26034870/223ab7b6-38e1-11e7-87ac-bd3f03b8178e.png)

**Comment by ryan-keenan** [comment]
I'm not sure why that is either
