### ISSUE TITLE
sjuneja P01 Jupyter Test Notebook

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#268]
Wouldn't it be better to have this notebook built up by the students completely? 

While they work through the lessons, they can implement it in the notebook? And then use the final notebook and use that for the project? 

Because that would be a good practice for them with jupyter, and with the different functions sequentially instead of having to do it all at once. I know there are the individual quizzes, but just thought working on this directly for the project might help flatten the learning curve a bit for this first week.

**Comment by ryan-keenan** [comment]
Basically I agree with you but this project is supposed to be rather lightweight and I feel like it already is getting somewhat heavy.  I would like to have the students fill out the notebook but I feel like it might be a lot to ask and really all they need to do is copy / paste from the lesson, so might as well provide them with the functions free of typos.  If people complain that it's too easy I'll reconsider but for now I mostly want them to focus on building up their pipeline using these functions for autonomous driving and mapping and then have the chance to extend their project to pickup samples as well.
