### ISSUE TITLE
Shreeyak P01E08: Var naming error

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#271]
In assignment, this function:
```
def pix_to_world(xpix, ypix, xpos, ypos, yaw, worldsize, scale):
```

the input parameter `worldsize` has a different name compared to the functions given as examples just above (`world_size`). Don't know if this is on purpose.

**Comment by ryan-keenan** [comment]
Thanks for catching this!  This was mistake that got propagated through to various places.  I think it's fixed everywhere now
