### ISSUE TITLE
Rover.worldmap has wrong channels specification on perception.py

### ISSUE THREAD

**Issue by thiagodefreitas** [udacity/robotics-beta-test-issues#273]
As:   

     # Example: Rover.worldmap[obstacle_y_world, obstacle_x_world, 0] += 1
        #          Rover.worldmap[rock_y_world, rock_x_world, 0] += 1
        #          Rover.worldmap[navigable_y_world, navigable_x_world, 0] += 1

should probably be:

     # Example: Rover.worldmap[obstacle_y_world, obstacle_x_world, 0] += 1
        #          Rover.worldmap[rock_y_world, rock_x_world, 1] += 1
        #          Rover.worldmap[navigable_y_world, navigable_x_world, 2] += 1

**Comment by ryan-keenan** [comment]
Great catch!  Just fixed this
