### ISSUE TITLE
Shreeyak P01E12: HTML video not playing

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#274]
The last cell of the projects jupyter cell outputs nothing for me. Can see an outline, but no video gets loaded.

**Comment by Shreeyak** [comment]
![html play blank](https://cloud.githubusercontent.com/assets/12800185/26037462/808fd60a-3910-11e7-8d24-3ad64af900a7.png)

**Comment by ryan-keenan** [comment]
Thanks for reporting this, I've seen similar behavior when looking at notebooks with a different tool called "nteract" but I'm not sure what causes it.  For now I've just added a comment to the notebook that says you might have to look at the saved video if the inline player doesn't work.
