### ISSUE TITLE
mikeUdacity Setting up Project 1

### ISSUE THREAD

**Issue by mikeudacity** [udacity/robotics-beta-test-issues#279]
https://classroom.udacity.com/nanodegrees/nd209-beta/parts/f491093d-8e67-4eab-8102-87bae095ca79/modules/0573f9ff-2e23-48cd-87d0-af24d758348a/lessons/ef841d31-8c53-49b3-8da3-a9d1523adef0/concepts/9ee96982-63f2-4425-8fa0-df842eb3a315

It would be helpful to tell the student where the project is. I didn't realize it was on this page until I started clicking multiple links:

Once you're comfortable using Git and GitHub, follow the instructions here to get setup with Python.

Should be something like:

Once you're comfortable using Git and GitHub, follow the instructions here to get setup with the first project here.

**Comment by ryan-keenan** [comment]
This is actually just the setup for Python, not the project per se.  Later in the lesson there is a link to a different repo for the project.
