### ISSUE TITLE
kylesf L5E02

### ISSUE THREAD

**Issue by kylesf** [udacity/robotics-beta-test-issues#281]
Make is clear that these are two separate scripts or include a double ampersand like so:
`cd ~/catkin_ws/src/simple_arm/ && mkdir scripts`

**Comment by kylesf** [comment]
At least I did not have any luck executing command like this. Do not want to create commits for each of the following instances if I am wrong

**Comment by bkinman** [comment]
This was a formatting issue, and should be fixed now. These should have been separate commands.
