### ISSUE TITLE
Vivek Yadav: Rover.near_sample is not set to true

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#283]
Hi,
I implemented code to spot for yellow samples, but when the rover went close to samples, the near_sample variable was not set to true in python file, but was set to true in simulator. Does this need to be fixed?

**Comment by vxy10** [comment]
vivek1108: Here is the image, https://drive.google.com/file/d/0B1fs4jieX9OOQTRQZjZxcm9JQ3c/view?usp=sharing

**Comment by ryan-keenan** [comment]
I was just trying this out today and when I'm near a sample I get back a 1 in data["near_sample"] from telemetry.  Are you still having this problem?  I've updated `RoverState()` now to have a `Rover.near_sample` field updated in `update_rover()` and it seems to work.

**Comment by vxy10** [comment]
No, i was looking at Rover.near_sample, not data['near_sample']. data['near_sample'] was 1
