### ISSUE TITLE
sagun L3-4 Consider removing "$" symbols in front of bash commands

### ISSUE THREAD

**Issue by sagunms** [udacity/robotics-beta-test-issues#284]
Just a recommendation. 

This is found all over Lesson 3 - 4. Lesson 5 seems properly formatted. 

It is implied, makes copy-pasting hard, $ symbol is used to refer to bash variables. 

Apparently, discouraged on popular sites like Server Fault.

**Comment by bkinman** [comment]
I've added the dollar sign everywhere.
