### ISSUE TITLE
sagun L05 Broken Links

### ISSUE THREAD

**Issue by sagunms** [udacity/robotics-beta-test-issues#285]
### Lecture 5.2

Three Broken links in the following paragraph:

> Note: If you have no longer have the catkin workspace from the previous lesson, you can download a copy of it **here**. Alternately, If you’d prefer to skip to the punch, you can download the entire, complete simple_arm package from **here**, or from **github**.

### Lecture 5.7

Broken link to [A gentle Introduction to ROS](https://cse.sc.edu/~jokane/agitr/)

> **Forbidden**
> 
> You don't have permission to access /~jokane/agitr/ on this server.
> 
> ---
> Apache/2.4.7 (Ubuntu) Server at cse.sc.edu Port 443

**Comment by bkinman** [comment]
What country are you located in?

**Comment by sagunms** [comment]
Australia. But never mind, all the broken links in this issue seem to be fixed now so you can close this issue.

**Comment by kylesf** [comment]
Links checked and working from US and international from VPN. Closing issue.
