### ISSUE TITLE
sagun P01 Document "pickup" command in course instructions and drive_rover.py

### ISSUE THREAD

**Issue by sagunms** [udacity/robotics-beta-test-issues#287]
Include function to send pickup command to the simulator as part of `drive_rover.py` script. 

I had to scrutinise the beta simulator source code to know how to do this.

```python
# Misc actions
def send_pickup():
    sample_data = {}
    sio.emit(
        "pickup",
        sample_data,
        skip_sid=True)
```

Also, include instruction about usage of the condition to know that a rock sample is nearby. Example:

```python
if Rover.near_sample:
  Rover.do_pickup = True
```

**Comment by ryan-keenan** [comment]
Good suggestion!  I've included this now in the [Requirements & Challenges](https://classroom.udacity.com/nanodegrees/nd209-beta/parts/f491093d-8e67-4eab-8102-87bae095ca79/modules/0573f9ff-2e23-48cd-87d0-af24d758348a/lessons/ef841d31-8c53-49b3-8da3-a9d1523adef0/concepts/ed33ab6f-2b67-4991-b372-ab915538b734) page and in the project code.
