### ISSUE TITLE
sagun L3-5 List of numerous typos throughout the lectures

### ISSUE THREAD

**Issue by sagunms** [udacity/robotics-beta-test-issues#292]
Sorry for being OCD but here is a long list of corrections to be made for Lectures 3-5. :)

### L3.3 Your Virtual Machine
So that everyone can **following** along in the same environment we're providing you with a virtual machine (VM) that is all setup with everything you need.
(CHANGE TO)
So that everyone can **follow** along in the same environment we're providing you with a virtual machine (VM) that is all setup with everything you need.

### L3.4 Automatically Configuring the Environment
~/.bash.rc file
(CHANGE TO)
~/.bashrc file

### L3.5 Launching Turtlesim Nodes

To do so, we will execute the rosrun command in a new terminal window, passing as parameters the name of the package we wish to run, and the **name of the name of the** actual node.
(CHANGE TO)
To do so, we will execute the rosrun command in a new terminal window, passing as parameters the name of the package we wish to run, and the **name of the** actual node.

Next, we will start the turtle_teleop_key node, also from **theturtlesim** package.
(CHANGE TO)
Next, we will start the turtle_teleop_key node, also from **the turtlesim** package.

By using the arrow keys in the turtle_teleop_key node’s console, **we are able to able** to move the turtle in turtlesim!
(CHANGE TO)
By using the arrow keys in the turtle_teleop_key node’s console, **we are able to** move the turtle in turtlesim!

### L4.4 Roslaunch

Now that you understand how to **created** a workspace, add a package, **built** and **launched** everything, 
(CHANGE TO)
Now that you understand how to **create** a workspace, add a package, **build** and **launch** everything, 

### L4.5 Rosdep

ROS packages have two different types of **dependencies, build dependencies**, and run dependencies.
(CHANGE TO)
ROS packages have two different types of **dependencies: build dependencies**, and run dependencies.

#### Joint angle command message topics should be formatted as a markdown table or an graphical representation:
```
|Topic Name | /simple_arm/joint_1_position_controller/command | | Message Type| std_msgs/Float64 | |Description | Commands joint 1 to move counter-clockwise, units in radians |
```

> Bash commands should span multiple lines. Examples:
* `cd ~/catkin_ws/src/simple_arm/` `mkdir scripts`
* `cd scripts` `echo ‘#!/bin/bash’ >> hello` `echo ‘echo Hello World’ >> hello`
* `chmod +x hello` `cd ~/catkin_ws` `catkin_make` `source devel/setup.bash` `rosrun simple_arm hello`
* `cd ~/catkin_ws` `cd scripts` `touch simple_mover` `chmod u+x simple_mover`

### L5.3

> Bash commands should span multiple lines

From the std_msgs package, we import Float64, which is one of the primitive message types in ROS. The std_msgs package also contains all of the other primitive types. Later on in this script, we will be publishing Float64 messages **to to** the position command topics for each joint.
(CHANGE TO)
From the std_msgs package, we import Float64, which is one of the primitive message types in ROS. The std_msgs package also contains all of the other primitive types. Later on in this script, we will be publishing Float64 messages **to** the position command topics for each joint.

The rate object is created here with a value of 10 **hertz**.
(CHANGE TO)
The rate object is created here with a value of 10 **Hertz**.

start_time is **used used** to determine how much time has elapsed
(CHANGE TO)
start_time is **used** to determine how much time has elapsed

### L5.4

> Bash commands should span multiple lines

Namely, we still need to cover: **Custom message generation Services Parameters Launch Files** In order to gain an understanding of the above, you will be writing another node called arm_mover.
(CHANGE TO)
Namely, we still need to cover: **Custom message generation Services, Parameters, Launch Files.** 
In order to gain an understanding of the above, you will be writing another node called arm_mover.

The find_package() macro should **looks** as follows.
(CHANGE TO)
The find_package() macro should **look** as follows.

As the names might imply, the std_msgs package contains all of the basic message types, and message_generation is required to generate message libraries for all **the the** supported languages (cpp, lisp, python, javascript).
(CHANGE TO)
As the names might imply, the std_msgs package contains all of the basic message types, and message_generation is required to generate message libraries for all **the** supported languages (cpp, lisp, python, javascript).

#### Modifying package.xml
**Now that the CMakeLists.txt file has been you are technically should technically be able to build the project.** 
(CHANGE TO)
**Now that the CMakeLists.txt file has been covered, you should technically be able to build the project.**

Let’s add the **message _generation** and message_runtime dependencies.
(CHANGE TO)
Let’s add the **message_generation** and message_runtime dependencies.

Let’s move onto the **core** for arm_mover.
(CHANGE TO)
Let’s move onto the **core** for arm_mover.

### L5.5

In general, you **should should** not use wait_for_message(). 
(CHANGE TO)
In general, you **should** not use `wait_for_message()`. 

### L5.6

Now that you’ve written the arm_mover node, the next step is to launch it, and then test it out by interacting with **the service the command line!**
(CHANGE TO)
Now that you’ve written the arm_mover node, the next step is to launch it, and then test it out by interacting with **the service via the command line!**

**To look at the point** the camera towards the numbered blocks on the countertop, we would need to rotate both joint 1 and joint 2 by approximately pi/2 radians. Let’s give it a **try**
(CHANGE TO)
**To point** the camera towards the numbered blocks on the countertop, we would need to rotate both joint 1 and joint 2 by approximately pi/2 radians. Let’s give it a **try.**

By **setting setting** the max_joint_2_angle on the parameter server, 
(CHANGE TO)
By **setting** the max_joint_2_angle on the parameter server, 

The service response is of type **GoToPositionResponse**
(CHANGE TO)
The service response is of type **GoToPositionResponse.**

**Comment by bkinman** [comment]
This was very thorough, you have a keen eye. Thanks!
