### ISSUE TITLE
VM: Suggestion: keyboard layout

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#300]
The default keyboard layout for the virtual machine is 'us'. This can be very annoying when working with a different layout (I always push every key until I find out where the '/' or the '-' is :D). Maybe providing some instructions to change this can be useful.

To change the keyboard layout, I've modified /etc/default/keyboard. In my case, I changed the XKBLAYOUT parameter from "en" to "es". After a reboot, the keyboard layout is changed.

Important: The password contains a hyphen. This can be hard to write with an incorrect keyboard layout. Modifying /etc/default/keyboard requires sudo, so I recommend to copy and paste the password.

**Comment by Shreeyak** [comment]
It would be nice to remove the hyphen from the password. If it need be more secure, then a longer phrase can be chosen. At boot up, one can't even type stuff to see what key prints what.

**Comment by kylesf** [comment]
All of this is taken care of in the new VM update. Will close this when new VM ships.

**Comment by kylesf** [comment]
This has been taken care of and you can find the updated VM in the classroom! Thanks for the help!
