### ISSUE TITLE
L03E05 - Video wrong/incomplete command

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#301]
The video explains how to launch the turtlesim node. The correct command to launch it is 'rosrun turtlesim turtlesim_node', but the video shows 'rosun turtlesim', which is incorrect. After that, the video changes and the correct command appears. 
This can be a little bit confusing if you don't know how rosrun works, and I think it should be fixed.

This is the link to the moment of the video where the wrong command is shown: https://youtu.be/nwPyzWfN5QE?t=55

**Comment by bkinman** [comment]
Good catch! We've fixed this in the latest edit (it may not show up in the beta classroom for a bit).
