### ISSUE TITLE
L03 general comment about ROS and tools

### ISSUE THREAD

**Issue by thiagodefreitas** [udacity/robotics-beta-test-issues#305]
During the ROS lesson, I think it could have cited(at least talked briefly) more about some of the tools for visualization/Debugging in general, i.e: rqt_graph, rqt_plot, rqt_bag, rviz, rqt_console, rosbag recording.

**Comment by bkinman** [comment]
I elected only to teach the students that which I considered to be "essential" to using ROS.

We may be able to update ROS Essentials later on to include this stuff, depending on how quickly students move through the material... But currently, the students only have 1 week, or ~10 hours to get through the material.

We _do_ intend to introduce students to these tools though as the course progresses.

I appreciate this type of feedback, keep it coming!
