### ISSUE TITLE
L04E02 catkin tools

### ISSUE THREAD

**Issue by thiagodefreitas** [udacity/robotics-beta-test-issues#306]
Wouldn't it be worthy to at least mention alternatives to catkin_make: http://catkin-tools.readthedocs.io/en/latest/index.html# ?

**Comment by bkinman** [comment]
I'm not sure I understand what you mean?

Do you mean mentioning other build systems, like make, cmake and scons?

**Comment by bkinman** [comment]
I think that mentioning catkin tools at this point would only add more noise to the conversation.

I actually didn't know anything about catkin tools before you linked me to that.
It solves a number of nagging little problems with catkin_make... Cool!
