### ISSUE TITLE
L04E04 - roslaunch runs master process

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#308]
In the previous lessons, it was stated that ```roscore``` is used to bring up the master process, and the master process is needed to run any other node. Here, the student is asked to run nodes with ```roslaunch``` without running the master process first. This can be confusing.
I think it can be explained in this lesson that the ```roslaunch``` command brings up the master process if it is not already running.

**Comment by bkinman** [comment]
That's a good point. I'm going to go ahead and leave this open until I update the script.

**Comment by bkinman** [comment]
I've updated the classroom text to make this a little bit more clear.
