### ISSUE TITLE
L04E03 - First build of the package does not fail

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#309]
The package build does not fail when ```controller_manager``` is not installed. This is because is not set as a build depend in the package.xml file. If you add the line ```<build_depend>controller_manager</build_depend>``` and try to build the package without installing ```ros-kinetic-controller-manager```, it will fail as said in the lesson.

**Comment by bkinman** [comment]
I just fixed a bug that would have caused the build to not fail. <- Haha, who guessed I'd get to say that.

It's actually not supposed to be `package.xml` that's causing the build to fail, but rather the required_component controller_manager in simple_arm's `CMakeLists.txt`.

There are currently 3 github repos containing some version of simple_arm; and not all of them had the update to `CMakeLists.txt`. If you do a `git pull` on the `simple_arm` package you have, and then `apt-get remove controller_manager`, and then build again, it should now fail.

If this isn't the case, feel free to reopen this issue or re-report.
