### ISSUE TITLE
Graphic inconsistent with instructor explanation

### ISSUE THREAD

**Issue by swwelch** [udacity/robotics-beta-test-issues#328]
In this video, at the 1:00 minute mark, the instructor says messages are sent from the camera node to the behavior executor node, but the image shows them going to to the position estimator:
https://classroom.udacity.com/nanodegrees/nd209-beta/parts/f491093d-8e67-4eab-8102-87bae095ca79/modules/2919466f-aa2b-4424-b86a-98b0a53ce335/lessons/2cd33882-d29e-43e8-9ff7-10398c8b5351/concepts/c26f0ceb-2419-46bd-926f-9a8c361f21b1

**Comment by bkinman** [comment]
This should be fixed in the next edit of the video. Good catch!
