### ISSUE TITLE
Voice cut off at end of video

### ISSUE THREAD

**Issue by swwelch** [udacity/robotics-beta-test-issues#329]
The instructors voice is cut off at the end of this video: https://classroom.udacity.com/nanodegrees/nd209-beta/parts/f491093d-8e67-4eab-8102-87bae095ca79/modules/2919466f-aa2b-4424-b86a-98b0a53ce335/lessons/2cd33882-d29e-43e8-9ff7-10398c8b5351/concepts/e1ddddec-7214-4495-8878-1030aa32fab0

**Comment by bkinman** [comment]
This is something I've also witnessed. This should be resolved in the final edit of the video.
