### ISSUE TITLE
Pick and place - Repo readme issues

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#333]
`To run projects from this repository you need version 7.6.0 If your gazebo version is not 7.6.0, perform the update as follows:`

When you perform the update, gazebo version is 7.7.0, not 7.6.0.

`For the rest of this setup, ros_ws is the name of active ROS Workspace, if your workspace name is different, change the commands accordingly`

But in the next line, the following command appears:
`export GAZEBO_MODEL_PATH=~/RoboticsScratch/src/kinematics_project/kuka_arm/models`
This should be changed to:
`export GAZEBO_MODEL_PATH=~/ros_ws/src/kinematics_project/kuka_arm/models`

**Comment by hvpandya** [comment]
Resolved, thanks
