### ISSUE TITLE
arek: gazebo crashing intermittently

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#334]
[ERROR] [1494968867.474688179, 261.578000000]: Could not load controller 'joint_1_position_controller' because controller type 'effort_controllers/JointPositionController' does not exist.
[ERROR] [1494968867.474729552, 261.578000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [1494968868.475286, 262.581000]: Failed to load joint_1_position_controller
[INFO] [1494968868.475775, 262.581000]: Loading controller: joint_2_position_controller
[ERROR] [1494968868.478115078, 262.583000000]: Could not load controller 'joint_2_position_controller' because controller type 'effort_controllers/JointPositionController' does not exist.
[ERROR] [1494968868.478147726, 262.583000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [1494968869.479209, 263.570000]: Failed to load joint_2_position_controller
[INFO] [1494968869.479699, 263.570000]: Controller Spawner: Loaded controllers: joint_state_controller
[INFO] [1494968869.484653, 263.574000]: Started controllers: joint_state_controller
gzclient: /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/include/OgreAxisAlignedBox.h:252: void Ogre::AxisAlignedBox::setExtents(const Ogre::Vector3&, const Ogre::Vector3&): Assertion `(min.x <= max.x && min.y <= max.y && min.z <= max.z) && "The minimum corner of the box must be less than or equal to maximum corner"' failed.
Aborted (core dumped)
[gazebo_gui-6] process has died [pid 2066, exit code 134, cmd /opt/ros/kinetic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/home/robo/.ros/log/b328ac24-3a7b-11e7-bcf8-000c29981ea9/gazebo_gui-6.log].
log file: /home/robo/.ros/log/b328ac24-3a7b-11e7-bcf8-000c29981ea9/gazebo_gui-6*.log

**Comment by 867sec** [comment]
![screen shot 2017-05-16 at 17 08 39](https://cloud.githubusercontent.com/assets/28066540/26128590/e6e3736c-3a5a-11e7-994d-dc53bbfad753.png)

**Comment by 867sec** [comment]
![screen shot 2017-05-16 at 17 19 43](https://cloud.githubusercontent.com/assets/28066540/26128865/e2f698be-3a5b-11e7-9204-0c0939de36d2.png)

**Comment by hvpandya** [comment]
Did you perform a rosdep install?

Your setup appears to be missing effort_controllers. Please try the following:
```
$ cd ~ros_ws
$ rosdep install --from-paths src --ignore-src --rosdistro=kinetic -y
```

**Comment by 867sec** [comment]
Yes you are right!
After your suggestions and per instructions I used rosdep install -i
simple_arm
and it installed effort_controllers.
Then I run your

rosdep install --from-paths src --ignore-src --rosdistro=kinetic -y

and got the following message:

#All required rosdeps installed successfully

so everything works now! Thanks!
