### ISSUE TITLE
ROS-install in VMWare in linux

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#339]
if one wants to use vmware in linux, you need to use 'unzip' from terminal to extract the files. I did without them, and kept getting error. Also, once we click power on ubuntu64, an error comes saying some vmdk file not found. Then you need to browse and select the file. it will be nice to include this, in case someone wants to use vmware on linux.

**Comment by vxy10** [comment]
vivek1108

**Comment by bkinman** [comment]
Currently we do no have plans to provide explicit support to students running Linux, so I'm going to go ahead and close this.

(I've seen this too, on my machine)
