### ISSUE TITLE
vivek1108: (L3-5) turtle_teleop_key terminal to be selected

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#340]
Will be nice to include in part 5 of lesson 3 that the terminal with turtle_teleop_key must be selected, not the simulator. Students new to ROS may miss this.

**Comment by bkinman** [comment]
I've updated the wording to be somewhat more explicit. It now says:

> By using the arrow keys with the turtle_teleop_key node’s console selected, we are able to able to move the turtle in turtlesim!

Before, it said:

> By use the arrow keys in the turtle_teleop_key node's console, we are able to move the turtle in turtlesim

If students are still having problems with it, even after this change, I will probably have to include a special note or caveat call out.

Hopefully the video the screencast I've just recently added helps to clear this up.

Thanks.
