### ISSUE TITLE
vivek1108: L4p1 catkin

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#342]
in definitation of catkin, the catkin itslef it used. it will be nice to define the terms, and may be a graphical lay out of nodes/topics in turtlesim

**Comment by bkinman** [comment]
Thanks for the feedback Vivek!

The updated script and associated head shot now contain a discussion of the term catkin, and where it comes from.

In terms of the graphical layout of nodes/topics in turtlesim, I think that's a good idea. I'll go ahead and create a separate issue for this.
