### ISSUE TITLE
vivek1108: including links to resources

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#343]
it will be nice to include links on how to get more information on ROS topics, etc. For example, catkin, http://wiki.ros.org/catkin/conceptual_overview

**Comment by bkinman** [comment]
Hello Vivek,
Can you provide some particular examples of where you'd like to see some more links?

I've provided links to the ROS wiki here and there throughout the material, and also discuss where to get help at the end.

The link that you've mentioned above has already been included in the "Creating a Workspace" concept.

Are you saying that you'd like more links like that one? 

Thanks,
Brandon

**Comment by bkinman** [comment]
As I've received no response here, I'm going to go ahead and close this issue.
