### ISSUE TITLE
vivek1108: catkin_package

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#344]
catkin_make failed for me, and the error was catkin_package was not installed. I used  pip install catkin_pkg, and this fixed the error. This ofcourse is not an issue if VMdisk is used.

**Comment by bkinman** [comment]
Hello Vivek,
Closing this issue, as we won't be explicitly supporting coursework outside of the VM.
Is there any technical reason why you've elected not to use the VM?
You may have mentioned this in another issue, perhaps I've not seen it.
