### ISSUE TITLE
arek: L5P3 it says at the bottom that there is video but no vide only screenshot

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#345]
arek: L5P3 it says at the bottom that there is video but no vide only screenshot

**Comment by bkinman** [comment]
I don't see any screenshots, or mention of screenshots in L5P3. Are you able to provide more context?

**Comment by 867sec** [comment]
Yes I can provide context. Please find below a screenshot of L5 P3 at the bottom saying: "Below is a video..." but instead of a video there is a screenshot.

**Comment by 867sec** [comment]
![capture](https://cloud.githubusercontent.com/assets/28066540/26177915/b86fbf5c-3b29-11e7-80b2-f3b3cb3f66b9.PNG)

**Comment by 867sec** [comment]
Please let me know if you need more info!

**Comment by bkinman** [comment]
Thanks! It's a video now! ;)
