### ISSUE TITLE
vivek1108: install error with catkin_make after getting simple_arm

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#347]
in case someone gets an error, the error says no module name em. using pip install empy (not em) will fix this issue

**Comment by bkinman** [comment]
Need more information.
catkin_make should not be installing anything?

Has anybody else had this problem?
Do you have the specific error output?

**Comment by vxy10** [comment]
not sure, i got this error while installing ROS from scratch on my host machine. The VM didnt have this issue.

**Comment by bkinman** [comment]
Interesting!
I'm going to go ahead and close this issue, as we will not be explicitly supporting users installing ROS.
