### ISSUE TITLE
letyrodri P1 important ?

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#351]
In notebook, there is an error when you are recording the video. Process_images is called 1 time more. The robot_log.csv has a header row, it seems not to be taken into account. So, some of us have an if to avoid looping the last time.

**Comment by ryan-keenan** [comment]
Thanks for reporting this!  This seems to be something strange with `moviepy`.  We're passing in `data.images` as the list of images to process and it doesn't contain the header line, so `clip` knows nothing about the header.  It seems like `clip.fl_image()` runs through the code once before starting to process the images, thereby incrementing `data.count` by +1 before starting or something like that.  I am providing a hacky fix to this now but setting `data.count = -1`, but if you figure out what's going on here let me know!
