### ISSUE TITLE
Simulator Graphics Quality

### ISSUE THREAD

**Issue by rohts-patil** [udacity/robotics-beta-test-issues#357]
There should be a note for students such that 
 while submitting the project they should mention what graphics settings did they use. Many of us are finding that under different graphics setting, the result might be different.

**Comment by ryan-keenan** [comment]
This is a great point!  I hadn't noticed this yet but makes sense.  I now added a note to the project description page in the classroom as well as to the README and writeup_template to make a note of simulator graphics settings in your writeup when submitting the project.
