### ISSUE TITLE
VM FAQ: qiang ROS Essentials L02E03

### ISSUE THREAD

**Issue by luqiang21** [udacity/robotics-beta-test-issues#366]
I can't paste the git clone command in the robo-nd virtual machine. I am using Mac.

**Comment by bkinman** [comment]
Are you running VMWare under OSX?

**Comment by luqiang21** [comment]
@bkinman Yes. I found another way, just opened udacity webpage inside the VMware.

**Comment by bkinman** [comment]
This is an issue that I've run into multiple times over the years when using VMs. It usually has something to do with the drivers you've installed in the host machine, or the lack of the guest drivers in the virtual machine.

I'm going to go ahead and leave this open for now; It's an issue that should be mentioned in our VM faq document, which has not yet been created.

**Comment by luqiang21** [comment]
Update: I used the latest vmdk, and was able to copy and paste between Mac and the robo-nd VM.

**Comment by bkinman** [comment]
Excellent! Good to hear! still going to leave this open to we know to make a FAQ entry!

**Comment by kylesf** [comment]
@bkinman What are your thoughts for this FAQ?

**Comment by sahiljuneja** [comment]
@kylesf I'm working on one currently. Will be sharing it with beta testers to add more to it soon.

**Comment by kylesf** [comment]
Awesome, I will assign this to you then.
