### ISSUE TITLE
P2 - Robotic arm - Pick & Place project - Missing shelf and dropbox in Gazebo

### ISSUE THREAD

**Issue by diyjac** [udacity/robotics-beta-test-issues#367]
Once the Gazebo and rviz are up and running in demo, I do not see the shelf in front of the robot or dropbox to its right, so I am reporting it as requested in the README.md project file.  There is a cube in front of the robot instead with the blue cylindrical target on the floor instead of the missing shelf or the cube.

![robond-p2-demo](https://cloud.githubusercontent.com/assets/22384435/26284807/852ff478-3e11-11e7-99bd-fe5a9401df5a.png)

**Comment by hvpandya** [comment]
Your env variable pertaining to gazebo is not set properly. 

You need to modify following line from README as it applies to your directory structure:
```
export GAZEBO_MODEL_PATH=~/ros_ws/src/kinematics_project/kuka_arm/models
```

**Comment by diyjac** [comment]
Hi @hvpandya!

It appears that was the problem.  I am able to see the self and the dropbox now.

Cheers!

![robond-p2-demo-take2](https://cloud.githubusercontent.com/assets/22384435/26288267/243bfb26-3e5c-11e7-86d8-1ad8b8af6c1e.png)
