### ISSUE TITLE
3 . generalized coordinates

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#369]
what are the three parameters required to locate p2 from p1 ?

i am confused whether you are trying to convey that any pair of three variables can be used to estimate the position i.e (x1,y1,L),(x1,y1,angle),(x1,L,angle) ...

if we take (x1,y1,L) , we can see that the next point lies in the circumference of the circle drawn with x1,y1 as center and L as radies . but , it will not give me a precise point 

same thing apply for (x1,y1,angel ). this is going to give a straight line on which we can find the next point . not a precised location is found yet 

(x1,y1,L,angle  ) is the one which can give us a precise location 

if i am wrong , please correct me and add a clear explanation on the notes 
thanks

**Comment by thomas-at-em** [comment]
The points I am trying to make are: 
(1) there is no unique choice of variables used to describe the configuration of a system. Choices include distances, angles, combinations of distances and angles, etc - hence the name "generalized coordinate" 
(2) generalized coordinates are variables, that is, they have the potential to change as a function of time. L is constant therefore it is not a potential choice for a generalized coordinate.  
(3) one thing we want to know is how many generalized coordinates does it take to completely describe the configuration of a system. For a rigid body confined to move on a plane, it takes exactly 3. Which three? Well, there is not a unique set that would work. One obvious set is the (x,y) coordinates of one particle and the angle of the rod with respect to the x-axis as another generalized coordinate.
