### ISSUE TITLE
3 . joint type and degree of freedom

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#370]
it will be easy if you can reorganize the order in the picture which explains lower and higher order joints

revolute
prismatic
screw
cylindrical
planar
spherical

this will be easy for the reader to start from the simple form of joint and go to higher orders. the current image starts with the higher order in left . so the student will have a hard time in trying to understand spherical joint first and go on to the next one

**Comment by thomas-at-em** [comment]
Good suggestion. I will communicate this to our team of animators/illustrators.
