### ISSUE TITLE
L06E04 - Principal Types of Serial Manipulators - Pictures or diagrams requested

### ISSUE THREAD

**Issue by diyjac** [udacity/robotics-beta-test-issues#371]
In `Principal Types of Serial Manipulators`, the video is currently not available, so I cannot visualize the types of serial manipulator being describe.  In particular, I am having problem figuring out what is the difference between joint axes being in parallel and not.

**Comment by thomas-at-em** [comment]
This is another case of not having material back from illustrators/animators. But you are correct, this is exactly my intention.

**Comment by kylesf** [comment]
There are now visualizations added to the classroom!
