### ISSUE TITLE
L06E08 and L06E09 - Rotation Matrices in 2D and Rotation Matrices in 3D.  Suggestion: Animated gifs

### ISSUE THREAD

**Issue by diyjac** [udacity/robotics-beta-test-issues#374]
I found the mathematics to be pretty dried here and many students will be lost.  I suggest maybe breaking up the formula presentations with animated gifs that shows what the rotation transform looks like in transition to hopeful make the lesson more clear.

**Comment by thomas-at-em** [comment]
Thanks for the feedback! That is precisely the idea. My storyboards have been sent to animators/illustrators but have not come back yet.

**Comment by kylesf** [comment]
@diyjac Do you find the updated content satisfactory now?
