### ISSUE TITLE
arek - Introduction to ROS - 11. Turtlesim Comms: List Nodes = "screencast missing"

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#377]
arek - Introduction to ROS - 11. Turtlesim Comms: List Nodes - "screencast missing" bove the first video

**Comment by 867sec** [comment]
![screen shot 2017-05-22 at 13 53 48](https://cloud.githubusercontent.com/assets/28066540/26321788/43122882-3ef6-11e7-837e-b6610003e046.png)

**Comment by bkinman** [comment]
Fixed!
