### ISSUE TITLE
L02E05 - Essential Elements of Robots

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#378]
1. What do the colours represent? Are they just there to confuse the user?

2. "mecanum wheels" is the only item that isn't capitalized. Consider capitalizing.

3. Flow meter seems like an odd example of a touch sensor. Maybe a pressure pad would be more intuitive?

**Comment by bkinman** [comment]
1. The colors are arbitrary, the system chooses them, they are not currently configurable in our content editor.

2. Fixed!

3. Agreed, fixed!
