### ISSUE TITLE
Intro to ROS: L01E04 Nodes and Topics

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#379]
Doubt it's a big deal really, but these two images don't match up.

http://resume.jchernus.com/ros.png

(avoiding imgur due to NDA, will delete image as soon as ticket marked 'done')

**Comment by jchernus** [comment]
Edit: Added 3rd image from L01E05 as well.

**Comment by bkinman** [comment]
Excellent catch! I've put a comment in the video, so it should make it into the next round of edits.
