### ISSUE TITLE
letyrodri L03E02 Hello world quotes

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#380]
Small issue, in lesson the quotes(') are ascents.(`). 

If you copy/paste doesn't work. Also, students could be confuse . 

$ echo ‘#!/bin/bash’ >> hello
$ echo ‘echo Hello World’ >> hello

**Comment by bkinman** [comment]
Oooh. They started life as ', rather than ‘, but copy-and-pasting from the script document messed things up. Great catch! I've fixed it.
