### ISSUE TITLE
letyrodri L03E04 Simple Mover: The Code commands errors in class

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#381]
In Running simple_mover section, it says:
$ cd ~/catkin_ws
$ cd roslaunch simple_arm robot_spawn.launch

There is an extra "cd". Should it be:

$ cd ~/catkin_ws
$ roslaunch simple_arm robot_spawn.launch

?

**Comment by bkinman** [comment]
Oops! Fixed!

**Comment by letyrodridc** [comment]
I'm not sure if there was an extra cd or a missing cd... Do we have to be in simple_arm folder?

**Comment by hvpandya** [comment]
> I'm not sure if there was an extra cd or a missing cd... Do we have to be in simple_arm folder?

@letyrodridc roslaunch does not care where you are as long as your env variables are sourced properly
