### ISSUE TITLE
letyrodri L03E03 Error in command line folder in Creating the empty simple_mover node script

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#382]
In section, Creating the empty simple_mover node script, it says:

$ cd ~/catkin_ws
$ cd scripts
$ touch simple_mover
$ chmod u+x simple_mover

But the "scripts" folder shouldn't be inside catkin_ws. It should be inside simple_arm

**Comment by bkinman** [comment]
You are correct! It has been fixed.
