### ISSUE TITLE
VM: ROS Essentials - L02E05 Rosdep

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#383]
Using: VM

`rosdep check simple_arm` comes up with 3 missing dependencies. Video only shows 1. 

Not a big problem, since `rosdep install -i simple_arm` installs all 3 missing packages, but students might be confused/worried.

apt	ros-kinetic-gazebo-ros-control
apt	ros-kinetic-joint-state-controller
apt	ros-kinetic-effort-controllers

**Comment by bkinman** [comment]
Hrmm. This is a good point. I'll create an issue to update this in the VM.

**Comment by bkinman** [comment]
Actually, I'll just reopen this one, and give this the VM label.

**Comment by jchernus** [comment]
Warning: I wasn't using today's VM. This might have been fixed in the latest one.

**Comment by bkinman** [comment]
Note to whoever makes this VM change: to make the latest VM  (5/22) agree with the lecture, install `ros-kinetic-effort-controllers`

**Comment by kylesf** [comment]
Okay, checked and fixed. Will be in the new VM. Will put in progress until a new successfully VM is released.

**Comment by kylesf** [comment]
This has been taken care of and you can find the updated VM in the classroom! Thanks for the help!
