### ISSUE TITLE
composition of homogeneous transform

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#388]
equation 2 

Ar(p/B0) = (AB)T B r(p/B0)

if i am not wrong , this equation is intended to show the point p transformed from B frame to A frame . so the left hand side of this equation should be 

Ar(p/A0)  (ie)replacing B0 with A0 because we have to find the point p with respected to the center of frame A (A0)

correct me if i am wrong

**Comment by thomas-at-em** [comment]
Ahh, the dangers of copy-paste. You are correct, equation (2) is wrong. Thanks for point it out.

**Comment by yuvaramsingh94** [comment]
check equation 3 also .. the same problem
