### ISSUE TITLE
Introduction to Kinematics - Rotations in Simpy - Sympy installation

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#389]
I think it can be useful to explain a way to install sympy. For example, `pip install sympy` can be used to perform the installation.

**Comment by hvpandya** [comment]
While the new VM image comes pre-installed with sympy, I agree that adding this simple instruction will help people not using the VM. Tagging @thomas-at-em for fixing this.

**Comment by thomas-at-em** [comment]
Fixed.
