### ISSUE TITLE
ROS Essentials: L03E04 Arm Mover

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#392]
At the bottom, under **Creating the empty arm_mover node script**

Shouldn't,

`cd ~/catkin_ws`

Be 

`cd ~/catkin_ws/src/simple_arm`

since that's where the scripts folder resides.

**Comment by bkinman** [comment]
Oops! Fixed! Good catch.

**Comment by luqiang21** [comment]
@bkinman Is it fixed in the lesson? I can't see the correct one in the lesson.
