### ISSUE TITLE
ROS Essentials - Lesson 3

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#396]
### Problem:

If someone is brand new to ROS, I believe that they might feel overwhelmed about all of the different things they did in the last 3 lessons. 

It's very resourceful to have included links to ROS documentation, but it can make newbies feel even more lost in all of the information. 

### Solution:

Recaps are great.

**Existing recap video:** Mostly talks about where you can find more information about ROS. I feel as though this can be communicated well with text alone (which I actually only _just_ noticed, since Udacity auto-loaded Kinematics as soon as the video completed).

**Julia's ideal recap video:** Recap what we accomplished in this section and list the most important tools or concepts we used.

Ex. "**Topics** are subscribed to, and used for ..." 
"**Services** are a request/response... "
"**Actions** are to be used when the response might not come immediately or when ... "

This will help students gauge how much of the last lesson they need to understand well and be able to use _vs._ simply be aware of (and be able to reference when needed).

This would be going along with the "Tell them what you're going to teach them, teach them, tell them what you've taught them" philosophy.

**Comment by bkinman** [comment]
This makes a lot of sense.

I'm not sure that we will have a chance to re-record the recap videos for this cohort... But what we could do is give students quizzes that would allow them to recap.

Also, our recap could be a little bit more thorough, to "tell them what you've taught them".

I'm going to leave this open until we've added some better recap and quizzes.
