### ISSUE TITLE
Kinematics - L01E07

### ISSUE THREAD

**Issue by kylesf** [udacity/robotics-beta-test-issues#397]
Near the bottom it says `You can see this most easily by comparing the y-values and noticing that the blue frame has a larger y-value.` shouldn't it be `You can see this most easily by comparing the x-values and noticing that the blue frame has a larger x-value.`

**Comment by thomas-at-em** [comment]
Good catch. Yes, what I mean to say is the blue frame has a smaller y-value. Fixed it.
