### ISSUE TITLE
Redundancy (Vivek1108)

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#401]
Some discussion on redundancy must be included, and methods to resolve them. So students are aware of issues.

**Comment by thomas-at-em** [comment]
I am afraid I don't understand your comment. I do (briefly) discuss the concept of kinematic redundancy near the end of lesson 3 - Joint Types and Degrees of Freedom. Feel free to re-open this issue if this section doesn't address your concern.
