### ISSUE TITLE
Kinematics - L01E11 [Typo]

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#404]
You have seen how to construct rotation matrices by hand, I will now show you how to do this in code with a Python package called SymPy. SymPy is a full-featured computer algebra system (CAS) that will enable you to construct and **manipulator** matrices symbolically and then numerically evaluate them when needed.

manipulator -> manipulate?

**Comment by jchernus** [comment]
Another: 

With rotations most **function** expect angles to be input as radians, but for most people units of degrees **is** more intuitive. Defining reusable conversion factors is generally a good idea.

function -> functions
is -> are?

Consider: 

For rotations, most functions will expect angles to be input as radians. However, most people find units of degrees to be more intuitive. Defining reusable conversion factors is often a good idea.

**Comment by thomas-at-em** [comment]
Good catch, thanks. If possible, please include the lesson name in your feedback because it makes it easier for me to find the problem. Keep up the good work!

**Comment by jchernus** [comment]
Sorry, will do!
