### ISSUE TITLE
VM: set EDITOR to nano, make sure nano is installed

### ISSUE THREAD

**Issue by bkinman** [udacity/robotics-beta-test-issues#406]
Vim is not the best choice of default editor. Also, vim is not currently installed on the virtual machine.
Let's make sure nano is installed, and that it is the default EDITOR.

**Comment by hvpandya** [comment]
I can confirm that nano is already installed in the VM but not set to default editor.

**Comment by Shreeyak** [comment]
What about gedit?

**Comment by kylesf** [comment]
Done, moving to in progress until new successful VM is released.

**Comment by kylesf** [comment]
This has been taken care of and you can find the updated VM in the classroom! Thanks for the help!
