### ISSUE TITLE
Kinematics: Composition of rotations - Coding quiz errors

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#408]
The second coding quiz [here](https://classroom.udacity.com/nanodegrees/nd209-beta/parts/72800973-80cd-4828-81fd-b3390486892b/modules/8855de3f-2897-46c3-a805-628b5ecf045b/lessons/87c52cd9-09ba-4414-bc30-24ae18277d24/concepts/56fa32b9-4a39-4367-8fcc-c520a65426ef) is not working. When you submit the answer, an error pops up: `No module named 'rotation_template'`.

In addition, the comments in lines 9 and 10 of the same quiz are copied from the first one and should be changed. The text now is:
`Create a symbolic matrix representing an intrinsic sequence of rotations about the Y and then Z axes.`
It should be:
`Create a symbolic matrix representing an extrinsic sequence of rotations about the Z and then Y axes.`

**Comment by thomas-at-em** [comment]
Great! Thanks very much. In addition to bugs, typos, and such, I would be very interested to hear your thoughts on the bigger picture issues: clarity, tone, logical flow, etc. Keep up the great work!
