### ISSUE TITLE
Intro to Kinematics - Joint space definition

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#409]
Didactic issue: I didn't understand the meaning of joint space. The definition is not in the introduction, but it talks about it. Someone with not background in robotics could feel confuse. The definition is in next lesson.

**Comment by kylesf** [comment]
Can you point to where you think the definition should go?  What Lesson/Exercise?

**Comment by letyrodridc** [comment]
Thanks: "In the robotics of serial manipulators, you'll often run into the term "configuration space" or "joint space", which refers to the set of all possible configurations a manipulator may have. "
