### ISSUE TITLE
Joint Types & Degrees of Freedom (DoF) - Can't see image text

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#410]
The joints image has some small text along the joint. If I click the image, I can't read the text. 

But I can see all the text up, left, right and under the joints.

**Comment by thomas-at-em** [comment]
Thanks for the feedback. All the images right now are placeholders. I am waiting to get materials from professional animators/illustrators so I can add it to the classroom.

**Comment by thomas-at-em** [comment]
In addition to bugs, typos, and such, I would be very interested to hear your thoughts on the bigger picture issues: clarity, tone, logical flow, etc. Keep up the great work!
