### ISSUE TITLE
Essential Elements of Robotics - Quiz is not working

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#411]
The quiz [here](https://classroom.udacity.com/nanodegrees/nd209-beta/parts/f491093d-8e67-4eab-8102-87bae095ca79/modules/0573f9ff-2e23-48cd-87d0-af24d758348a/lessons/274b5065-eac5-4405-a09e-83c71e62a2fe/concepts/f3ce75bf-c501-4a4c-bf21-a490762ee178) is not working. The submit button does not launch any dialogue box to tell the student if the answer is correct or wrong. In addition, I think that the option `IMU` was here before, but it doesn't appear anymore.

**Comment by ryan-keenan** [comment]
thanks for reporting this!  It is fixed now
