### ISSUE TITLE
P1 - lesson Warp, Threshold, & Map

### ISSUE THREAD

**Issue by Mohammed-Tag-ElAsfia** [udacity/robotics-beta-test-issues#412]
in the image illustrating the rover ordinates, the x and y should be swapped

the image link:

https://d17h27t6h515a5.cloudfront.net/topher/2017/May/5921f4f6_screen-shot-2017-05-21-at-1.12.06-pm/screen-shot-2017-05-21-at-1.12.06-pm.png

the lesson link 

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/f491093d-8e67-4eab-8102-87bae095ca79/modules/0573f9ff-2e23-48cd-87d0-af24d758348a/lessons/ef841d31-8c53-49b3-8da3-a9d1523adef0/concepts/19027920-cc3a-43a3-9328-fd71f215e48e

P.S.
in the next lesson similar image is used

**Comment by ryan-keenan** [comment]
Thanks for reporting but actually these are the correct axis labels.  The direction of rover travel should be x and y to rover's left.  This way when the rover is at (0, 0) in world coordinates and at a yaw=0 the world axes line up with rover axes.
