### ISSUE TITLE
P1 - lesson : Map to World Coordinates

### ISSUE THREAD

**Issue by Mohammed-Tag-ElAsfia** [udacity/robotics-beta-test-issues#413]
the quiz of this lesson and it's solution.py still use the old approach, it doesn't use the rotate_pix and translate_pix functions

lesson link:

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/f491093d-8e67-4eab-8102-87bae095ca79/modules/0573f9ff-2e23-48cd-87d0-af24d758348a/lessons/ef841d31-8c53-49b3-8da3-a9d1523adef0/concepts/e4a704e8-9490-4aff-b478-85e3f29fd4b5

**Comment by ryan-keenan** [comment]
thanks for reporting this! should be fixed now but you might have to refresh the page and hit "Reset" on the quiz.
