### ISSUE TITLE
arek Packages & Catkin Workspaces -> 3. Add a Package

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#414]
arek Packages & Catkin Workspaces -> 3. Add a Package
Upon finishing watching the video it shoul NOT automatically advance to part 4. Roslaunch because there are commands to execute below the video in part 3. The content under video in part 3 disappears when the video in part 3 automatically switches to part 4 so the automatic switching to the next part should be disabled here.

**Comment by bkinman** [comment]
I've heard this one a couple of times.
@ryan-keenan , do you know if this is something that can be fixed on the site?

**Comment by kylesf** [comment]
Fixed for Add a Package and Rosdep! Thanks for reporting!
