### ISSUE TITLE
arek - Write ROS Nodes - 3. Simple Mover: The Code

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#417]
arek - Write ROS Nodes - 3. Simple Mover: The Code
Right above the video please replace the line: `rosrun simple_arm simple_mover` with the following:
"Now open a new terminal window because in your current window you are running the master process. Then source your setup.bash like this: `source devel/setup.bash` then change the directory to here: `cd ~/catkin_ws` then run this: `rosrun simple_arm simple_mover`

**Comment by kylesf** [comment]
Looks like this has been addressed in the classroom. Furthermore, you would want do change to your catkin_ws before sourcing devel/setup.bash.
