### ISSUE TITLE
arek - Write ROS Nodes - 6. Arm Mover: Launch and Interact

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#420]
arek - Write ROS Nodes - 6. Arm Mover: Launch and Interact
In the section titled: "Testing the new service" we need to remind the student to do `catkin_make` and also remind them that whenever they start a new terminal the have to do `~/catkin_ws$ source devel/setup.bash`

Next, if we are aking them to run `rosnode list` and `rosservice list` then we need to provide the results so they can verify that the `arm_mover` node is indeed running.

**Comment by bkinman** [comment]
Thanks Arek! I've updated the instructions in to include the directive to make and source the workspace!
I've also modified the text informing students what to look for in the `rosnode list` and `rosservice list` console commands.

I didn't provide them with a screenshot though, as the `rosservice` list output is quite long.
