### ISSUE TITLE
Vivek 1108: DH parameter, intersecting axes

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#425]
When Z-axes are intersecting, we need to take x as the normal to planes of z_{i_1} and z_i, and origin as o_{i-1} (previous link's origin). the second part was not covered.

**Comment by thomas-at-em** [comment]
I don't really understand your comment here. In the modified DH parameter that I teach, the origin of frame i is always the intersection of Xi with Zi, which is described in the text:
"X_i represents a unit vector that is mutually perpendicular (or "normal") to both Z_{i-1} and Z_i. The origin of a frame {i} is identified as the intersection of the common normal with 
​Z_i"

and this is also shown in the figures.
