### ISSUE TITLE
Kinematics: 15 Introduction to Homogeneous Transforms and their Inverse

### ISSUE THREAD

**Issue by cornzyblack** [udacity/robotics-beta-test-issues#428]
When describing the homogeneous transform, on line 12, the first sub part of the RHS , the text says 

"​ **_A​​_ R _B_** is the 3x3 rotation matrix" , however the diagram shows **_B_  R _A_** "

![](https://d17h27t6h515a5.cloudfront.net/topher/2017/May/591e29af_image-1/image-1.png)

**Comment by thomas-at-em** [comment]
Yes, the rotation component in the homogeneous transform in the attached figure is incorrect. The super and subscripts of R should be reversed. Great catch!
