### ISSUE TITLE
L2.2 Rosdep - wrkspc needs to be source

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#430]
to run rosdep, devel/setup.bash needs to be sourced. A mention should be added. When using roslaunch, a new terminal would be opened for typing rosdep and this needs to be sourced to run it.

[link to lesson](https://classroom.udacity.com/nanodegrees/nd209-beta/parts/ae288087-b8ef-4e2d-97ff-a85993300ac7/modules/2919466f-aa2b-4424-b86a-98b0a53ce335/lessons/658c94f5-f806-4273-9001-9e2838e56856/concepts/ad9785ee-a561-4a98-bf11-a8ef32d6fc75)

**Comment by bkinman** [comment]
Added a note! Thanks!
