### ISSUE TITLE
crl Kinematics

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#431]
In general, I think the content in this lesson is not easy to understand. I mean, there are some figures missing some values, more color to facilitate visualization and, of course, videos will make this things easier because the instructor can show where the things are. In short, improve this content is really necessary

**Comment by thomas-at-em** [comment]
Thanks for the candid feedback, I do appreciate it. What you see in the classroom right now are "placeholder" images. I haven't received the professionally made illustrations/animations yet. I think these images will help tighten things up once they can be imported into the classroom.
