### ISSUE TITLE
Kinematic - L01C12 Composition of Rotations

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#432]
It would be great if the [third image](https://d17h27t6h515a5.cloudfront.net/topher/2017/May/591e04c4_image-2/image-2.png) had dashed lines for frame B just like the [first](https://d17h27t6h515a5.cloudfront.net/topher/2017/May/591e0401_image-0/image-0.png) and [second](https://d17h27t6h515a5.cloudfront.net/topher/2017/May/591e0465_image-1/image-1.png) images did. Adding colour is also an option - just something to help distinguish what's what.

**Comment by thomas-at-em** [comment]
These are meant to be placeholder images, which I truly hate, but lack the time to significantly improve. Feel free to propose/sketch something better and I will see if we can get the professional illustrators to make it.
