### ISSUE TITLE
Kinematics Feedback

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#433]
The Kinematics sections provides a good technical discussion into the formulas that are used. Perhaps it would be beneficial to have the content creator provide an intuitive approach to the kinematics framework as well to help the student build intuition.

**Comment by kylesf** [comment]
Do you still hold this sediment with the updated material in the classroom?

**Comment by letyrodridc** [comment]
Hey Kyle, sorry the delay. I need to find time to take a closer look to kinematics lesson and project. I will post by then.
