### ISSUE TITLE
Jupyter Bug with OS X update

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#435]
There is a  a bug with jupyter that's cropped up with a recent update to OS X. 
There's a discusion here: https://github.com/jupyter/notebook/issues/2438

Just encountered a student in Live Help having this problem. People seemed to have found a solution. Course material should be updated to reflect this.

**Comment by ryan-keenan** [comment]
Thanks for reporting this!  Didn't see it right away, but I've now added a note in the "Environment Setup" page in the classroom and on the markdown instructions in the repo.
