### ISSUE TITLE
ROS Essentials Lesson 2 - ROS Packages

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#442]
While or before introducing catkin, wouldn't it be better to first give an overview, preferably visually, of what a ROS package is? 

The `Overview of Catkin Workspaces and Packages` is great, but I think it might help if there were appropriate visuals to better talk the students through the "setup". And this could include explaining it from the viewpoint of ROS packages perhaps?

What do you think? [Although, I understand this is limited based on resources and something that you can come to later as well].

**Comment by bkinman** [comment]
I can imagine a visual that might be pretty helpful.

Essentially, it would be a headshot and animation that really drives the idea home that all ROS systems are essentially composed of packages... I could mention the fact that the OSRF maintains the debian repository containing all the packages... I could then discuss the packages which are part of a typical robot, such as EMbot, which was introduced earlier.

This is good feedback, thanks... I'm going to add the backlog label for now though, as I think this will be an improvement for later.
