### ISSUE TITLE
ROS Essentials Lesson 2 - Create A Workspace

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#443]
In this lecture, it's mentioned -

```
Let’s list the contents of the current directory to see what changed.
```

Couple of things -

- Do you think there should be a need to first have them check what it looks like before initializing the workspace?

- The above reminded me, shouldn't it be explained what initializing a workspace actually means?

- Should it be explained what the symbolic link entails and/or why it's important? Otherwise, having them check what's changed isn't of much benefit, right?

I know you mention it's not important to have a deep understanding of it. But I am wondering where the balance should be between explaining some details vs giving them links to explore [the latter gets important for students with time constraints]. Let me know what you guys think.

---

For `Step 5: catkin_make`

Shouldn't the `Warning` be given before they are asked to run the command, so that they don't make any mistake. It's less likely they will miss Step 4, but it's better as per me to have the warning before running the command. [There's an entire movie about this too - Dr Strange] :D 

---

For `Step 6: Commentary`

It might be of some benefit to the students if it's pointed out how important reading REP is for them and for this course (relative to the broader picture of learning ROS). Otherwise, they can either skip it somewhat or read it in detail depending on what's important to move further.

**Comment by bkinman** [comment]
> Do you think there should be a need to first have them check what it looks like before initializing the workspace?

I don't think so. I mean, they just created an empty directory in the very last command. There will be absolutely nothing in it.

> The above reminded me, shouldn't it be explained what initializing a workspace actually means?

We should I've added a note to the script that there should be an additional paragraph or so explaining what it means to be initialized, and what `CMakeLists.txt` is actually for.

> Should it be explained what the symbolic link entails and/or why it's important? Otherwise, having them check what's changed isn't of much benefit, right?

It should, agreed. Made a note in the script doc to also include this explanation.

>I know you mention it's not important to have a deep understanding of it. But I am wondering where the balance should be between explaining some details vs giving them links to explore [the latter gets important for students with time constraints]. Let me know what you guys think.

I think we could do better here and agree with your feedback.

> For Step 5: catkin_make ...

Fixed!

> For Step 6:

Made a node in the script for future revisions.

Whew! Lots of detailed feedback, thanks!
