### ISSUE TITLE
ROS Essentials Lesson 2 - Package Name Typo in "Dive Deeper into Packages"

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#444]
In this lecture, it's mentioned -

```
 Let’s name ours “first_project” and we won’t specify any dependencies. By convention, package names are lowercase.
```

It says to name the package `first_project`

But then, the next command is -

```
catkin_create_pkg first_package
```

It's a one-word difference, but I don't want it to crop up in later lessons and cause any issues for students if they try to copy paste commands and the words get interchanged somewhere.

**Comment by bkinman** [comment]
Oops, fixed!
