### ISSUE TITLE
L03E03-simple_mover code

### ISSUE THREAD

**Issue by manalips30** [udacity/robotics-beta-test-issues#445]
When the code is explained, rate.sleep is added in the while loop whereas it is not present in the original code. It should be consistent in both places.

Code:
while not start_time:
        start_time = rospy.Time.now().to_sec()

Explained Code Section:
 while not start_time:
        start_time = rospy.Time.now().to_sec()
        rate.sleep()

**Comment by bkinman** [comment]
Good catch, fixed!
