### ISSUE TITLE
sjuneja L3E3 - Simple Mover: The Code incomplete command for explanation

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#451]
classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/e12c47b6-316e-4a0b-aae5-2f2c5fcd99f5/concepts/cf5f5628-9a52-4500-a862-d08a2967b3ca

In the above, we first have the entire code for the script. One line is 
```python
rospy.init_node('arm_mover', anonymous=True)

```

Scroll down a bit, and we get to the explanation for the above 

```python
rospy.init_node('arm_mover')
```

The `anonymous` argument is missing, and no explanation is provided for that here.

---

Also, the following in the entire code -

```python
while not start_time:
        start_time = rospy.Time.now().to_sec()
```

But scrolling down for the explanation -
```python
while not start_time:
        start_time = rospy.Time.now().to_sec()
        rate.sleep()
```

There's an additional `rate.sleep()` command.

---

Adding this here since it's for the same lecture, but not related to the code -

```
The try/except blocks here are significant as rospy uses exceptions extensively. The particular exception being caught here is the ROSInterruptException.
```

It might be good to add a link to any more information regarding these exceptions in ROS.

---

In `mover_code()` in the initial code at the top, we have -
```python
pub_j1 = rospy.Publisher('/simple_arm/joint_1_position_controller/command',
                             Float64, queue_size=10)
pub_j2 = rospy.Publisher('/simple_arm/joint_2_position_controller/command',
                             Float64, queue_size=10)
```

But during the explanation -
```python
def mover():
    pub_j1 = rospy.Publisher('/simple_arm/joint_1_position_controller/command',
                             Float64)
    pub_j2 = rospy.Publisher('/simple_arm/joint_2_position_controller/command',
                             Float64)
```

The `queue_size` is missing and there's no explanation on what that argument is for.

**Comment by bkinman** [comment]
1. Fixed the anonymous issue.
2. Good catch, fixed.
3. Added a link to an explanation of the rospy exceptions!
4. Fixed the queue_size thing.
