### ISSUE TITLE
arek - Project: Robotic Arm: Pick & Place - 11. Project: Robotic Arm: Pick and Place

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#454]
arek - Project: Robotic Arm: Pick & Place - 11. Project: Robotic Arm: Pick and Place

Some links are pointing into 404 Not Found pages, please ensure all links works properly because that would be really helpful!

**Comment by kylesf** [comment]
All the links are checked and working with the exception of the final project github link, which has yet to be created. Moving to in progress until last link is in place!

**Comment by kylesf** [comment]
Fixed!
