### ISSUE TITLE
Search and Sample Return Project - Wrong csv format in repo

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#456]
The `test_dataset` provided in the repository uses the delimiter `,` instead of `;` . This can lead to problems when trying to read the csv using the new notebook format `df = pd.read_csv('../test_dataset/robot_log.csv', delimiter=';', decimal='.')`

**Comment by ryan-keenan** [comment]
Thanks for catching this!  It's fixed now.
