### ISSUE TITLE
sjuneja L3.3 Simple Mover: The Code better visualization

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#458]
I was thinking if it would be better for new students if the robot was made to move in a pattern which they can easily visualize while looking at the code and then confirm it when they see the robot's joints moving? I am not saying the current movements aren't, just that 

- Maybe breaking it down into two sets of motions for each joint, running them separately?
- Having the end-effector following a different specific pattern instead - like a simple circle, or a letter.
- For the above, we could add a bit of code where the end effector traces that path and it's visible to the students as if it's "drawing it out"? Not sure there's functionality for that (looking into it)

What do you guys think? Better for them or too complicated?

**Comment by bkinman** [comment]
This is not a bad suggestion. I'm going to go ahead and label this "backlog" for now.
