### ISSUE TITLE
sjuneja L3.4 Required changes to CMakeLists already exist

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#460]
https://classroom.udacity.com/nanodegrees/nd209-beta/parts/ae288087-b8ef-4e2d-97ff-a85993300ac7/modules/2919466f-aa2b-4424-b86a-98b0a53ce335/lessons/ade14c05-008c-4802-bfd8-f0271db9facc/concepts/0e711050-3964-4135-9f20-d28b17ccd644

It's mentioned -
```
Next, replace the commented-out add_service_files() macro with the following:
```

The content following the above is already there in the CMakeLists, so perhaps the statement shouldn't be to `replace` but to `uncomment`?

**Comment by kylesf** [comment]
Made those changes. Thanks!
