### ISSUE TITLE
sjuneja L3.5 Arm Mover:The Code Too rough an introduction for many details

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#461]
https://classroom.udacity.com/nanodegrees/nd209-beta/parts/ae288087-b8ef-4e2d-97ff-a85993300ac7/modules/2919466f-aa2b-4424-b86a-98b0a53ce335/lessons/ade14c05-008c-4802-bfd8-f0271db9facc/concepts/ee8b24b2-bfbb-4c8d-a173-72591e661e12

```The “~” is the private namespace qualifier, and indicates that the parameter we wish to get is within this node’s private namespace /simple_arm/ (e.g. ~min_joint_1_angle resolves to /simple_arm/min_joint_1_angle).```

I think namespaces in ROS should be covered better and before the above statement. This might be important because many might not be aware of what a namespace is.

---

```
in the case that rospy.get_param() was unable to get the parameter from the param server.
```

I might be wrong, but there hasn't been an explanation on what a param server is.

---

```
The rest of this function simply clamps the joint angle if necessary. Warning messages are logged if the the requested joint angles are out of bounds.
```

Just a typo - Two "the"s in there.

---

In the piece of code with `rospy.logwarn` a link to log warnings in ROS would be helpful.

---

In the `handle_safe_move_request()` function 
we have the following -
```
move_arm(clamp_j1, clamp_j2)
```

`move_arm` is supposed to return `time_elapsed`. Since that's not being assigned to a variable explicitly here, it might be important to have a small explanation why so that students don't get confused.

---

```
This section of code is similar, to that of simple_mover().
```

In `simple_mover()` it was explained what each step does and that a separate function which published the necessary controller commands was called in `main` along with defining the `rate` and etc. 

A small explanation why that's not done here would help students make a proper connection between the two and understand the flow of the whole thing.

**Comment by bkinman** [comment]
1.Param server was indeed explained, but I don't think that you guys had a chance to view the videos.

2. Not sure what you mean by a link to the log warnings? Can you create another ticket for this explaining what you mean? I'd like to limit the number of concerns in each issue. Thanks!

3. I fixed the time_elapsed thing with mov_arm, nice catch!

4. The overall structure should be clear here, I hope. Students should know python by this point... To be honest though, I'm not 100% sure what you're mentioning here. Could you perhaps create another ticket for this?
