### ISSUE TITLE
sjuneja L3 Write ROS Nodes - A summary or graph of everything

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#462]
The lesson builds everything up and shows the student in the end what happens via the camera.

Which I honestly think is really awesome.

But I feel that there should be a summary graph at the end which kind of shows what each function that they wrote eventually looks like for that whole movement of the manipulator.

Something similar to the rqt graph, but with visuals shown in the initial ROS videos where you showed connections between nodes the messages being passed and such. 

I think that visual would really help solidify what they built in the end.

**Comment by bkinman** [comment]
This is not a bad idea. Going to put this in the backlog.
