### ISSUE TITLE
sjuneja L3.6 Arm Mover - Probably incorrect phrase for where to check out of bounds angle

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#463]
It's explained
```
 Looking at the roscore console, we can very clearly see what the problem was. The requested angle for joint 2 was out of the safe bounds. We requested 1.57 radians, but the maximum joint angle was set to 1.0 radians.
```

It says `roscore console`. But technically it isn't that, right? This might confuse students slightly, because they can get the warning in the tab/window where they run their `roslaunch` command. 

The warning appears as 
```
[WARN] [1496095974.262102, 491.087000]: j2 is out of bounds, valid range (0,1.0), clamping to: 1.0

```

So perhaps this should be clarified a bit?

**Comment by bkinman** [comment]
The error should appear both in the roscore console and the console for the actual node, I believe. If you had launched the node separately, it would have happened in both places.

I don't find this to be incorrect.
