### ISSUE TITLE
sjuneja L1.8 Rotation Matrices in 3D - Mistake in axis of rotation

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#466]
In the lecture,

```
Let’s consider two frames, {A} and {B}, that are initially aligned. Frame {B} is then rotated about 
a_z by an angle theta

```

Shouldn't it be `b_z` since it's in reference to Frame B? I know since they are aligned it's fine, but proper terminology would be `b_z`, correct?

**Comment by thomas-at-em** [comment]
The axes are collinear. Either statement is correct.
