### ISSUE TITLE
sjuneja L.20 Working through the steps for D-H algorithm

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#469]
Stating the points won't help at all. There needs to be a step-by-step procedure for the students to be able to work it out on a relatively simple manipulator. Followed by a relatively complex manipulator where the final outcome is provided to them to cross-check. This is very important as per me.

**Comment by Shreeyak** [comment]
+1 There should also be an image to indicate what is meant. A good solved example will make all the difference

**Comment by thomas-at-em** [comment]
I have a whole screencast devoted to working an example in detail. It unfortunately wasn't in the classroom yet when you reviewed the material.
