### ISSUE TITLE
sjuneja P01.13 Autonomous Mode - Launching drive_rover.py

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#475]
A student on live-help pointed out that when they ran the command it wasn't matching up with the mentioned expected output in the lesson.

```
python drive_rover.py
(1439) wsgi starting up on http://0.0.0.0:4567
```

The above should also include
```
NOT recording this run ...
```
It's a very small problem, but since it confused one student I thought it should be added.

**Comment by ryan-keenan** [comment]
Good catch!  Added this now.
