### ISSUE TITLE
qiang: Introduction to Kinematics - 18 Denavit-Hartenberg Parameter Assignment Algorithm

### ISSUE THREAD

**Issue by luqiang21** [udacity/robotics-beta-test-issues#476]
This will guarantee that α​0​​  = a​0​​  0, and, if joint 1 is a revolute, d​1​​  = 0. If joint 1 is prismatic, then θ
​1​​ = 0.

Here do you want to say α​0​​  = a​0​​ = 0?

**Comment by thomas-at-em** [comment]
Yes, you are correct. And thank you for including the lesson title in your ticket, it makes finding the problem much easier!
