### ISSUE TITLE
vivek1108: DH parameters, common normal

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#478]
Identify the common normal between frames {i-1} and frame {i}, it would be benefitial to write common normal between z-axes.

**Comment by thomas-at-em** [comment]
I don't understand what problem you are identifying. Could you provide more details please?

**Comment by vxy10** [comment]
In link below, item 4. It says identify common normal between frames i-1 and i. However, what we need to do is to identify common normal between z-axes of i-1 and i. Its a minor point, but will be nice to clarify. 

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/72800973-80cd-4828-81fd-b3390486892b/modules/8855de3f-2897-46c3-a805-628b5ecf045b/lessons/87c52cd9-09ba-4414-bc30-24ae18277d24/concepts/2f59c902-9c32-4b26-9e52-5e495ec14dba

**Comment by thomas-at-em** [comment]
Hey, sorry for the late reply, I have been out sick. I see your point. Should be fixed now. Thanks!
