### ISSUE TITLE
arek - Introduction to Kinematics - 7. Coordinate Frames and Vectors

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#479]
arek - Introduction to Kinematics - 7. Coordinate Frames and Vectors
The first equation introduces theta without explaining what angle that is because theta is missing from the 2 drawings above the equation.
Then the third drawing has theta as an angle difference between frames which is not the theta used in the equation I mentioned at the beginning. I hope this explanation is clear because I put effort into making it concise and lucid. Please ask questions.

**Comment by thomas-at-em** [comment]
Thanks, I see what you are saying. I will see if I can get our professional illustrators to make that correction.
