### ISSUE TITLE
arek - Introduction to Kinematics - 15. Homogeneous Transforms and their Inverse

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#481]
arek - Introduction to Kinematics - 15. Homogeneous Transforms and their Inverse
I copied the solution to starter.py and clicked on Test Run and received the following error and was expecting no error. Do we want the student to receive the error when they copy and paste the solution therefore making them change P_A to P or the pasted solution should just work? Please see screenshot attached. 
Traceback (most recent call last):
  File "vm_main3.py", line 47, in <module>
    import main
  File "/tmp/vmuser_abdzafiqvl/main.py", line 2, in <module>
    import studentMain
  File "/tmp/vmuser_abdzafiqvl/studentMain.py", line 4, in <module>
    print('P in {A} is: \n', starter.P,'\n')
AttributeError: 'module' object has no attribute 'P'

![screen shot 2017-06-02 at 03 15 36](https://cloud.githubusercontent.com/assets/28066540/26715072/363bda1e-4742-11e7-8b0f-17cbd03787f8.png)

**Comment by thomas-at-em** [comment]
Ah, I see the problem. Good catch! Should be fixed now.
