### ISSUE TITLE
arek - Project:Robotic Arm: Pick& Place -  11. Inverse Kinematics with Kuka KR210

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#482]
#arek - Project:Robotic Arm: Pick& Place -  11. Inverse Kinematics with Kuka KR210
At the bottom of the page usage of undefined acronyms RPY, RHS, LHS. These acronyms need to be defined. Please see screenshot below.
![screen shot 2017-06-03 at 08 01 25](https://cloud.githubusercontent.com/assets/28066540/26753404/61f28922-4833-11e7-98da-f33f1d8f55b2.png)

**Comment by kylesf** [comment]
Made updates to address this.
