### ISSUE TITLE
Project 2 - L11- Inverse Kinematics with Kuka R210

### ISSUE THREAD

**Issue by GabrielDGP** [udacity/robotics-beta-test-issues#485]
One thing that made me spend a lot of time to understand and find these equations was the fact that I did not know that this rotation matrix was given in the form of quarterns by the ROS. Perhaps if you intrude some explanation of quarterns here or in the inverse kinetic lecture, you can improve the understanding of what you need to do to find q4, q5, and q6.

**Comment by hvpandya** [comment]
This has been fixed by new code pushes last week. Please pull from the repo.
