### ISSUE TITLE
Readme of project 2

### ISSUE THREAD

**Issue by GabrielDGP** [udacity/robotics-beta-test-issues#486]
In the readme of the project 2 that you gave on github,
It is good to say that to run your program should follow the following statement in another terminal

$ Cd ~ / catkin_ws / src / kinematics_project / kuka_arm / scripts
$ Source ~ / catkin_ws / devel / setup.bash
$ Rosrun kuka_arm IK_server.py

and not.

$ Cd ~ / catkin_ws / src / kinematics_project / kuka_arm / scripts
$ Rosrun kuka_arm IK_server.py

I spent a lot of time also to find out this, and to be able to test the code that I did.
Because there was always an error saying that Ik_server was not found.

It may be interesting to put this also in some lesson of project 2.

**Comment by hvpandya** [comment]
This is incorrect, you do not need to source every time as you already added the `setup.bash` to your `.bashrc` file.
