### ISSUE TITLE
shreeyak P02 Pick and Place

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#488]
We really need a lot more examples, for each topic. Kinematics, in my opinion should have min 3. At least 2 solved, and one as exercise with ans provided.
The level of maths required escalates quickly and many will not be able to grasp it from simple examples alone. The difficulty of the solved examples should also increase, approaching near the level of the project.

**Comment by sahiljuneja** [comment]
There is some more content added and being added to cover this. If you find some time, please go through them and let us know if you feel there's more that could help students! Thanks!
