### ISSUE TITLE
project 1 error with supporting_functions.py latest update from github

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#490]
a student is experiencing this error . he has roboND env setup and linux simulator. he pulled the new code from github on 7/6/17 (IST) . this is the error he is having

**Comment by yuvaramsingh94** [comment]
this is the error image 
https://drive.google.com/open?id=0BzmnMmsPbJkVbUFxNEZJc1hKTEE

**Comment by ryan-keenan** [comment]
Thanks for reporting, I think this is due to not having the latest simulator (and / or codebase)  please ask them to update everything and try one more time.
