### ISSUE TITLE
ROS Essentials - Typos

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#491]
I found some typos along the lesson:
 - [Run turtlesim](https://classroom.udacity.com/nanodegrees/nd209-beta/parts/ae288087-b8ef-4e2d-97ff-a85993300ac7/modules/2919466f-aa2b-4424-b86a-98b0a53ce335/lessons/2cd33882-d29e-43e8-9ff7-10398c8b5351/concepts/a4c3ac2b-85f7-42cb-80d2-d90da37ecd04): We are now free to begin begin launching nodes!

- [Echo a topic](https://classroom.udacity.com/nanodegrees/nd209-beta/parts/ae288087-b8ef-4e2d-97ff-a85993300ac7/modules/2919466f-aa2b-4424-b86a-98b0a53ce335/lessons/2cd33882-d29e-43e8-9ff7-10398c8b5351/concepts/04ab939e-0139-4afa-a35e-8a546afc79f5): To do so, we we can use the command rostopic echo

 - [Simple mover: the code](https://classroom.udacity.com/nanodegrees/nd209-beta/parts/ae288087-b8ef-4e2d-97ff-a85993300ac7/modules/2919466f-aa2b-4424-b86a-98b0a53ce335/lessons/ade14c05-008c-4802-bfd8-f0271db9facc/concepts/5789f0e3-3cf1-46c5-8702-f456c035d4af): now copy and past the code below

**Comment by sahiljuneja** [comment]
Thanks. Fixed!
