### ISSUE TITLE
Lesson 3.5(Arm Mover:The Code)

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#494]
def handle_safe_move_request(req):

    time_elapsed = rospy.Time.now()

not sure on why we have to define time_elapsed inside this function . we are returning time_elapsed form move_arm function. we should use only one of the time_elapsed to find the total time taken for moving the arm. 

we should remove one of it . either in move_arm function or at handle_safe_move_request function 

https://gist.github.com/yuvaramsingh94/7496bc2bdc9cbda17e4ea5ed986c5672

**Comment by bkinman** [comment]
Nice catch, fixed!
