### ISSUE TITLE
Lesson 3.5(Arm Mover:The Code)

### ISSUE THREAD

**Issue by sychaichangkun** [udacity/robotics-beta-test-issues#495]
In the code explanation of clamp_at_boundaries(), “~” is said to be the private namespace qualifier, representing '/simple_arm/' here. 
Anctually '~' is 'arm_mover' because the node name is 'arm_mover'.
You can imput 'rospy.get_param_names()' to see what '~' is.

**Comment by sychaichangkun** [comment]
sorry '  ~  ' can not be displayed properly.

**Comment by sychaichangkun** [comment]
In the code explanation of clamp_at_boundaries(), '  ~  ' is said to be the private namespace qualifier, representing '/simple_arm/' here.
Anctually '  ~   '   is  ' arm_mover ' because the node name is ' arm_mover '.
You can imput  ' rospy.get_param_names() ' to see what '  ~   ' is.

**Comment by kylesf** [comment]
What is the status of this issue?

**Comment by swwelch** [comment]
Updated. Thanks!
