### ISSUE TITLE
VM - 4K screen problems

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#497]
With a 4K screen, the VM has an issue where it shows a very small resolution/size corresponding to the text inside the VM. This is how it looks right now on my end (after setting Font Size to 24)

![untitled](https://user-images.githubusercontent.com/12501638/27102929-a4f23f8c-50a4-11e7-83f1-7af53c5e445c.png)

These are the current Display Options of the VM as per VMware.

![untitled](https://user-images.githubusercontent.com/12501638/27103177-733669ea-50a5-11e7-9f83-e26fc3d01711.png)

The current workaround seems to be to manually increase font size via Preferences-> Desktop Preferences (in the VM, lubuntu settings). This seems to be a problem with Vmware I believe and might get fixed at some point. 

Might have to add the workaround (font size and any other) in the FAQ.

**Comment by kylesf** [comment]
Can you share a screen shot of your Display options in the system settings?

**Comment by sahiljuneja** [comment]
@kylesf Updated post.

**Comment by sahiljuneja** [comment]
The font size change doesn't work for the terminal. Which is very annoying to look at right now 😅

**Comment by kylesf** [comment]
Can you try to manually change the size of the monitor and then make the VM fullscreen?

As for text size, what terminal are you using?

**Comment by sahiljuneja** [comment]
Yup, tried those. Didn't help. This is a known problem apparently. VMware Workstation Pro seems to have that fixed. 

The default one, LXTerminal. Can change the font size for that separately. But then trying to work with RViz and Gazebo and all, everything is like for ants! [Dunno if you get that reference]

I will mess around it with a bit and try for a workaround. But will probably move to virtual box or docker if nothing works. Won't personally be able to work with this.

**Comment by kylesf** [comment]
Zoolander lol. You should be able to set the preferences for terminal and have it apply for all windows. I also recommend using terminator for ROS instead. Try playing with font there.

**Comment by sahiljuneja** [comment]
No solution came out of the VMWare Workstation Player itself for me. 

Did manage with some changes to lubuntu itself. 

Steps to follow -

- In home directory, create file `.Xresources`
- In the file enter desired DPI value in this format: `Xft.dpi: 150` (change 150 to number that works best for you)
- Restart the VM

The above is the only thing that has worked reasonably without any noticeable performance issues. Although, even with a powerful laptop, the VM is a resource hog and still performs relatively poorly compared to a full installation. Which is expected I guess.

I will add this to the wiki section soon. Feel free to close it if nothing more to add.
