### ISSUE TITLE
Intro to Linux

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#506]
Student feedback - student wanted Linux resources because being new the Linux, (s)he was very confused in the ROS section.

Could add a link to the following course somewhere: 
https://www.udacity.com/course/linux-command-line-basics--ud595

**Comment by ryan-keenan** [comment]
Thanks for the feedback Julia, I've added this link to the "Your Virtual Machine" concept in ROS Essentials L1
