### ISSUE TITLE
arek - P2 Lesson 9. Pick and Place Demo Walkthrough

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#510]
arek - P2 Lesson 9. Pick and Place Demo Walkthrough

The path to `inverse_kinematics.launch` is incorrect as `kinematics_project` and should be changed to `RoboND-Kinematics-Project`

Please see screenshot attached with marked problem in red ellipse.
![screen shot 2017-06-30 at 15 04 15](https://user-images.githubusercontent.com/28066540/27750494-04a9a326-5da6-11e7-9da9-bc86e883f1ac.png)

**Comment by sahiljuneja** [comment]
Thanks for pointing this out! Fixed it.
