### ISSUE TITLE
arek - P2 Lesson 15. Creating IK Solver for Kuka KR210

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#511]
arek - P2 Lesson 15. Creating IK Solver for Kuka KR210

The path for `IK_sercer.py` shows as `kinematics_project` which is incorrect. It should be changed to: `RoboND-Kinematics-Project`.

Please see screenshot attached with annotated exact location of the error in red oval:

![screen shot 2017-06-30 at 15 18 55](https://user-images.githubusercontent.com/28066540/27750946-15299164-5da8-11e7-93fe-ed53102ec5f3.png)

**Comment by sahiljuneja** [comment]
Fixed. Thanks!
