### ISSUE TITLE
Perception L2E11 rajat

### ISSUE THREAD

**Issue by rajmis** [udacity/robotics-beta-test-issues#512]
Submit button throws the following error:

"/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Environment: {'executor_result': {u'vm_time': 1.2752389907836914, u'stdout': u'', u'vm_creation_time': 8.392333984375e-05, u'test_results': [], u'stderr': u'Traceback (most recent call last):\n File "vm_main3.py", line 47, in \n import main\n File "/tmp/vmuser_ygjhzqqfse/main.py", line 2, in \n import aiMain\n File "/tmp/vmuser_ygjhzqqfse/aiMain.py", line 121, in \n image = mpimg.imread('sample1.jpg')\n File "/usr/local/lib/python3.4/dist-packages/matplotlib/image.py", line 1227, in imread\n im = pilread(fname)\n File "/usr/local/lib/python3.4/dist-packages/matplotlib/image.py", line 1205, in pilread\n with Image.open(fname) as image:\n File "/usr/local/lib/python3.4/dist-packages/PIL/Image.py", line 2312, in open\n fp = builtins.open(filename, "rb")\nFileNotFoundError: [Errno 2] No such file or directory: 'sample1.jpg'\n', u'exec_server_time': 1.2829899787902832, u'exec_status': u'error'}, 'grade_result': {'comment': 'Thank you for your submission!', 'feedback': '', 'completed': None, 'test_results': [], 'bin_codes': [], 'correct': False}, 'executor_status': u'error'}
Submission: {'_operation': 'REGRADE', u'point_cloud.py': u'import matplotlib.pyplot as plt\nimport matplotlib.image as mpimg\nfrom mpl_toolkits.mplot3d import Axes3D\nimport numpy as np\nfrom time import time\n\n# Read in the image and depth map as seperate assets\nimage_location = '1.png'\ndepth_map_location = '2.png'\n\n# Load in the images\ndepth_map = mpimg.imread(depth_map_location)\nimage = mpimg.imread(image_location)\n\nstart_time = time()\nfig = plt.figure()\nax = fig.add_subplot(111, projection='3d')\n \nrows, cols = depth_map.shape\n\n# Send pixels not correctly mapped to the back\nmax_val = depth_map.max() * 1.1\n\ncount = 0\n\n# Cut down pixels for time purpose \n# Computations need to be under 30s\npixel_cut = 3 \n \n# Interate thorugh all the pixels \nfor x in range(cols):\n for y in range(rows):\n if (x % pixel_cut == 0 and y % pixel_cut == 0):\n \n # Count points done\n count+=1\n \n # Get point color\n pixel_color = (image[y,x,0],image[y,x,1],image[y,x,2])\n \n # Get point depth\n depth = depth_map[y,x]\n \n # Send points not correctly mapped to the back\n if depth == 0:\n depth = max_val\n \n ax.scatter(x, depth, y, c = pixel_color, marker='o')\n\n# Axis Labels\nax.set_xlabel('Width')\nax.set_ylabel('Depth')\nax.set_zlabel('Height')\n\nplt.gca().invert_zaxis()\n\n###########################################\n# Play with me to change view rotation!\nelevation = 30 # Up/Down\nazimuth = 3 # Left/Right\n###########################################\n\n\nax.view_init(elevation, azimuth)\n\nplt.show() # Uncomment if running on your local machine\nprint ("Outputed {} of the {} points".format(count,6552))\nprint ("Results produced in {:04.2f} seconds".format(time()-start_time))'}

**Comment by kylesf** [comment]
Fixed. Will updated the quiz to be more challenging the in the future.
