### ISSUE TITLE
Lesson 2: Introduction to 3D Perception, Active vs Passive Sensors

### ISSUE THREAD

**Issue by cornzyblack** [udacity/robotics-beta-test-issues#514]
I believe the first diagram for Active and Passive sensors is meant to give an idea of what Active and Passive sensors are. In the diagram, the visual representation for the Passive part is clear ->
sun rays hit a robot, and the video camera is able to measure the reflected rays without any need to release energy into the environment. However for the Active part the video camera sends energy into the environment, but nothing is reflected back (Although something is meant to). Just a thought, why not use a Camera with a flash for the Active sensor, and show the rays being reflected back, and a Camera without a flash for passive sensor

**Comment by kylesf** [comment]
This is a great idea and we will keep it in mind for future updates!

**Comment by ryan-keenan** [comment]
Just made this update!  Looks like this now
![02_In-Depth-Look-at-3D-Sensors-and-Sensing-Techniques_-T_D__1-update.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/580d7944f8087f0e00ff12bf/125516c66e82c728ace21e0d46b8c6a50a8cce8d8af9ab4be971ff9b220b2667645787664380ed3bb050684c0e011ab1220d0107a5a7de36c2e36f28d4054aa8842e3069a25265c3d78302fa41ee71cf1a97aaaeca0e9fb26876a399855d3b16511180ac0930f69a1dca58fe4be14904ac106530b572246055d64f2b78343a7fe1a99d448d9763a5b0112b5fc1e1e2f21110a675d9c61b3c.jpg)
