### ISSUE TITLE
Perception 2: Active vs Passive Sensors

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#516]
Should this concept be split into two - the second being Active Sensors.

1. Active vs Passive Sensors
2. Active Sensors
3. Passive Sensors

Otherwise the order/naming of the concepts is a bit confusing.

**Comment by jchernus** [comment]
Also, I think Pros/Cons would be better delivered as two-column bullet points than a table.

**Comment by kylesf** [comment]
Changed for now. May need to revaluate.
