### ISSUE TITLE
Perception 2: RGB-D Cameras - Revise Text?

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#518]
1. "In general, an RGB-D camera consists of a normal RGB camera along with an infrared (IR) projector and receiver." 

sounds repetitive to the paragraph immediately above it. Can you just say, 

"Traditionally, the active depth sensor is an infrared (IR) projector and received."

2. First image - either make stand darker, or pointing lines darker (preferred). Hard to see what labels relate to.

3. Non-trivial images should be referenced (or even explained) in text.

4. "RGB-D sensors" -> "RGB-D cameras" ?

5. Consistency, in a previous slide you said "~2cm to 5m" and here you say "~0.2 to 2m".

**Comment by kylesf** [comment]
Done. Thanks!
