### ISSUE TITLE
crl Lesson 6, Perception, E04 Quiz

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#520]
There is an indentation issue in the first line of quiz

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/571766f0-9631-484d-a69f-94ea58110725/modules/e5bfcfbd-3f7d-43fe-8248-0c65d910345a/lessons/8d51e0bf-0fa1-49a7-bd45-e062c4a2121f/concepts/a9440090-ecd4-4f89-b0d4-f523259394f0

**Comment by sahiljuneja** [comment]
Thanks! Fixed it.
