### ISSUE TITLE
Perception - Tabletop Segmentation Exercise - PCL imported twice on the script

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#522]
As you can see [here](https://classroom.udacity.com/nanodegrees/nd209-beta/parts/571766f0-9631-484d-a69f-94ea58110725/modules/e5bfcfbd-3f7d-43fe-8248-0c65d910345a/lessons/8d51e0bf-0fa1-49a7-bd45-e062c4a2121f/concepts/02cbb56e-9e54-4c08-977b-df149cb0bca4), PCL is imported twice on the text. I checked the file in the repo and the code is correct there.

**Comment by hvpandya** [comment]
Fixed, thanks
