### ISSUE TITLE
Perception - Active sensors - lidar interface

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#523]
The chart for lidar sensors in [this lesson](https://classroom.udacity.com/nanodegrees/nd209-beta/parts/571766f0-9631-484d-a69f-94ea58110725/modules/e5bfcfbd-3f7d-43fe-8248-0c65d910345a/lessons/56ce88d9-6c4c-4714-a40a-541fa759dbdd/concepts/229a4414-fe3d-46e7-a94f-4e4de10f2dd6) shows that the interface for this kind of sensors is Ethernet. This is the most common thing, but not always true. e.g: [Hokuyo URG-04LX-UG01](https://www.hokuyo-aut.jp/search/single.php?serial=166) uses USB instead of Ethernet.

**Comment by hvpandya** [comment]
We are only referring to 3D lidars, remember the name of this lesson is Intro to 3D perception. I will add statements in the lesson to make sure that this point is clear
