### ISSUE TITLE
Perception L03E04: Camera Calibration Pattern

### ISSUE THREAD

**Issue by maunesh** [udacity/robotics-beta-test-issues#527]
Below are some additional notes that I have written to explain **Camera Calibration** intuitively. I feel it's important to introduce this topic with the problem that we are trying to solve first, before jumping right into selecting calibration pattern. (A few students were a little lost when this topic was introduced in Self-Driving Car Nanoderee.)

**Camera Calibration:**

> ***Problem:*** When we take picture/video, using any camera, we may get some distortion in our image, typically at the corners of the image (visualize fisheye lens effect). This is just an example of various artifacts, and you may get other types of distortions or no distortion at all. Now, since we are planning to use our images do some precise calculations, this distortions could potentially give us bad or completely wrong results. This is the problem that we are trying to solve.

> ***Solution:*** Let's think about how we can fix the distortion artifacts in our images.. If we take a well defined pattern, and take a picture of it, and then try to come up with a matrix (called the Camera Matrix), that can transform the pattern in a distorted image, back to the correct well-defined pattern that we expect, then we can use the same matrix (the Camera Matrix) on all of the future images that we take, and correct the distortions in them. In other words, we are placing a known object in real world, taking a picture of it, and then identifying correspondence between the real world scene and the distorted image, and then computing the mapping between them.  Now, to map the correspondence points between real world to camera, we would need to select some points/features in the images. *Corners* are a great option as feature points, because in the regions around the corners, image gradients have two or more dominant directions. Read about "[Corner Detection](https://en.wikipedia.org/wiki/Corner_detection)" to understand more. For now, you simply need to know that corners are great features points and we would simply use cv2.findChessboardCorners to detect them in our chessboard images. 
To calculate the camera matrix that we mentioned earlier, we can use cv2.calibrateCamera. This function takes in points in world coordinates and points in image coordinates (those corners points that we found) as inputs, comes up with the transformation matrix that maps them, and then returns that Camera Matrix.

**Comment by ryan-keenan** [comment]
Thanks Maunesh, I'll do my best to incorporate your feedback!
