### ISSUE TITLE
Lesson 2, Concept 5 Quiz

### ISSUE THREAD

**Issue by thomas-at-em** [udacity/robotics-beta-test-issues#530]
Quiz should be re-designed to:
(a) remove extraneous choices from selection list
(b) state the answer choices are active, passive, or hybrid 
(c) give some indication as to the number of incorrect answers OR
(d) explicitly indicate which selections are incorrect

**Comment by haoyang-udacity** [comment]
https://classroom.udacity.com/nanodegrees/nd209/parts/c199593e-1e9a-4830-8e29-2c86f70f489e/modules/e5bfcfbd-3f7d-43fe-8248-0c65d910345a/lessons/56ce88d9-6c4c-4714-a40a-541fa759dbdd/concepts/9e14db7e-0479-4782-87aa-c31afcebafc0
