### ISSUE TITLE
Awkward phrasing, grammatically incorrect

### ISSUE THREAD

**Issue by thomas-at-em** [udacity/robotics-beta-test-issues#532]
Lesson 3, Concept 7 - Extrinsic Calibration
Current text:
"The relation between position of a point in the 2D pixel coordinate and 3D point position in world coordinate, is defined by using the pinhole camera model:"

Suggested Edit:
"The relation between position of a point in the 2D pixel coordinates and 3D point position in world coordinates, is defined by the pinhole camera model:"

**Comment by hvpandya** [comment]
Fixed, thanks
