### ISSUE TITLE
crl Calibration, L03E15

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#533]
I could not find a valid link to download the file table_scene_lms400.pcd. So, I had to go to PCL site and download the file from there.

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/571766f0-9631-484d-a69f-94ea58110725/modules/e5bfcfbd-3f7d-43fe-8248-0c65d910345a/lessons/8d51e0bf-0fa1-49a7-bd45-e062c4a2121f/concepts/fdb3a445-43e0-4a02-81e2-0448432c156f

**Comment by sahiljuneja** [comment]
The tabletop.pcd is provided in the github repo for the exercise. 

Here's the direct link - https://github.com/udacity/RoboND-Perception-Exercises/tree/master/Exercise-1 of where the file is located.

You shouldn't have to download additional files.

**Comment by zenetio** [comment]
Note that I am not talking about tabletop.pcd but table_scene_lms400.pcd

**Comment by kylesf** [comment]
Can you provide the link to where you downloaded the file? I will add it to the classroom :)

**Comment by kylesf** [comment]
Classroom is updated.
