### ISSUE TITLE
abhi_: Passive sensors: L02E03

### ISSUE THREAD

**Issue by abhiojha8** [udacity/robotics-beta-test-issues#536]
It would be really nice to have a link for triangulation technique to get depth data from a scene. 

We can add the following research paper for curious readers: http://robotics.stanford.edu/~ang/papers/ijcv07-monocular3dreconstruction.pdf

**Comment by kylesf** [comment]
@ryan-keenan Thoughts on this?

**Comment by ryan-keenan** [comment]
@abhio9vt thanks for the reference!  Just added the link.
