### ISSUE TITLE
L03E08: Table top segmentation exercise

### ISSUE THREAD

**Issue by abhiojha8** [udacity/robotics-beta-test-issues#544]
I think this chapter should come after "Voxel grid downsampling" or maybe this can be added as a lab at the end of this lesson.

Since we are not taught voxel grid downsampling before this exercise, it is hard to solve it.

**Comment by sahiljuneja** [comment]
I think it wasn't clear that the next few sections would walk the student through this exercise from this chapter. I have clarified that now. But the intent was to introduce to what the first exercise would have the student implement, followed by implementing those parts while going through the next chapters. Hopefully, now, it would be less confusing. Thanks!
