### ISSUE TITLE
akhil - L2.8. setting up python-cpl

### ISSUE THREAD

**Issue by AkhilSharma1** [udacity/robotics-beta-test-issues#547]
When following the instructions in RoboND-Perception-Exercises github repo, `python setup.py build` gives me 'ModuleNotFoundError: No module named 'Cython' . Adding sudo seems to work here.
I am doing this in RoboNDVM 2.1.0

**Comment by sahiljuneja** [comment]
That's interesting. I didn't face such a problem when I installed it yesterday. Will wait to see if more people face this problem or not. Thanks for reporting!

**Comment by AkhilSharma1** [comment]
it is L3.8 and not L2.8. Soory :)

**Comment by AkhilSharma1** [comment]
I am also using Virtualbox instead of VmWarePlayer in case it matters
![installing pcl-python.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595d4ded6ab458001a0231e2/125516c66e82c728ace21e0d46e19a8937838fa586e7b803b45efcd9395f337b260ae1673295f127b54778154d555ca9490c564dafad8c7da5e03e70825c0be980655c27956e15bea4905dee5fee7fd616cfe3fe9846d2ea3b2fe68f86463d1906188cfc5d30a08b06.png)

**Comment by sahiljuneja** [comment]
You did install Cython first, right? There's a step for that as well. [Just to be sure]

**Comment by AkhilSharma1** [comment]
Yes, I ran the command to install it but it says that it is already installed but with some cache related warnings:
![cython.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595d4ded6ab458001a0231e2/125516c66e82c728ace21e0d46eb8d8e2b8d8debc3abaf51ab57f5973d047d317c5ca7722986e77db9117d535f574eac45095747afaada2fb4aa2e32db025fb28c341521842f1bbebb8315be05b329884886b1b88d4dc2ee2f68.png)

I had to use sudo in a couple of places including when trying to start pcl_viewer
