### ISSUE TITLE
arek - Project 2: Arm - writeup_template

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#552]
Please remove erroneous table from writeup_template under section "2. Using the DH parameter table you derived earlier..." or replace it with an example of what is expected of students. Please find below screenshot of the table to be removed because it is confusing:
<img width="912" alt="screen shot 2017-07-09 at 22 28 19" src="https://user-images.githubusercontent.com/28066540/28000776-0287745e-64f6-11e7-8adf-bd6761f0b7b2.png">

**Comment by kylesf** [comment]
Okay changed it!
