### ISSUE TITLE
Kinematics -> Project -> Move It!

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#553]
"A point to be noted is that a motion planner only generates a collision free path from start state of the robot to end state, it is Moveit! that converts this path into a joint space trajectory which obeys velocity and acceleration constraints for joint angles. "

Consider revising. I'm not sure how to do so accurately. 

"A point to be noted is that a motion planner only generates a collision free path from **the** start state of the robot to **its** end state, **and then** Moveit! converts this path into a joint space trajectory which obeys velocity and acceleration constraints for joint angles. "

**Comment by kylesf** [comment]
Sounds better. Changed it!
