### ISSUE TITLE
crl Clustering, L04E07

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#555]
There is a typo in paragraph 3: and and

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/571766f0-9631-484d-a69f-94ea58110725/modules/e5bfcfbd-3f7d-43fe-8248-0c65d910345a/lessons/2cc29bbd-5c51-4c3e-b238-1282e4f24f42/concepts/f3abc339-1d6d-42b6-9178-67e3e37eba19

**Comment by sahiljuneja** [comment]
Thanks, fixed!
