### ISSUE TITLE
crl Perception Exercise-3

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#558]
I verified that my Ex-3 worked only the first time. Then all the times that I run, the gazebo shows the first object and then the capture_features.py script stops in line 87, wait_for_message, and nothing happens.

**Comment by kylesf** [comment]
Have you made any updates with this matter?

**Comment by ryan-keenan** [comment]
This should be fixed  with the new version.  Please reopen this issue if problems persist.
