### ISSUE TITLE
Creating a point cloud Exercise x,y inverted

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#559]
Why are the x the columns and the y the rows? It's inverted as mathematical intuition. But it works! Free of bugs, just a question.

**Comment by kylesf** [comment]
Can you link to the material you are talking about?

**Comment by jchernus** [comment]
Does this have to do with (x,y) for an image being different from the (rows, cols) for a plot?

I presume you're referring to https://classroom.udacity.com/nanodegrees/nd209-beta/parts/571766f0-9631-484d-a69f-94ea58110725/modules/e5bfcfbd-3f7d-43fe-8248-0c65d910345a/lessons/56ce88d9-6c4c-4714-a40a-541fa759dbdd/concepts/6590d38f-fd2f-4111-8f4a-f980503ab086 .

**Comment by letyrodridc** [comment]
Thanks Julia. Yes, I'm referring to that lesson. Maybe that's ok, I saw in many parts the switch using x for columns, and y to rows. I think it's because it use a Cartesian representation, like a chart.  Nevermind, my mind is switched.
