### ISSUE TITLE
OpenCV Calibration Notebook

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#560]
The notebook throws an error using RoboND environment

![error](https://user-images.githubusercontent.com/9123307/28495277-d88a2156-6f1d-11e7-8f58-0a3c9cc7de95.png)

**Comment by kylesf** [comment]
Can you share the specs of the system you are using?

**Comment by letyrodridc** [comment]
Sorry Kyle, that was a really short description. 

I've tested on my computer instead of the VM. 

My computer has the RoboND anaconda environment for the first Beta-test in Search and Sample return project. I've installed it jupyter notebook.

I use a notebook, Lenovo Yoga 510. 

Processor : Intel® Core™ i5-6200U CPU @ 2.30GHz × 4 
Memory : 7,7 GiB 
Graphics: Intel® HD Graphics 520 (Skylake GT2) 

It run a Linux Ubuntu 16.04 LTS 64-bit.

**Comment by kylesf** [comment]
@ryan-keenan Any thoughts on this?

**Comment by kylesf** [comment]
I am unsure why your computer is throwing that error. I have just checked to make sure it is working in the course provided VM. Outside of the VM I am unable to diagnose problems! Closing this issue.

**Comment by letyrodridc** [comment]
Ok I will do it on the VM. thanks Kyle
