### ISSUE TITLE
crl Object Recognition: L05E07

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#562]
I think the Feature Vector graphic should be explained. I mean, who is who in the picture.

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/571766f0-9631-484d-a69f-94ea58110725/modules/a352053a-c3f0-411e-9061-44fb82f38a78/lessons/81e87a26-bd41-4d30-bc8b-e747312102c6/concepts/b1864a2b-11b4-4dfd-a8db-552209f1a38c

**Comment by kylesf** [comment]
I am not sure I follow. Do you mean label the axis for this image?
![screen-shot-2017-07-20-at-4.43.05-pm.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581230873cf83a0e0050dc25/125516c66e82c728ace21e0d46fb978826878de49ce1b057e90fa0c57e0b77246456f3667191ae7cf116284f5f5a53ec1c4a4356bcbbd671f3e57862804e0ee585645627923847afee801fb701ba24da4786e5efd948d2f42f67b6d5db1063474f4dcbed5727a29e41c95df64ae14d5ca6113065ee702431.png)

**Comment by zenetio** [comment]
No, I am talking about the Feature Vector graphic resulting from the test. It seems that we have features in 10%, 30%, 60% and so on. Is that correct? But what features? I think that we need an explanation text here.

**Comment by ryan-keenan** [comment]
Thanks for this suggestion!  I added an image and some text explanation to this concept.  Please let me know what you think (be sure to refresh the page ;):  https://classroom.udacity.com/nanodegrees/nd209-beta/parts/571766f0-9631-484d-a69f-94ea58110725/modules/a352053a-c3f0-411e-9061-44fb82f38a78/lessons/81e87a26-bd41-4d30-bc8b-e747312102c6/concepts/b1864a2b-11b4-4dfd-a8db-552209f1a38c?contentVersion=1.0.0&contentLocale=en-us

**Comment by zenetio** [comment]
Yes, its is much better! Now we know the meaning of bar distribution in the graph.
