### ISSUE TITLE
arek - Project 3 - Gtihub instructions

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#563]
arek - Project 3 - Gtihub instructions talk about the robot throwing objects away in frustration: here exactly: 
"(or thrown objects away in frustration)"
This needs to be removed because personification of robot is confusing and associating frustration as a negative emotion is  real and destructive to students. The instructions should be simple and straightforward but expression "(or thrown objects away in frustration)" is hard to understand.

**Comment by ryan-keenan** [comment]
Changed this to "sometimes the robot gets excited and throws objects across the room".  Hopefully a more positive spin ;)  Just meant to be a silly comment.
