### ISSUE TITLE
crl Object Recognition: L05E17

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#568]
I got a "topic mismatch" message when tried to run the last part of Ex3, object_recognition.py. Checking the suggested code in the lesson I see we need create 2 publishers but there is no mention in which topic name to publish. Then I tried the Maker topic and got no error. Not sure if this missing is proposal to make the student to think or it must be part of the instructions in the lesson

Please, check the end of the page here
https://classroom.udacity.com/nanodegrees/nd209-beta/parts/571766f0-9631-484d-a69f-94ea58110725/modules/a352053a-c3f0-411e-9061-44fb82f38a78/lessons/81e87a26-bd41-4d30-bc8b-e747312102c6/concepts/8389976c-550a-4fde-a530-65ca24b31f05

**Comment by sahiljuneja** [comment]
For now, I have updated the comment to indicate Message Type as well. Thanks!
