### ISSUE TITLE
Perception - Exercise 1 - Outlier Removal Filter says cloud_in instead of cloud

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#569]
In this lesson, the last code says `outlier_filter = cloud_in.make_statistical_outlier_filter()` but `cloud_in` is never defined. It uses `cloud_filtered`. https://classroom.udacity.com/nanodegrees/nd209-beta/parts/571766f0-9631-484d-a69f-94ea58110725/modules/e5bfcfbd-3f7d-43fe-8248-0c65d910345a/lessons/8d51e0bf-0fa1-49a7-bd45-e062c4a2121f/concepts/fdb3a445-43e0-4a02-81e2-0448432c156f

**Comment by sahiljuneja** [comment]
Fixed. Thanks!
