### ISSUE TITLE
Perception -> Object Recognition -> Support Vector Machine

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#572]
Would be great to have one persistent data set for students to use - where they can really see the effect of their changes. 

Hard to evaluate what each parameter does when the data keeps changing from run to run.

**Comment by ryan-keenan** [comment]
@sahiljuneja is working on modifying the quiz to accommodate this

**Comment by sahiljuneja** [comment]
Updated the quiz. Let me know if you notice any issues if you get the chance.
