### ISSUE TITLE
VM: Auto-source in terminal not working

### ISSUE THREAD

**Issue by jchernus** [udacity/robotics-beta-test-issues#575]
As evident below:

Do you want to source ROS in this workspace (y/n): y
ROS sourced!
robond@udacity:~/catkin_ws/src/sensor_stick$ roscd sensor_stick
roscd: No such package/stack 'sensor_stick'
robond@udacity:~/catkin_ws/src/sensor_stick$ cd ~/catkin_ws/
robond@udacity:~/catkin_ws$ source devel/setup.bash 
robond@udacity:~/catkin_ws$ roscd sensor_stick
robond@udacity:~/catkin_ws/src/sensor_stick$

**Comment by sahiljuneja** [comment]
That option is to select between ROS and the Anaconda Environment. In `.bashrc` you will still have to uncomment the `source devel...` line to have auto-sourcing setup.

**Comment by kylesf** [comment]
Sahil is correct in this matter! Closing!
