### ISSUE TITLE
arm_part not in confusion matrix

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#576]
The lesson shows arm_part in the confusion matrix.
![image](https://user-images.githubusercontent.com/9123307/28755222-345827da-752c-11e7-92f8-cb417a0e9a84.png)

But it doesn't appears in Exercise 3 run
![image](https://user-images.githubusercontent.com/9123307/28755229-712be318-752c-11e7-8ed0-2ae32d3472e7.png)

Lesson: https://classroom.udacity.com/nanodegrees/nd209-beta/parts/571766f0-9631-484d-a69f-94ea58110725/modules/e5bfcfbd-3f7d-43fe-8248-0c65d910345a/lessons/81e87a26-bd41-4d30-bc8b-e747312102c6/concepts/46d04b51-09cc-45bc-aedc-036a47df710e

**Comment by ryan-keenan** [comment]
Thanks for catching this!  confusion matrices now updated in the classroom.
