### ISSUE TITLE
capture_features throws Invalid cloud detected

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#577]
capture_features throws Invalid cloud detected 

robond@udacity:~/catkin_ws$ rosrun sensor_stick capture_features.py
Invalid cloud detected
Invalid cloud detected
Invalid cloud detected

Lesson: https://classroom.udacity.com/nanodegrees/nd209-beta/parts/571766f0-9631-484d-a69f-94ea58110725/modules/e5bfcfbd-3f7d-43fe-8248-0c65d910345a/lessons/81e87a26-bd41-4d30-bc8b-e747312102c6/concepts/e648c3ea-2de7-48f2-86e3-2191b7318477

**Comment by sahiljuneja** [comment]
I think Ryan answered this in the Slack. I'll close this then!
