### ISSUE TITLE
Perception - Exercise 3 - Train your SVM Solution Quiz incorrect

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#578]
Lesson: https://classroom.udacity.com/nanodegrees/nd209-beta/parts/571766f0-9631-484d-a69f-94ea58110725/modules/e5bfcfbd-3f7d-43fe-8248-0c65d910345a/lessons/81e87a26-bd41-4d30-bc8b-e747312102c6/concepts/46d04b51-09cc-45bc-aedc-036a47df710e#

This is the solution
![image](https://user-images.githubusercontent.com/9123307/28755338-95b03fc0-752e-11e7-9bf5-8f602da365bf.png)

The questions:

Fraction of the time the "soda_can" was correctly classified: 0.9
Fraction of the time the "create" was misclassified as a "beer": 0.1

seems to be incorrect.

0.9 and 0.1 are the confusion matrix values. Does the confusion matrix show the correctly classified or misclassified? Because the fraction represents always the same, I think quiz statements aren't correctly formulated, the text is incorrect.

**Comment by jchernus** [comment]
http://imgur.com/a/BluGC

Represents how the correct values were obtained. The confusion matrix doesn't show only 'correct' or 'incorrect' classifications. It shows ALL classifications. The values on the diagonal would be considered correct, as the Predicted Label matches the True Label. Everything off the diagonal is incorrect. 

Thus, when question 2 asks about a correct classification, we are looking at the diagonal. And question 3 asks about a misclassification, so we are looking at where "True Label: Create" matches up with "Predicted Label: Beer".

Does this make any more sense now?

**Comment by letyrodridc** [comment]
ahh yes, anything that is not in the diagonal is misclassification. Go it. Thanks Julia
