### ISSUE TITLE
Percetion - Exercise 3 - Error loading the model

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#579]
Hi, maybe I missed the instructions but object_recognition can't find the model:
``` 
robond@udacity:~/catkin_ws/src/sensor_stick/scripts$ ./object_recognition.pyTraceback (most recent call last):
  File "./object_recognition.py", line 206, in <module>
    model = pickle.load(open('model.sav', 'rb'))
``` 

It's not clear if we have to use the model saved before or a new model that is in some folder. 

I think it's the model that we trained, and that model is not named "model.sav" . It's "training_set.sav" and that model should be copy to the script folder because it's not finding it. 

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/571766f0-9631-484d-a69f-94ea58110725/modules/e5bfcfbd-3f7d-43fe-8248-0c65d910345a/lessons/81e87a26-bd41-4d30-bc8b-e747312102c6/concepts/e648c3ea-2de7-48f2-86e3-2191b7318477

**Comment by letyrodridc** [comment]
I found it in : 
```
robond@udacity:~/catkin_ws$ ls
build  devel  model.sav  src  training_set.sav
```
Maybe, `/home/robond/catkin_ws/` needs to be added

**Comment by luqiang21** [comment]
I also had this problem. I didn't find any code related with changing working directory in capture_features.py, but the generated sav file is not in the same directory with capture_features.py, it is under catkin_ws.
I solved this by importing os, and explicitly set the working directory as the scripts folder.

**Comment by sahiljuneja** [comment]
Updated text to reflect where the files get saved. Thanks!
