### ISSUE TITLE
crl Perception Project L06

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#580]

**Comment by zenetio** [comment]
The command rosmsg info std_msgs/Int32 showd be
rosmsg show msgs/Int32

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/571766f0-9631-484d-a69f-94ea58110725/modules/a352053a-c3f0-411e-9061-44fb82f38a78/lessons/e3e5fd8e-2f76-4169-a5bc-5a128d380155/concepts/f816b260-335a-40ec-883b-18ab27067205

**Comment by sahiljuneja** [comment]
Both of them work.

`rosmsg info std_msgs/Int32`
`rosmsg show std_msgs/Int32`
