### ISSUE TITLE
introduction to control (Building a P Controller)

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#585]
under the programming section 

in quad1d_eom.py 
at line 36 . dt = t - pid.last_timestamp_

it should be 
dt = t - p.last_timestamp_
because p is the variable which represent the object of the class p_controller
def ydot(y, t, p)

**Comment by kylesf** [comment]
Thanks, fixed!

**Comment by kylesf** [comment]
Been doing some renaming in the quizzes so they will be less confusing!
