### ISSUE TITLE
introduction to controls(using dt for integral part)

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#587]
a typical pid controller will have dt for I and D term. here we are using dt for only I and i was able t get away with not using dt for D term (my submission was accepted ). 

can you explain the reason :)

**Comment by kylesf** [comment]
Could you let me know more information so I can replicate this error and fix it?

**Comment by yuvaramsingh94** [comment]
in artificial intelligence for robotics under pid implementation section 

def run(param1, param2, param3):
    myrobot = robot()
    myrobot.set(0.0, 1.0, 0.0)
    speed = 1.0 # motion distance is equal to speed (we assume time = 1)
    N = 100
    myrobot.set_steering_drift(10.0 / 180.0 * pi) # 10 degree bias, this will be added in by the move function, you do not need to add it below!
    #
    # Enter code here
    #
    old_error = myrobot.y
    total = 0.0
    for i in range (0,N):
        error = myrobot.y
        diff = error - old_error
        total +=error
        old_error = error
        steer = -(param1*error)-(param2*diff)-(param3*total)
        myrobot= myrobot.move(steer,speed)
        print myrobot,steer

# Call your function with parameters of (0.2, 3.0, and 0.004)
run(0.2, 3.0, 0.004)


here we are not using any dt term because we have removed the dt term from the entire equation 

https://www.youtube.com/watch?v=vnOcv2xkROY
here is the course from coursera where they discussed about delta t

**Comment by kylesf** [comment]
That is for the artificial intelligence for robotics course. 

In the PID quiz for our beta section you can see in this snippet that dt is taken into account
```
        # Sum the errors
        self.error_sum_ += error * delta_time
        
        # Calculate the delta_error
        ########################################
        delta_error = error - self.last_error_
        ########################################
        
        # Update the past error with the current error
        ########################################
        self.last_error_ = error
        ########################################
        
        # Proportional error
        p = self.kp_ * error
       
        # Integral error
        i = self.ki_ * self.error_sum_
       
        # Calculate the derivative error here. Be sure to access the 
        # the internal Kd class variable
        ########################################
        d = self.kd_ * (delta_error / delta_time)
        ########################################
```

Now are you saying that you were able to by pass our quiz in the Building a PID controller section?

**Comment by yuvaramsingh94** [comment]
i was able t opass with this code . here i have not used delta_time for d calculation     

    delta_error = error - self.last_error_

########################################
        d = self.ki_ * delta_error
        ########################################
        
        # Set the control effort
        # u is the sum of all your errors. In this case it is just 
        # the proportional error.
        ########################################
        u = p+i+d
        ########################################

**Comment by kylesf** [comment]
Ahh seems you have beat the test case! Let me make it more strict :)

**Comment by yuvaramsingh94** [comment]
:)

**Comment by yuvaramsingh94** [comment]
i think i was able to beat it because the dt was a constant value . dt will be effective if the time gap is varying

**Comment by kylesf** [comment]
Should be fixed now.

**Comment by kylesf** [comment]
Let me know!

**Comment by kylesf** [comment]
?
