### ISSUE TITLE
Update classroom corresponding to new VM changes

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/robotics-beta-test-issues#588]
https://classroom.udacity.com/nanodegrees/nd209/parts/af07ae99-7d69-4b45-ab98-3fde8b576a16/modules/2919466f-aa2b-4424-b86a-98b0a53ce335/lessons/2cd33882-d29e-43e8-9ff7-10398c8b5351/concepts/0cabcedf-a31b-4f41-b85a-3e0aedbdf5e8

Specifically, the feature to switch between ROS and Conda.

Possibly add a section in the first week for the VM so that students can start using it for first project?

**Comment by kylesf** [comment]
This update is being held and we will be moving to workspaces. Therefore the VM will be deprecated.
