### ISSUE TITLE
arek - Lesson 2 - Introduction to 3D Perception - Section 11. Creating a Point Cloud Quiz

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#589]
arek - Lesson 2 - Introduction to 3D Perception - Section 11. Creating a Point Cloud Quiz

Misspelling comment inside both point_cloud.py and solution.py:

# Interate thorugh all the pixels 

should be "Iterate"

**Comment by sahiljuneja** [comment]
Thanks! Fixed.
