### ISSUE TITLE
Perception: L4 Clustering - Incorrect hint to wrong answer

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#591]
Giving an incorrect answer to question "No need to define an termination / convergence criteria for this algorithm." gives hint "DBSCAN runs through the dataset only once, doesn't iterate."

**Comment by sahiljuneja** [comment]
Could you clarify why you think it's incorrect?

In reference to the k-means section with the algorithm, since we run through the dataset in DBSCAN just once there's no need to define a termination condition unlike in k-means
