### ISSUE TITLE
introduction to controls (Building a PD controller)

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#592]
at the code section , the graph outputs u_i instead of u_d

in hover_plot.py
line no 80 
ax3.plot(time, pd.u_d, label='u_i', linewidth=3, color = 'blue')

to 

ax3.plot(time, pd.u_d, label='u_d', linewidth=3, color = 'blue')

**Comment by kylesf** [comment]
Thanks! Fixed
