### ISSUE TITLE
catkin_ws suggestion

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#594]
Each project is using the folder catkin_ws

I use to remove previous project code and add the new one. Is there a way to leave different projects in catkin_ws folder? 

Maybe we can use symbolic links.

**Comment by sahiljuneja** [comment]
All your different packages (projects) go under the `src` folder in the same catkin workspace so you don't have to remove that folder for every project. So you can have different folders named `project_1` or `project_2`, for example, in your `/catkin_ws/src/` directory and work with them individually. As long as the package names are different there won't be any clash and they should all build and run fine.
