### ISSUE TITLE
Introduction to Controls - Building a P controller

### ISSUE THREAD

**Issue by cornzyblack** [udacity/robotics-beta-test-issues#596]
Nice work! So I know the student is meant to get familiar with the codebase and this involves the student going through the python files in the Quiz window. 
I see most of the work is done in **p_controller.py** file. I would like to suggest if  `# TODO` comments can also be added to the lines in p_controller.py.

**Comment by kylesf** [comment]
I will see how students initially react before adding this change. Thanks for the feedback!

**Comment by jchernus** [comment]
This is how Perception was scripted. I think it would be valuable to keep things consistent.

**Comment by kylesf** [comment]
Closing for now but will open if student complaints arrive.
