### ISSUE TITLE
crl Introduction to Controls L01E05

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#598]
Why the lesson shows 2 set of graphs changing only the range?

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/fc3e1236-996e-4fb8-b317-479ce23c0e1d/modules/95f92697-f568-4063-b6d4-b134503ec984/lessons/6c738150-6af4-4c12-a21d-8bc6ea55d72e/concepts/2c274f44-03a7-453a-ac06-95eaef2998cc

**Comment by kylesf** [comment]
Fixed. Thanks
