### ISSUE TITLE
crl Introduction to Controls L01E09

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#599]
Typo?
I can read "and see its affects" should be "and see its effects" 

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/fc3e1236-996e-4fb8-b317-479ce23c0e1d/modules/95f92697-f568-4063-b6d4-b134503ec984/lessons/6c738150-6af4-4c12-a21d-8bc6ea55d72e/concepts/75568c90-12b7-4e18-a21a-d30a81086ead

**Comment by kylesf** [comment]
Got it thanks
