### ISSUE TITLE
arek - misspelling in controls lab README

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#600]
arek - 2 misspellings in controls lab README

1. The word "paramters" should be "parameters" in the following sentence:

"Luckily, you've likely found some pretty decent PID paramters in your previous exploration"

2. The word "Dissalow" should be "Disallow: in the following sentence:

"Example: Dissalow movement along the quad's X axis"

**Comment by kylesf** [comment]
Fixed, thanks!
