### ISSUE TITLE
arek - "Override" in controls README refers to vm or host?

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#602]
arek - "Override" in controls README refers to vm or host?

In controls README at the bottom there is an instruction to "set Override" to true in ros_settings.txt

But in ros_settings.txt there are 2 options regarding override: "vm-override" and "host-override" which one the instructions refer to?

Please see the attached screenshot of the contents of ros_settings.txt showing 2 options not referred to in the instructions.

<img width="338" alt="screen shot 2017-08-15 at 12 20 29" src="https://user-images.githubusercontent.com/28066540/29325152-b84a7efa-81b4-11e7-81a9-8e9dcc75901d.png">

**Comment by kylesf** [comment]
Thanks, I have updated README.
