### ISSUE TITLE
crl Introduction of Controls: L01E14

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#608]
The text do mention of knobs but I dont see any in the lesson

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/fc3e1236-996e-4fb8-b317-479ce23c0e1d/modules/95f92697-f568-4063-b6d4-b134503ec984/lessons/6c738150-6af4-4c12-a21d-8bc6ea55d72e/concepts/f86df59e-a793-4624-97ed-b7f2aecee4c7

**Comment by kylesf** [comment]
Made it more clear. Thanks! The knobs are just another term for Kp, Ki and Kd.
