### ISSUE TITLE
Quadrotor Control using PID - Completing PID Controller: Wrong link

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#614]
This section contains a link to a [previous lesson](https://coco.udacity.com/nanodegrees/nd209-beta/locale/en-us/versions/1.0.0/parts/341269/modules/341270/lessons/341463/concepts/341472#). The link actually points to a content creator page that you probably want to keep secret! ;)

**Comment by thomas-at-em** [comment]
Thanks! I think I fixed it. Please try again.

**Comment by alvarovillena** [comment]
Working as expected now :)
