### ISSUE TITLE
arek - misspelling in Lesson 4: Clustering for Segmentation - Section 5. K-means Playground

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#615]
arek - misspelling in Lesson 4: Clustering for Segmentation - Section 5. K-means Playground

There is word "learn" missing in the following sentence:

"Have a look at the functions in the np.random package to how these functions work"

should be:

"Have a look at the functions in the np.random package to learn how these functions work"

**Comment by sahiljuneja** [comment]
Fixed. Thanks!
