### ISSUE TITLE
arek - misspelling in Lesson 4: Clustering for Segmentation - Section 13. Cluster Visualization

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#617]
arek - misspelling in Lesson 4: Clustering for Segmentation - Section 13. Cluster Visualization

There's an apostrophe and "s" missing :

"let" should be "let's" in the following sentence:

create one final point cloud, let call it "cluster_cloud"

**Comment by kylesf** [comment]
Super, thanks!
