### ISSUE TITLE
arek - 3D Perception Project - writeup_template.md

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#621]
arek - 3D Perception Project - writeup_template.md

There's erroneous 4x4 grid containing bigus values like "highlight", "bold" and "italic" right below the image of the robot.

Here's the screenshot of the 4x4 table grid that needs to be deleted from writeup_template.md

![screen shot 2017-08-18 at 02 17 35](https://user-images.githubusercontent.com/28066540/29446755-e0f49e72-83bb-11e7-9a2d-c71b4b4969fd.png)

**Comment by kylesf** [comment]
Removed.
