### ISSUE TITLE
arek - misspelling in Project 3 - Perception rubric

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#622]
arek - misspelling in Project 3 - Perception rubric - Section - Exercise 1, 2 and 3 pipeline implemented.

There are total of 3 issues described below:

in sentence:

"Exercise 1, 2 and 3 pipeline implemented."

There is an unnecessary dot at the end of the above heading and below that heading unnecessary doubled word "within" in the sentence:

"the pcl_callback() function within within the template Python script"

The third issue is that the first word "the" in the above sentence should be capitalized.

**Comment by kylesf** [comment]
Thanks! Fixed!
