### ISSUE TITLE
Building a PI Controller

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#625]
in the final quiz of this topic the working match is 

de,in,in,de,deg :de = decrease , in = increase deg = degrade . 
not sure on how the steady state erro decreases with the increase with the ki as i can see ki = 0.5 the error visually increases

**Comment by kylesf** [comment]
Mathematically an increase of Ki with decrease the steady state error. Granted there is a limited range in which this is applicable.
