### ISSUE TITLE
crl TensorFlow L02E05

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#627]
Typo. The URL to install is missing the last letter 'l'. It should be whl

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/4405411f-bdc8-43fb-9e2b-b4b98a61c760/modules/375d6b1e-b31a-4d2e-b33a-996167faf77e/lessons/a4a80417-00cb-4a9c-8cc4-3a091414baa2/concepts/b4b04f6b-ed58-483b-acc7-3e5628ed9478

**Comment by sahiljuneja** [comment]
Fixed, thanks!
