### ISSUE TITLE
Minior - TF installation, environment name change?

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#629]
Suggestion
Hi, the instructions indicates to create a new environment RoboND. 
I have already created that environment, I assume I used it for Search and Sample return project. 
Maybe it's better to ask to create a RoboND-TF environment as name. 
In DLND they creates a new one.

**Comment by sahiljuneja** [comment]
Thanks! We might continue with the same environment for both and have TF installed on top of that for the students who would like to. So I will update instructions to reflect that.

**Comment by sahiljuneja** [comment]
Updated instructions to use the same environment.
