### ISSUE TITLE
crl Convolutional NN L04E11

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#637]
When I run the code in this page, I am getting conv shape = [ ?, 16, 16, 20] , I mean, my first field is None when in the lesson is 1.

At end of page I see 'SAME' vs 'PADDING'. I am guessing if should be 'SAME' vs 'VALID'

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/4405411f-bdc8-43fb-9e2b-b4b98a61c760/modules/375d6b1e-b31a-4d2e-b33a-996167faf77e/lessons/dca6b1cd-5d40-41ab-a502-69a24c4b227e/concepts/d0db3cab-ad70-46ec-9614-4dfc27dfc865

**Comment by thomas-at-em** [comment]
That is correct. Thanks for reporting that.
