### ISSUE TITLE
arek - p4 Follow Me - Github repo TODO

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#638]
In the README here:

https://github.com/udacity/RoboND-DeepLearning

Is the following TODO for students or a reminder for content developers to add content? Please see screenshot attached.

Also "preprocesing" in "To run preprocesing" is misspelled below:

Image Preprocessing

Before the network is trained, the images first need to be undergo a preprocessing step. TODO: Explain what preprocessing does, approximately. To run preprocesing:

![screen shot 2017-09-16 at 18 35 32](https://user-images.githubusercontent.com/28066540/30516500-1433539a-9b0f-11e7-8b2f-7423f2638db8.png)

**Comment by kylesf** [comment]
In this case TODO is for content developers.  And thanks for the spelling fix. We will be rolling out a large update for you guys shortly.
