### ISSUE TITLE
Follow Me - Configuration AWS - AMI not available

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#639]
The instruction says that the AWS AMI is available in the following locations:

Note: The AMI is available in the following regions: Oregon, North Virginia, Frankfurt, South America, Tokyo, Ohio, Seoul and Sydney. 

But, I have only found it in Oregon. The rest is missing.

Link to lesson: https://classroom.udacity.com/nanodegrees/nd209-beta/parts/4405411f-bdc8-43fb-9e2b-b4b98a61c760/modules/375d6b1e-b31a-4d2e-b33a-996167faf77e/lessons/197a058e-44f6-47df-8229-0ce633e0a2d0/concepts/27c73209-5d7b-4284-8315-c0e07a7cd87f

**Comment by kylesf** [comment]
Thanks, I have updated those so they are now public. Let me know if you can see them now!
