### ISSUE TITLE
Project implementation: feelings of a student

### ISSUE THREAD

**Issue by yannrs** [udacity/robotics-beta-test-issues#646]
With the point of view of a student, all functions preimplemented are very fuzzy, as there are few comments, and they didn't implemented neither of them.
I would advise to let students implement some parts of these fonctions, with some strong guidiance
The fuzziest is the SeparableConv2DKeras.

**Comment by yannrs** [comment]
I didn't saw the new part on the lesson semantic segmentation, which solve my worries

**Comment by yannrs** [comment]
Lesson6, 8.Lab: Encoder: I would recommend to add a figure which illustrate the steps use with the separavbleConv2D compared to commonly used conv2D.
With a visual point of view it should be clearer for a wider range of students

**Comment by kylesf** [comment]
Good idea! Will add it to back log

**Comment by kylesf** [comment]
@sahiljuneja Thoughts on this?
