### ISSUE TITLE
Project: Follow Me project -> link to github is not working anymore

### ISSUE THREAD

**Issue by yannrs** [udacity/robotics-beta-test-issues#648]

**Comment by kylesf** [comment]
Where do you specifically see this?

**Comment by yannrs** [comment]
From 
Lesson Project Follow Me Project => 9.Project;  Follow Me Project 
: https://classroom.udacity.com/nanodegrees/nd209-beta/parts/4405411f-bdc8-43fb-9e2b-b4b98a61c760/modules/375d6b1e-b31a-4d2e-b33a-996167faf77e/lessons/197a058e-44f6-47df-8229-0ce633e0a2d0/project

Also why using 2 times the word "project" on these titles ?

**Comment by kylesf** [comment]
Fixed the project wording and links will be in there shortly!
