### ISSUE TITLE
Project Follow me: overlay_viz crash -> pred_viz ?

### ISSUE THREAD

**Issue by yannrs** [udacity/robotics-beta-test-issues#651]
When I try to use the overlay_viz parameter, I get 

(tensorflow11) C:\Users\yann\deepcars-master\RoboND\Project 4 - Follow Me\RoboND-DeepLearning\code>python realtime_follower.py save_modelweights.h5 --overlay_viz
usage: realtime_follower.py [-h] [--pred_viz] [--pred_images PRED_IMAGES]
                            model_file
realtime_follower.py: error: unrecognized arguments: --overlay_viz

**Comment by kylesf** [comment]
Sorry you may need to check out the python code to see if the naming for that argument is different. We have changed it in the current version. We will have lots of updates out soon. 

I believe you want to try `--pred_viz` as the argument.
