### ISSUE TITLE
error with RoboND-segmentation-Lab

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#652]
under network definition
model = keras.models.Model(inputs=inputs, outputs=out_layer)

[1:18] 
should be

[1:19] 
model = models.Model(inputs=inputs, outputs=out_layer)

[1:19] 
because we have imported models from keras

from tensorflow.contrib.keras.python.keras import models

**Comment by sahiljuneja** [comment]
Does this throw an error or just that it's redundant to use keras.models.Model instead of models.Model?

**Comment by yuvaramsingh94** [comment]
it was confusing and it does not throw any error because we have imported keras previously

**Comment by sahiljuneja** [comment]
Got it. Thanks. Fixed!
