### ISSUE TITLE
Lab Segmentation: Typo weight_filename != weight_file_name

### ISSUE THREAD

**Issue by yannrs** [udacity/robotics-beta-test-issues#656]

**Comment by yannrs** [comment]
If it's not a typo, maybe it would be nice to create this second variable

**Comment by kylesf** [comment]
Where is this? Are you finding this in the current https://github.com/udacity/RoboND-Segmentation-Lab?

**Comment by yannrs** [comment]
It's on the file /blob/master/code/segmentation_lab.ipynb

Before "Prediction"
# Save your trained model weights
weight_file_name = 'model_weights'

After "Prediction"
# model = load_weights(model, weight_filename)

**Comment by sahiljuneja** [comment]
Fixed, thanks!
