### ISSUE TITLE
arek - 11. Deep Learning for Robotics - Lesson 6: Semantic Segmentation - part 6. Lab: Getting Started

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#658]
arek - 11. Deep Learning for Robotics - Lesson 6: Semantic Segmentation - part 6. Lab: Getting Started

In the text there is a reference to `student_notebook.ipynb` but such file doesn't exist in the repo. Please see screenshot attached:

This paragraph needs to be fixed:

"The Jupyter interface will open in your browser. You can then access the cloned repo and the Jupyter Notebook from there. We are specifically working with the student_notebook.ipynb which can be found in following path code/segmentation_lab.ipynb."

![screen shot 2017-09-26 at 13 41 39](https://user-images.githubusercontent.com/28066540/30875404-6be2cf30-a2c1-11e7-9ef5-385f4238d0bd.png)

**Comment by sahiljuneja** [comment]
Fixed. Thanks!
