### ISSUE TITLE
shreeyak - DNN Lab notebook

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#660]
There is a section of code that gives me an error. Also a typo:
```
# TODO: Set the list of weights and biases tensors based on number of layers
weights = []
biases = []

### DON'T MODIFY ANYTHING BELOW ###
from tensorflow.python.ops.variables import Variable

assert features._op.name.startswith('Placeholder'), 'features must be a placeholder'
assert labels._op.name.startswith('Placeholder'), 'labels must be a placeholder'
assert all(isinstance(weight, Variable) for weight in weights), 'weights must be a TensorFlow variable'
assert all(isinstance(bias, Variable) for bias in biases), 'biases must be a TensorFlow variable'
```

In the assertion, `isinstance(weight` should be `isinstance(weights`.  `isinstance(bias` should be `isinstance(biases`

And the for loop is giving me an Error: `'bool' object is not iterable` or `TypeError: 'Variable' object is not iterable`
So `assert all(isinstance(weight, Variable) for weight in weights)` should be `assert isinstance(weights, Variable)`, just like it is in the NN-Lab notebook.

**Comment by kylesf** [comment]
@sahiljuneja Is this done or need to be looked in too?
