### ISSUE TITLE
AWS - jupyter connection failed

### ISSUE THREAD

**Issue by yannrs** [udacity/robotics-beta-test-issues#661]
I'm able to connect to the VM, upload files.
But when I run :
jupyter notebook --ip='*' --port=8888 --no-browser

I can't access to the notebook: ERR_CONNECTION_TIMED_OUT

Is it because I'm from Europe, and the VM is hosted in North Virgina ? The AMI is not available in Ireland, this is why I did that.

**Comment by kylesf** [comment]
Please use your local host machine and not the VM

**Comment by kylesf** [comment]
Sorry, I may have misread. I have added Ireland. Let me know if you are still having issues.
