### ISSUE TITLE
arek - Part 2: Setting up your AWS Instance

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#662]
arek - Part 2: Setting up your AWS Instance

There are backticks and "sh" around the terminal command as you can see on the following screenshot. They need to be removed (should not be visible)

![screen shot 2017-09-27 at 18 06 20](https://user-images.githubusercontent.com/28066540/30940406-ffce3cfa-a3ae-11e7-8022-505e487b7b94.png)

**Comment by kylesf** [comment]
Thanks, fixed!
