### ISSUE TITLE
Project Follow Me - github: Link to download the dataset isn't working anymore

### ISSUE THREAD

**Issue by yannrs** [udacity/robotics-beta-test-issues#664]
The link for the training and validation dataset give this error:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>Deep Learning Data/train.zip</Key>
<RequestId>AEB1BFB33A80A48F</RequestId>
<HostId>
bVgh9ZMxb2fhGYqVoXEyd8FJpBjVWWilUC5OaDiYP/x0yCgWMmnmAzWFUvoPajYQ93Y8e3k/W2M=
</HostId>
</Error>

**Comment by kylesf** [comment]
Please check again.

**Comment by danzelmo** [comment]
has been fixed
