### ISSUE TITLE
arek - 4 misspellings in Project Follow Me - 5. Collecting your Data

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#671]
arek - misspelling in Project Follow Me - 5. Collecting your Data

In the following passage there are 4 misspellings:

1. The words "above in this" should be removed from "provided above in this respository" and instead should be "provided in this project's repository"

2. "you're" should be removed and instead "your" should be added in "you're segmentation"

3. "you may be interested in collecting" should be replaced with "you may want to collect" because the word "interested" is already repeated at the beginning of this sentence.

4. "To do, please" should be replaced with "To do it, please"

A simple training dataset has been provided above in this repository. This dataset will allow you to verify that you're segmentation network is semi-functional. However, if you're interested in improving your score, you may be interested in collecting additional training data. To do, please see the following steps.

**Comment by kylesf** [comment]
Fixed thanks!
