### ISSUE TITLE
shreeyak - segmentation lab - conv2d_batchnorm() param error

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#673]
```
def conv2d_batchnorm(input_layer, filters, kernel_size=3, strides=1):
    output_layer = layers.Conv2D(filters=filters, kernel_size=kernel_size, strides=1, 
                      padding='same', activation='relu')(input_layer)
    
    output_layer = layers.BatchNormalization()(output_layer) 
    return output_layer
```
In the code above, parameter strides=1 is redundant and never gets used. if you see inside the function `output_layer = layers.Conv2D(filters=filters, kernel_size=kernel_size, strides=1` meaning that strides will always be = 1 and never equal to the input passed. Either the param must be removed or this line should be corrected.

Hence:
`output_layer = layers.Conv2D(filters=filters, kernel_size=kernel_size, strides=1`
should be
`output_layer = layers.Conv2D(filters=filters, kernel_size=kernel_size, strides=strides`

**Comment by danzelmo** [comment]
this has been fixed, in the lab.
