### ISSUE TITLE
shreeyak - seglab - prediction steps broken

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#677]
So running `gt_folder, pred_foldr = model_tools.write_predictions_grade_set(model,run_number,'validation')` gives me an error:  
```
TypeError                                 Traceback (most recent call last)
<ipython-input-24-c4320e95393d> in <module>()
      1 # generate predictions, save in the runs, directory.
      2 run_number = 'run1'
----> 3 gt_folder, pred_foldr = model_tools.write_predictions_grade_set(model,run_number,'validation')

TypeError: write_predictions_grade_set() missing 1 required positional argument: 'grading_dir_name'
```

Tried going through the code, but can't get it.

**Comment by Shreeyak** [comment]
Also look at the last cell `scoring_utils.score_run(validation_path, output_path)`. There is no variable called validation_path.

It's like there's been a huge mix up when releasing this. Please test the code before publishing this again. I'd request you to make the var names a bit more clear as well. I have no idea what `gt_folder` could represent.

**Comment by danzelmo** [comment]
Updated write_predictions_grade_set, you can close the issue if its fixed.

**Comment by kylesf** [comment]
@Shreeyak Is the error resolved?

**Comment by danzelmo** [comment]
This issue has been fixed in segmentation repo
