### ISSUE TITLE
shreeyak - project follow me - some folders not explained

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#678]
```
...
data/validation/masks - contains masked (labeled) images for the validation set
data/weights - contains trained TensorFlow models
data/raw_sim_data/train/run1
data/raw_sim_data/validation/run1
```
The explanations for the last two folders are missing.

**Comment by kylesf** [comment]
Please recheck this concept and let me know if further explanation is needed: https://classroom.udacity.com/nanodegrees/nd209/parts/09664d24-bdec-4e64-897a-d0f55e177f09/modules/cac27683-d5f4-40b4-82ce-d708de8f5373/lessons/197a058e-44f6-47df-8229-0ce633e0a2d0/concepts/209307be-a6df-4cb0-b5a9-06b5e375373d?contentVersion=1.0.0&contentLocale=en-us
