### ISSUE TITLE
shreeyak - project follow me: the depth image should have a black background

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#679]
In the sim, can't make out the output of the depth camera at all. Most of it is transparent. Can make out its the depth output only in the first few seconds of launching it. Will be much better if a black background can be added. Can visualize the depth camera.

**Comment by Shreeyak** [comment]
Can see the depthcam output here:
![quadsim2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58fb6dd0cc6965001a9640ba/125516c66e82c728ace21e0d46f9819b27918aa4ddabf301b44fff9e2c4533317346f67374dcba2bbb177d52095d4ea441585b15f4fada78f5b22e6c981e5ab38532022d8c6853beb2901eb70bbb258b4983bfb98c4fc2ed3c2df5c6.png)

After first few seconds, it is focused on nearby objects and output not visible due to transparency.
![quadsim3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58fb6dd0cc6965001a9640ba/125516c66e82c728ace21e0d46f9819b27918aa4dcabf301b44fff9e2c4533317346f67374dcba2bbb177d52095d4ea441585b15f4fada78f5b22e6c981e5ab38532022d8c6853beb2901eb80bbb258b4983bfb98c4fc8e83421f5c6.png)

**Comment by demi180** [comment]
Good catch. Fix should be coming either today or Monday.

**Comment by kylesf** [comment]
@danzelmo Whats the status with this?
