### ISSUE TITLE
shreeyak - project follow me: scroll in window causes sim to zoom

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#680]
When selecting the folder to save records in, scrolling causes the simulator in the background to zoom in/out.

**Comment by Shreeyak** [comment]
![quadsim4.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58fb6dd0cc6965001a9640ba/125516c66e82c728ace21e0d46f9819b27918aa4dbabf301b44fff9e2c4533317346f67374dcba2bbb177d52095d4ea441585b15f4fada78f5b22e6c981e5ab38532022d8c6853beb2901eb80bbb258b4983bfba824ec4ea3425f5c6.png)

**Comment by demi180** [comment]
Fix coming today or by Monday.
