### ISSUE TITLE
shreeyak - project follow me - RMB doesnt always work in sim

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#681]
In the sim, clicking right mouse button doesn't always reset the camera. I need to click double/triple click to reset. After this, sometimes a single click will reset the view. Very inconsistent behavior.

My system specs: Ubuntu 16.04, i7 cpu, gtx 1060 gpu.

**Comment by kylesf** [comment]
@danzelmo Whats the status with this?
