### ISSUE TITLE
shreeyak - segmentation lab - resources not released

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#682]
Once I run the notebook to train/run the model, a tensorflow object is created which takes up 90% of the GPU ram. After running all the cells, it is not released.
The code should release it automatically after training and also after prediction. Or provide a cell to do so. Currently I need to restart the kernel every time to make it release my GPU.

**Comment by danzelmo** [comment]
This is a known issue with tensorflow and jupyter notebooks. I still have to restart notebooks myself. Closing.
