### ISSUE TITLE
arek - misspelling in Project Follow Me - Segment 5. Collecting your Data

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#683]
arek - 3 misspelling in Project Follow Me - Segment 5. Collecting your Data

This ticket is about 3 misspellings.

There are 2 things in this sentence:  "However, if your interested in improving your score,you may want to collect"

1. your should be you're 
2. there should be space in "score,you"

And the third is in this sentence: "Before the network is trained, the images first need to be undergo a preprocessing"

The word "be" should be deleted.

**Comment by kylesf** [comment]
Fixed, thanks!
