### ISSUE TITLE
Follow me simulator v1.2.1

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#686]
the quad is following mode has a small bug in the simulator (V1.2.1) . this mode toggles back to patrolling mode within few seconds without mouse key press 
After activating this mode it follows the hero for few seconds and then toggles back to patrolling mode

**Comment by yuvaramsingh94** [comment]
i am using the windows version

**Comment by danzelmo** [comment]
I have noticed this bug as well. @demi180 will be able to fix this on monday

to get around the issue press `9` to speed up data collection, then spam the middle mouse button:)

**Comment by demi180** [comment]
I think we know why it's happening, we should have a fix out today

**Comment by kylesf** [comment]
@danzelmo Whats the status with this?
