### ISSUE TITLE
shreeyak - seglab and project4 - add tensorboard

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#688]
We can use tensorboard to visualize our plots and it takes just 1 line to be changed.

```
#logger_cb = plotting_tools.LoggerPlotter()
logger_cb = keras.callbacks.TensorBoard(log_dir='./logs2', histogram_freq=0, batch_size=32, write_graph=True, write_grads=False, write_images=False, embeddings_freq=0, embeddings_layer_names=None, embeddings_metadata=None)
```

**Comment by Shreeyak** [comment]
Here it is working successfully on my machine:
![devin1](https://user-images.githubusercontent.com/12800185/31048744-7ca55558-a641-11e7-96f5-e5ab8e8b1c24.png)

**Comment by Shreeyak** [comment]
Doc here: https://keras.io/callbacks/#tensorboard

**Comment by sahiljuneja** [comment]
Thanks. Currently, there are no plans to add tensorboard because that might require additional content as well. I will add this to the backlog for a later consideration.
