### ISSUE TITLE
shreeyak - seglab and project4 - add model checkpoints

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#689]
Add model checkpoints via callbacks to the model. By doing this, if the model ends up overfitting, we can simply take one of the intermediate results from one of the checkpoints saved.

Here is the implementation:  
```
save_cb = keras.callbacks.ModelCheckpoint(filepath='./saved_chkpts/model1/weights.{epoch:02d}-{val_loss:.2f}.hdf5', verbose=1, period=5)

callbacks = [logger_cb, save_cb]
```

Here is the doc: https://keras.io/callbacks/#example-model-checkpoints

**Comment by Shreeyak** [comment]
Might be easier to resume training from a checkpoint. Please add this feature.

**Comment by kylesf** [comment]
@danzelmo Thoughts?
