### ISSUE TITLE
crl preprocess_ims.py

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#691]
I found 2 issues when running this python script
1. line 107, the new_frame variable created has an additional underscore (_). So, I replaced '_mask' by 'mask'
2. line 109, is failing and creating a dir_base empty variable. It works on Linux but on Windows need test the inverted backslash. So, I replaced by

sep = '/'
if i.find('\\'):
    sep = '\\'    # for Windows
dir_base = str(os.sep).join(i.split(sep)[:-1])

**Comment by danzelmo** [comment]
Thanks for pointing these out. Sorry about the separator, I thought one loose backslash had crept in there somewhere. I will replace with os.sep, which handles this smoothly. The update is up now.
