### ISSUE TITLE
AWS instructions for Mac and Linux

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#693]
AWS configuration instructions only work on Mac and Linux. What about Windows users?
Link: https://classroom.udacity.com/nanodegrees/nd209-beta/parts/4405411f-bdc8-43fb-9e2b-b4b98a61c760/modules/375d6b1e-b31a-4d2e-b33a-996167faf77e/lessons/197a058e-44f6-47df-8229-0ce633e0a2d0/concepts/27c73209-5d7b-4284-8315-c0e07a7cd87f

![image](https://user-images.githubusercontent.com/9123307/31059472-1c57dae8-a6d9-11e7-983e-a355eadcedb6.png)

**Comment by kylesf** [comment]
@sahiljuneja Is this something we should add to classroom?
