### ISSUE TITLE
qiang: Typo in Segmentation Lab

### ISSUE THREAD

**Issue by luqiang21** [udacity/robotics-beta-test-issues#694]
In the second paragraph,

Intead should Instead

**Comment by sahiljuneja** [comment]
Hey, could you please specify where exactly this is? Which section in the Semantic Segmentation lesson?

**Comment by luqiang21** [comment]
Oh, sorry, it is in the jupyter notebook.

**Comment by kylesf** [comment]
@sahiljuneja Status on this?
