### ISSUE TITLE
shreeyak - project follow me - naming error in model_training notebook

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#695]
Loading the model is done as:
```
restored_model = model_tools.load_network(weight_file_name)
```

The later lines of code expect the model to be named as `model` and give error `restored_model` not found. This line should be modified:

```
restored_model = model_tools.load_network(weight_file_name)
model = restored_model
```

**Comment by kylesf** [comment]
@sahiljuneja Status on this?
