### ISSUE TITLE
crl Kinematics Demo L1, L2

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#696]
I don't know how this works but in my browser nothing is functional. E.g., 
1. In rotations, I see a button and its html code and when I click on button, nothing happens. 
2. In HTML lesson, I only see a screenshot that is well designed.

**Comment by kylesf** [comment]
Did you run the code block and then hit the button? HTML lesson is just a design preview.

**Comment by zenetio** [comment]
Cool! It is working.
I suggest a highlight indication or so of what axis line is being executed (feedback interaction).

**Comment by kylesf** [comment]
Its going to launch in the classroom with no notebook soon. Hence the HTML preview.
