### ISSUE TITLE
arek - 3 misspellings in Rubric for Follow Me Deep Learning project

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#697]
arek - 3 misspelling in Rubric for Follow Me Deep Learning project

1. First misspelling:

In the following sentence: 

"The student is demonstrates a clear understanding of 1 by 1 convolutions"

please delete the word "is".

2. Second misspelling:

Im the sentence:

"The student can demonstrate the benefits and/or drawbacks different network architectures pertaining to this project and "

there should be the word "of" added after the word "drawbacks".

3. Here there are additional 2 misspellings:

In the sentence: "It is important that the student know how hyper tuning this parameters impacts the overall network (and system)."

The word  "know" should be "knows" and the word "this" should be "these" .

**Comment by kylesf** [comment]
Fixed, thanks!
