### ISSUE TITLE
shreeyak - segmentation lab - typo in utils?

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#698]
plotting_tools.py -> get_im_file_sample:

```
masks = np.array(get_mask_files(path, subset_name))
```

should be:
```
masks = np.array(get_pred_files(pred_run_name))
```

**Comment by danzelmo** [comment]
What happens now is that the predictions are ignored and only the images, and labels are displayed. I am not sure `get_pred_files` would work as it is set up for the project. Having the predictions shown in the lab is an improvement that should be added eventually.

**Comment by kylesf** [comment]
@danzelmo Whats the status with this?
