### ISSUE TITLE
letyrodri: FollowMe QuadSim E/Q keys not in instructions

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#700]
In the following instructions:
https://classroom.udacity.com/nanodegrees/nd209-beta/parts/4405411f-bdc8-43fb-9e2b-b4b98a61c760/modules/375d6b1e-b31a-4d2e-b33a-996167faf77e/lessons/197a058e-44f6-47df-8229-0ce633e0a2d0/concepts/18f7a89e-7829-478c-998a-fb154e49dbcc

E and Q keys steer the quadrotor but are not in instructions.

**Comment by karimchamaa** [comment]
@sahiljuneja Should I add:"E/Q: Rotate the quad clockwise and counterclockwise respectively"?

**Comment by sahiljuneja** [comment]
Missed this ticket. Thanks for the reminder @karimchamaa ! I have updated this in the Classroom.
