### ISSUE TITLE
arek - Project Follow Me Deep Learning instructions

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#701]
arek - Project Follow Me Deep Learning instructions still say that the final score needs to be above 0.45 - this needs to be changed to 0.40, please see screenshot below:

![screen shot 2017-10-16 at 21 19 20](https://user-images.githubusercontent.com/28066540/31642204-ba19056a-b2b7-11e7-85e3-4e37af26c5ca.png)

**Comment by sahiljuneja** [comment]
Fixed. Thanks!
