### ISSUE TITLE
abhi - Intro to C++ for Robotics - Ubuntu Setup

### ISSUE THREAD

**Issue by abhiojha8** [udacity/robotics-beta-test-issues#702]

**Comment by abhiojha8** [comment]
A link below the video that points to the setup instructions will be helpful.

**Comment by sahiljuneja** [comment]
There's already a link there. Is that not accessible or visible?

**Comment by abhiojha8** [comment]
Got it! Looked like a heading so I didn't notice.

**Comment by karimchamaa** [comment]
I will update it and move it to the body part since you couldn't find it easily.
