### ISSUE TITLE
C++ lesson 9 Quiz 2 `error`

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-beta-test-issues#703]
C++ lesson 9 quiz 2 states that `error` should be the correct answer due to the access modifier. However the access modifier is `public` so that doesn't make sense. I'm guessing the code was meant to use `private` instead?

**Comment by delvingdeep** [comment]
I noticed the same issue. The code should meant `private` for quiz answer to be correct.

**Comment by karimchamaa** [comment]
Yes sorry, I meant `private` and updated it now in the classroom. Thanks for noticing.
