### ISSUE TITLE
C++ lesson 8 quizzes

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-beta-test-issues#704]
Lesson 8 quizzes ask what would happen after a certain statement was compiled and run. Sorry if I'm being too picky, but if you just tried to compile those bits of code nothing would get printed as it's missing all the surround C++ structures required to compile and run correctly. I understand that's not the point of this quiz, but perhaps the wording could be changed a little to prevent confusion on this point?

**Comment by karimchamaa** [comment]
You are right, I added the missing C++ structures so students can get used to it!
![Screen Shot 2017-10-18 at 11.10.34 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8729d5c976a0011ad845d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455fb6b7191a379ee0c2a51415c4abc30254d58eeb9cb74fce36f34985619e8d939567d956914fabbd41dbf09ba208f1e8db5efd91fc4fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34be94e50a4173660e475316e0a.png)
