### ISSUE TITLE
letyrodri: openCV link missing

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#707]
This is the official documentation of OpenCV where you can discover all the functions supported.
https://classroom.udacity.com/nanodegrees/nd209-beta/parts/1e37243c-6a40-45ff-bcc0-876e7e6ea03e/modules/89cdf9e1-8a98-4da9-b756-4ff2c3182f54/lessons/a8c217f8-6604-44e6-9ad6-b591ad6c57fe/concepts/b833066e-5fcd-4660-938a-7477d1ccc846

**Comment by karimchamaa** [comment]
Link is connected to the tile. But I will update it and move it to the body part since I got more than 1 review regarding a missing link.
