### ISSUE TITLE
abhi - Rover Control

### ISSUE THREAD

**Issue by abhiojha8** [udacity/robotics-beta-test-issues#708]

**Comment by abhiojha8** [comment]
Is there any simulator for native Ubuntu? I am not sure if there is one yet. If it is, we can include it.

**Comment by karimchamaa** [comment]
Yes, I will include a Linux build!

**Comment by karimchamaa** [comment]
![Screen Shot 2017-10-18 at 10.46.15 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8729d5c976a0011ad845d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455fb6b7191a379ef0c2f57415e4bbc30254d58eeb9cb74fce36f34985619e8d939567d956914fabbd41dbf09ba208f1e8db5efd91fc4fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34be94e51ac1b3563e57f3f6e0a.png)
