### ISSUE TITLE
C++ Lesson 13 - ROS Nodes

### ISSUE THREAD

**Issue by adammalpass** [udacity/robotics-beta-test-issues#709]
I cloned the simple_arm_c package as requested. However when doing the catkin_make I get the error "Multiple packages found with the same name `simple_arm`". This is because we also had a simple_arm in term 1. Might be better to rename the new package as simple_arm_c too, to avoid confusion.

**Comment by karimchamaa** [comment]
Sure, will update it!

**Comment by karimchamaa** [comment]
Thanks for reporting this issue. Package is now renamed to simple_arm_c
