### ISSUE TITLE
[Intro C++][8. Functions and Data Structures]  Do all students know modulo ?

### ISSUE THREAD

**Issue by yannrs** [udacity/robotics-beta-test-issues#715]
Silly question: Can we assume that the every student known what's a modulo ?

**Comment by karimchamaa** [comment]
Yes because students already know at least one programming language and worked with python in Term 1! Also, this lesson is just a review of the main C++ concepts. Before watching it, students should take the Udacity in-depth C++ course and Sololearn C++ tutorial.
