### ISSUE TITLE
[Intro C++][11.] Suggestion - Add a quiz with pointer operations

### ISSUE THREAD

**Issue by yannrs** [udacity/robotics-beta-test-issues#718]
Add a quiz, where you can ask the student what will be the output when the input is x+&y, where x and y were defined before

**Comment by karimchamaa** [comment]
You mean something like: 
int x=3;
int y=6;
cout << x+&y;
This will give a HEX answer that students will not be able to identify, right?

**Comment by yannrs** [comment]
Yes for example

But I also meant something like :
   int  var = 20;   // actual variable declaration.
   int  *ip;        // pointer variable 

   ip = &var;       // store address of var in pointer variable

   cout << var << endl;
   cout << ip << endl;
   cout << *ip << endl;

   var ++;

   cout << var << endl;
   cout << ip << endl;
   cout << *ip << endl;

**Comment by karimchamaa** [comment]
Added something similar which is pointer reference to an operation. Thanks for suggesting!
