### ISSUE TITLE
[Intro C++][12. External Libraries] Suggestion - download image

### ISSUE THREAD

**Issue by yannrs** [udacity/robotics-beta-test-issues#719]
Modify the link to udacity image, to a start download link
Or add the code to download the image into the VM:
wget https://s3-us-west-1.amazonaws.com/udacity-robotics/Term+2+Prep/Udacity.png

**Comment by karimchamaa** [comment]
Modified the Metadata of the image on AWS to downloadable. Please, clear your cache and cookies on Chrome if you are testing. Should've thought of "wget" before making the video. Thanks for suggesting!
