### ISSUE TITLE
map to world coordinates quiz

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#72]
In map to world coordinate quiz, the figures on top do not correspond to the figures generated by the code. as a result, there is potential for confusion. Will be nice to make points so that the examples match the figure shown above. also, will be nice to overlay points on the map. This can be fixed by giving a fixed x_rover,y_rover and yaw_rover, and adding figure on top of a map.

**Comment by vxy10** [comment]
vivek1108, forgot to put id.

**Comment by ryan-keenan** [comment]
Thanks Vivek, this is fixed now ;)
