### ISSUE TITLE
[Intro C++][13. ROS Nodes] Suggestions - content

### ISSUE THREAD

**Issue by yannrs** [udacity/robotics-beta-test-issues#720]
Block the auto go to the next section

Explain what means '::'

**Comment by karimchamaa** [comment]
1- Unlocked the auto go
2- Scope resolution operator is now explained: https://classroom.udacity.com/nanodegrees/nd209-beta/parts/1e37243c-6a40-45ff-bcc0-876e7e6ea03e/modules/89cdf9e1-8a98-4da9-b756-4ff2c3182f54/lessons/a8c217f8-6604-44e6-9ad6-b591ad6c57fe/concepts/36925bdd-c7f2-499e-8ed6-ec424bb00847
