### ISSUE TITLE
arek - Kinematics - Lesson 2: Forward and Inverse Kinematics - 7. Composition of Rotations

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#722]
arek - Kinematics - Lesson 2: Forward and Inverse Kinematics - 7. Composition of Rotations

Both of the coding Quizzes have the same solution in the solution tab even though the top quiz talks about YZ intrinsic rotation and the bottom one talks about ZY extrinsic rotation. Please see screenshot attached below.
![screen shot 2017-11-02 at 17 40 53](https://user-images.githubusercontent.com/28066540/32351894-5865d2b2-bff5-11e7-88b3-d3f2fb35a2fd.png)

**Comment by kylesf** [comment]
They may look the same but they are not they are the correct answers. Updated the print output to so it looks better.
