### ISSUE TITLE
shreeyak - kinematics - L02E07 - diagram wrong

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#727]
In the video, one frame does not have the y2 drawn in red. Here is the lesson URL:
https://classroom.udacity.com/nanodegrees/nd209-beta/parts/72800973-80cd-4828-81fd-b3390486892b/modules/8855de3f-2897-46c3-a805-628b5ecf045b/lessons/87c52cd9-09ba-4414-bc30-24ae18277d24/concepts/56fa32b9-4a39-4367-8fcc-c520a65426ef

**Comment by Shreeyak** [comment]
[Uploading Screenshot from 2017-12-04 13-47-56.png...]

**Comment by Shreeyak** [comment]
![Screenshot from 2017-12-04 13-47-56.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58fb6dd0cc6965001a9640ba/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227e49f2793dd5b768ee11365558424baa53444d04bea6d37ef5f22e7a985903b9d8640c20c36b12faba8217bf01be71834cd6e5ef8e5edcfa7f74b9dfd0126754505a9bf54f34a7934acd59f448e64853a51b3264ee647b.png)

**Comment by jchernus** [comment]
Hey! I'm not sure what you mean - the screenshot attached, and all of the graphics that I saw in the video seem to have y2 in red.

**Comment by Shreeyak** [comment]
This was so long ago, I don't remember what I meant. Sorry. looks like all the labels are there. 

I'll close the issue.
