### ISSUE TITLE
letyrodri-kinematics-If I use float in my transformation matrix, it's not passing the tests.

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#730]
In this Quiz:

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/72800973-80cd-4828-81fd-b3390486892b/modules/8855de3f-2897-46c3-a805-628b5ecf045b/lessons/87c52cd9-09ba-4414-bc30-24ae18277d24/concepts/3a388487-c7f2-4324-8768-f50631871df0

If I use my matrix version, I'm not passing the Quiz. 
```
T = Matrix([[cos(q1)  ,0.0   ,sin(q1)   ,0.0],
            [0.0      ,1.0   ,0.0       ,0.0],
            [-sin(q1) ,0.0   ,cos(q1)   ,30.0],
            [0.0      ,0.0   ,0.0       ,1.0]])  
```

On the left, the matrix T in quiz solution. On the right, my T matrix solution.
![image](https://user-images.githubusercontent.com/9123307/33786222-03001972-dc47-11e7-8fd2-6c83bef02f4a.png)

It seems that it's a floating point precision issue. I used float in all my matrix values.

**Comment by karimchamaa** [comment]
Matrix is supporting floating point values! Your T[0][3] should be equal to 1.0 and not 0.0 so that's why you are getting the error.
