### ISSUE TITLE
vivek1108: Project repository link

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#74]
Project repository link points back to the same page, not github link. https://classroom.udacity.com/nanodegrees/nd209-beta/parts/f491093d-8e67-4eab-8102-87bae095ca79/modules/0573f9ff-2e23-48cd-87d0-af24d758348a/lessons/ef841d31-8c53-49b3-8da3-a9d1523adef0/concepts/6bd08af4-003a-419f-ad47-890ce75d5a9a

**Comment by diyjac** [comment]
Hi vivek!  It appears that the beta project's repository is [https://github.com/ryan-keenan/beta_rover](https://github.com/ryan-keenan/beta_rover).  The link is still incorrect, but at least you can play with the project.

**Comment by ryan-keenan** [comment]
Thanks for catching this guys, I now have this link updated in several places (hopefully all ;)
