### ISSUE TITLE
arek - T2 - Lesson 2: The Jetson TX2 - Part 7: SSH from Host

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#751]
arek - T2 - Lesson 2: The Jetson TX2 - Part 7: SSH from Host

Misspelling of command in 2 places: `ipconfig` should be `ifconfig` under step 1 and step 2.

Here's the link to beta classroom:

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/30b42f46-d5c7-433f-8719-fb6ea023d59a/modules/451b7eed-6813-422a-a4d0-ce5db5ee1bca/lessons/a53bb2e1-a399-449f-ae4d-fd9bd6ea1c6b/concepts/3c8538ec-0421-4569-9ae8-a6e84ada40b2

**Comment by karimchamaa** [comment]
Fixed
