### ISSUE TITLE
Term1-Kinematics-KR210 Forward Kinematics 1-Story board visible

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#753]

**Comment by letyrodridc** [comment]
I'm not sure if this is happening in the students version, but in beta-tester the last frame of Term1 Forward kinimatics is showing the story board.
![kinematics.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58864c41d037341a00051a26/125516c66e82c728ace21e0d46e39d94268f82bd86eaac01e81fe086264c22703d46f96925dde771e6417f54095c18ae41505f44f8a88128f5e56f74984019af80330b2b9b645bf9fa9015ad00bd2a8a4a84b0ba8c4dc9ec3d21e5889d02.png)

**Comment by sahiljuneja** [comment]
Hmmm.. could have sworn we had this edited. Thanks for reporting will have it fixed soon.
