### ISSUE TITLE
Term 1, Project Pick&Place, Rubric link

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#755]
In the Pick&Place Rubric, the link in Kinematics Analysis, Describe inverse kinematics... "here" is taking to the home page.
Rubric: https://review.udacity.com/#!/rubrics/972/view

Link: https://classroom.udacity.com/nanodegrees/nd209/parts/7b2fd2d7-e181-401e-977a-6158c77bf816/modules/8855de3f-2897-46c3-a805-628b5ecf045b/lessons/87c52cd9-09ba-4414-bc30-24ae18277d24/concepts/8d553d46-d5f3-4f71-9783-427d4dbffa3a

**Comment by sahiljuneja** [comment]
Good catch. They should be fixed now. Thanks!
