### ISSUE TITLE
T2 p3 launch file error

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#757]
Extending your Robot Creation - Launch Files

in the provided launch file example , there is a small issue which showed up during the beta testing 

```
<node name="rtabmap" pkg="rtabmap_ros" type="rtabmap" output="screen" args=”--delete_db_on_start”>
```

there is a small error with the quote format 
```
args=”--delete_db_on_start”>
```

the working replacement is 
```
 args="--delete_db_on_start">
```

**Comment by kylesf** [comment]
Fixed, thanks!
