### ISSUE TITLE
LKF L0306: Lab

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#759]
The picture about rqt_graph is too short. I had to copy and paste in Paintbrush to be able to see it. Why not use a kind of magnifying glass in ROI

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/d2337ea3-40a9-4717-af6d-4b6e17c28e3e/modules/e015f3a0-a7a3-44be-9bb9-91054b0e034e/lessons/72cae9de-deae-4579-93da-7e56bd5021fc/concepts/aac6c3ef-9d8d-4656-9a0f-2f0170a5931c

**Comment by karimchamaa** [comment]
you just have to click on it and it will maximize

**Comment by zenetio** [comment]
Yes, I did. But even so, the text is still not readable. Then I had to copy/paste into Paintbrush and then zoom it to be able to read.
