### ISSUE TITLE
L04E05: MCL

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#760]
The solution is firing an error with message "No such file or directory"

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/d2337ea3-40a9-4717-af6d-4b6e17c28e3e/modules/e015f3a0-a7a3-44be-9bb9-91054b0e034e/lessons/f45bb62d-a83c-4c9c-91bb-cbc11d155ccc/concepts/e3a9d449-b4de-40f3-91f7-87bb81525541

**Comment by karimchamaa** [comment]
![Screen Shot 2018-02-18 at 12.01.08 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59efda092b78160011a98ec6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216455fb6b7191a379ed0c2b50415f46bc21254d58eeb9cb74fce36f34985619e8d939567d956914fabbd41dbf09ba208f1e8db5efd91fc4fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae9445da0123466ee73356e0a.png)

**Comment by karimchamaa** [comment]
I don't see any error - reset your quiz

**Comment by zenetio** [comment]
My output
![p](https://user-images.githubusercontent.com/578337/36383731-d1b4e6d2-156b-11e8-8c17-36c5ebd22a69.JPG)

**Comment by zenetio** [comment]
I found the issue. My bad.
