### ISSUE TITLE
L05E02: Build MCL in C++

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#761]
I just comment out the print statement and got the error below. It seems something wrong with python

main.cpp:230:11: error: expected ‘;’ before string constant
     Print "I am ready for coding the MCL!"
           ^
Traceback (most recent call last):
  File "vm_main.py", line 33, in <module>
    import main
  File "/tmp/vmuser_idssarmdsd/main.py", line 2, in <module>
    import studentMain
  File "/tmp/vmuser_idssarmdsd/studentMain.py", line 4, in <module>
    call("./main.out")
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by karimchamaa** [comment]
[Uploading Screen Shot 2018-02-20 at 11.48.49 AM.png...]

**Comment by karimchamaa** [comment]
I got no error, remember to reset your quiz and system use a python compiler for the C++ code

**Comment by karimchamaa** [comment]
![Screen Shot 2018-02-20 at 11.48.49 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59efda092b78160011a98ec6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f36b7191a379ee0c2f59415b47bc30254d58eeb9cb74fce36f34985619e8d939567d956914fabbd41dbf09ba208f1e8db5efd91fc4fa2137a5dad11b61435c52dcbd4f3fb29842c259f34ae84c50a211346ae370326e0a.png)
