### ISSUE TITLE
L0509: Build MCL

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#762]
The video says that particles 1 and 3 occupy small space but particle 5 has the same value but it is not mentioned. I guess this might confuse the student if particle 5 is not mentioned as well.

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/d2337ea3-40a9-4717-af6d-4b6e17c28e3e/modules/e015f3a0-a7a3-44be-9bb9-91054b0e034e/lessons/9122dec6-37d4-46b6-a567-97ab8923f8ca/concepts/b3b47216-fc5a-4bf0-b8ce-b302e60e3354

**Comment by karimchamaa** [comment]
I didn't say particle 1 and 3 are the only one that occupies a small space so this should not confuse them. Thanks for reporting the issue
