### ISSUE TITLE
Term 2 - Computing the Posterior

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#766]
In beta link: https://classroom.udacity.com/nanodegrees/nd209-beta/parts/bece8892-4bc6-44e2-a5f6-53c2b3707ce4/modules/4b66b4d9-f728-4029-a7d1-9a77535dce8e/lessons/09ff9955-a893-43b2-a314-819a02f9231c/concepts/c2a0c279-383a-47cb-a1f2-91a1bf3a7724#

The step 0.1 should be added to the quiz.

![image](https://user-images.githubusercontent.com/9123307/36643123-4a88c650-1a3f-11e8-9f9a-bfbe2de3b990.png)

There are infinite numbers between 0.7 and 1.

**Comment by karimchamaa** [comment]
Thanks for reporting this
