### ISSUE TITLE
SLAM: L02E11 - Inverse Sensor Model

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#768]
The solution for case 1 does not match what we see in the picture that is missing Zk>Zmax or Zk<Zmin

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/bece8892-4bc6-44e2-a5f6-53c2b3707ce4/modules/4b66b4d9-f728-4029-a7d1-9a77535dce8e/lessons/09ff9955-a893-43b2-a314-819a02f9231c/concepts/fd2a50fc-9352-419d-8b30-e15b39af9c0c

**Comment by karimchamaa** [comment]
Added a comment for that. Thanks for reporting
