### ISSUE TITLE
Lab: path planning .BFS: Expansion Vector

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#771]
```You can see that the first cell was expanded 0 times whereas the goal cell was expanded 20 times. All the obstacles and some cells were never expanded and thus are showing a value of -1. ```

i am not sure if times is the correct word to use here . the main purpose of the expansion matrix is to record at which step that cell is expanded . i am not sure if we can use ``` times``` (how many time that cell is visited) here

**Comment by karimchamaa** [comment]
Thanks for reporting. Will go through it and fix them so they will be also consistent with the path planning lesson.
