### ISSUE TITLE
Path planning L0102

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#772]
In think in the quiz, to make the text more clear, is better to mention that the variable members in the classes must be initialized.

**Comment by karimchamaa** [comment]
I agree even though you can still assign values later in the main function. I made the changes in the task list:https://classroom.udacity.com/nanodegrees/nd209-beta/parts/b572e799-088a-4f3d-9e13-86a5d37f2ec3/modules/041a5cdb-bb0a-414b-a8bf-8b1eeb6c8bb0/lessons/de92bb3c-a163-4808-8335-b6ce5a79db08/concepts/e0600634-15a4-46f3-9ffb-2ae7a7618681 .Thanks for reporting.
