### ISSUE TITLE
Lab PP

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#773]
Please consider draw a graph with current position and the path executed until there.
https://classroom.udacity.com/nanodegrees/nd209-beta/parts/b572e799-088a-4f3d-9e13-86a5d37f2ec3/modules/041a5cdb-bb0a-414b-a8bf-8b1eeb6c8bb0/lessons/de92bb3c-a163-4808-8335-b6ce5a79db08/concepts/89705ca1-69f1-42e8-8316-c45e0512f19c

**Comment by karimchamaa** [comment]
Thanks for reporting. Will consider adding if I get many requests on that but currently think that the arrows and the final visualization quiz are helpful to see the path from start to goal
