### ISSUE TITLE
Project:Home Service - L04

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#775]
When I download gmapping from Git and try to catkin_make, I get an error openslam_gmapping dependency. It seems that the slam_gmapping is relate to openslam_gmapping. What to do here? Use just gmapping package from inside gmapping or need download, compile and install openslam_gmapping that is an svn package?

**Comment by karimchamaa** [comment]
We are working to get the dependencies in the workspace, for now you can install them manually with these 3 commands:
sudo apt-get install ros-kinetic-navigation
cd home/workspace/catkin_ws
source devel/setup.bash
rosdep -i install turtlebot_teleop
rosdep -i install turtlebot_gazebo

**Comment by karimchamaa** [comment]
Follow these instructions and let me know if you still can't get it to build:
cd /home/workspace/catkin_ws/src
git clone https://github.com/ros-perception/slam_gmapping
cd ..
source devel/setup.bash
rosdep -i install gmapping 
catkin_make

**Comment by zenetio** [comment]
I am using TX2 and yes, it worked now.
