### ISSUE TITLE
HSF project - L08 - Wall Follower

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#778]
There is a typo in gmapping Parameters item
"parameter valuees,"

https://classroom.udacity.com/nanodegrees/nd209-beta/parts/b572e799-088a-4f3d-9e13-86a5d37f2ec3/modules/041a5cdb-bb0a-414b-a8bf-8b1eeb6c8bb0/lessons/5a024889-3d4f-4f77-864d-7aa7b512511d/concepts/0823081c-ef32-4c7d-8731-dd51607f183e

**Comment by karimchamaa** [comment]
Fixed. Thanks
