### ISSUE TITLE
HSR project - L08- Wall Follower

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#779]
After run the wall follower I got a good map. But now when I try to save the file using the command rosrun map_server map_server mymap I get an error message saying that I am using a old map server interface and need switch to the new interface. What is this new interface that I could not find in internet?

**Comment by karimchamaa** [comment]
Never seen that error, maybe run an update/upgrade?

**Comment by zenetio** [comment]
Yes, I already did an upgrade with no success. This is weird because after got a good map definition in my TX2, now I cannot save it.

**Comment by zenetio** [comment]
Fixed!

**Comment by karimchamaa** [comment]
How did you fix it ? And what do you think was the error?

**Comment by zenetio** [comment]
The command line was wrong. I was ever typing map_server map_server when the correct command to save the map is map_server map_saver.

**Comment by karimchamaa** [comment]
oh ok
