### ISSUE TITLE
vivek1108: Rotation-translation pixel-transform

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#79]
In the notes, pixel angle and pixel distance are introduced without explanation of what they are. Will be nice to explain what these values are, and what is the effect of the calculations. In short we are doing p_new = p_o + R * p_pixels. So will be nice to provide a link to explain those calculations

**Comment by ryan-keenan** [comment]
Thanks for the suggestion, I've cleaned this up a lot now and used your other suggestion of introducing rotation matrices.  I think it makes a lot more sense now :)
