### ISSUE TITLE
vivek1108: rover angle

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#80]
Is there a reason why rover angle is measured with respect to y-axis vs x-axis? Typically, we express angles about x-axis and assume angles are measured about x-axis. Also, we assume that counterclockwise angles are positive, here clockwise rotation is taken as positive

**Comment by ryan-keenan** [comment]
Great point!  The default in Unity is apparently yaw measured clockwise from positive y.  I gather this is the way airplanes measure yaw as if it were a compass angle away from north.  But anyway, the standard in robotics is definitely counterclockwise from x, so I've converted the simulator itself and all angle references in the lesson to follow this standard.
