### ISSUE TITLE
vivek1108: explanation of math for transformation

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#81]
in l208 section on mapping from rover coordinates to worldmap, a lot of math is introduced without reference or reason for doing so. It will be nice to introduce some explanation on it. Also, we are in effect doing transformations, so will be nice to explain that here, adn provide links. Homogeneous matrices, rotation matrices, and transformation matrices can be introduced here, or at least be pointed to for more work.

**Comment by ryan-keenan** [comment]
Thanks for this suggestion, I've cleaned this section up and now describe this task as a rotation followed by a translation linking out to more information on each and introducing a simple rotation matrix.  I think it works better now :)
