### ISSUE TITLE
diyjac missing `action` subsection between L02E10 and L02E11?

### ISSUE THREAD

**Issue by diyjac** [udacity/robotics-beta-test-issues#93]
`L02E05` through `L02E08` is clearly belongs to the `perception` element of robotics.  Like wise `L02E09` and `L02E10` belongs to `decision making`, but there seems to be a missing subsection on `action`, even though at the beginning `L02E01` mention that `action` is an essential element.  It seems that `action` is just a sub part of `L02E12` as the `telemetry()` function and not a subsection by itself.  Please consider making `action` a subsection to make it just as important as `perception` and `decision making` in elements of robotics.

**Comment by ryan-keenan** [comment]
thanks for pointing this out John :)  I have now titled the last concept in the lesson "Action!" where I'm going through the autonomous navigation and mapping scripts.  I will flesh this out more but at least it exists now ;)
