### ISSUE TITLE
P01E06

### ISSUE THREAD

**Issue by stupsi99** [udacity/robotics-beta-test-issues#97]

**Comment by stupsi99** [comment]
It took me a long time to understand where the matrix entries from the destination matrix were coming from. I think a small image of what the points actually are would have been great! Also, I would suggest to comment in the code where the "dst_size" value is coming from.

**Comment by stupsi99** [comment]
Actually the very first image on that page is already quite good. Combine the transformed checkers board with a coordinate system and its clear how to get to the destination points. Also placing the original image above the transformed image would help (instead of having them side by side).

**Comment by ryan-keenan** [comment]
I've reorganized things on this page a bit to hopefully be more understandable.   We'll move forward now with making a video for this concept to help visualize things better.  Thanks for your suggestions here!
